"""Provider/plugin host IPC foundation models.

Phase 8B exposes wire helpers only. Production providers are still invoked
through the existing direct Python paths until routed host verticals land.
"""

from sase.host.wire import (
    HOST_CAP_IPC_V1,
    HOST_CAP_LLM_METADATA,
    HOST_CAP_MANIFEST_V1,
    HOST_CAP_XPROMPT_CATALOG,
    HOST_ERROR_CODES,
    HOST_OPERATION_FAMILIES,
    PROVIDER_HOST_IPC_WIRE_SCHEMA_VERSION,
    FakeInProcessHostTransport,
    HostActorWire,
    HostDeadlineWire,
    HostEnvironmentPolicyWire,
    HostEnvironmentRequirementWire,
    HostErrorWire,
    HostFallbackWire,
    HostLogRecordWire,
    HostManifestWire,
    HostNetworkPolicyWire,
    HostOperationSelectorWire,
    HostProcessPolicyWire,
    HostRequestEnvelopeWire,
    HostResourceUsageWire,
    HostResponseEnvelopeWire,
    HostSideEffectIntentWire,
    HostWorkspaceIdentityWire,
    host_request_from_dict,
    host_response_from_dict,
    host_wire_to_json_dict,
)

__all__ = [
    "HOST_CAP_IPC_V1",
    "HOST_CAP_LLM_METADATA",
    "HOST_CAP_MANIFEST_V1",
    "HOST_CAP_XPROMPT_CATALOG",
    "HOST_ERROR_CODES",
    "HOST_OPERATION_FAMILIES",
    "PROVIDER_HOST_IPC_WIRE_SCHEMA_VERSION",
    "FakeInProcessHostTransport",
    "HostActorWire",
    "HostDeadlineWire",
    "HostEnvironmentPolicyWire",
    "HostEnvironmentRequirementWire",
    "HostErrorWire",
    "HostFallbackWire",
    "HostLogRecordWire",
    "HostManifestWire",
    "HostNetworkPolicyWire",
    "HostOperationSelectorWire",
    "HostProcessPolicyWire",
    "HostRequestEnvelopeWire",
    "HostResourceUsageWire",
    "HostResponseEnvelopeWire",
    "HostSideEffectIntentWire",
    "HostWorkspaceIdentityWire",
    "host_request_from_dict",
    "host_response_from_dict",
    "host_wire_to_json_dict",
]
