"""Provider/plugin host IPC foundation models.

Phase 8C exposes a subprocess runtime for fake/no-op operations only.
Production providers are still invoked through the existing direct Python
paths until routed host verticals land.
"""

from sase.host.runtime import (
    DEFAULT_HOST_TIMEOUT_MS,
    MAX_HOST_LOG_BYTES,
    ProviderHostRuntime,
    ProviderHostRuntimeConfig,
    ProviderHostRuntimeError,
    redact_host_log,
    run_provider_host_stdio,
)
from sase.host.wire import (
    HOST_CAP_IPC_V1,
    HOST_CAP_LLM_METADATA,
    HOST_CAP_MANIFEST_V1,
    HOST_CAP_XPROMPT_CATALOG,
    HOST_ERROR_CODES,
    HOST_OPERATION_FAMILIES,
    PROVIDER_HOST_IPC_WIRE_SCHEMA_VERSION,
    FakeInProcessHostTransport,
    HostActorWire,
    HostDeadlineWire,
    HostEnvironmentPolicyWire,
    HostEnvironmentRequirementWire,
    HostErrorWire,
    HostFallbackWire,
    HostLogRecordWire,
    HostManifestWire,
    HostNetworkPolicyWire,
    HostOperationSelectorWire,
    HostProcessPolicyWire,
    HostRequestEnvelopeWire,
    HostResourceUsageWire,
    HostResponseEnvelopeWire,
    HostSideEffectIntentWire,
    HostWorkspaceIdentityWire,
    host_request_from_dict,
    host_response_from_dict,
    host_wire_to_json_dict,
)

__all__ = [
    "HOST_CAP_IPC_V1",
    "HOST_CAP_LLM_METADATA",
    "HOST_CAP_MANIFEST_V1",
    "HOST_CAP_XPROMPT_CATALOG",
    "HOST_ERROR_CODES",
    "HOST_OPERATION_FAMILIES",
    "DEFAULT_HOST_TIMEOUT_MS",
    "MAX_HOST_LOG_BYTES",
    "PROVIDER_HOST_IPC_WIRE_SCHEMA_VERSION",
    "FakeInProcessHostTransport",
    "HostActorWire",
    "HostDeadlineWire",
    "HostEnvironmentPolicyWire",
    "HostEnvironmentRequirementWire",
    "HostErrorWire",
    "HostFallbackWire",
    "HostLogRecordWire",
    "HostManifestWire",
    "HostNetworkPolicyWire",
    "HostOperationSelectorWire",
    "HostProcessPolicyWire",
    "HostRequestEnvelopeWire",
    "HostResourceUsageWire",
    "HostResponseEnvelopeWire",
    "HostSideEffectIntentWire",
    "HostWorkspaceIdentityWire",
    "ProviderHostRuntime",
    "ProviderHostRuntimeConfig",
    "ProviderHostRuntimeError",
    "host_request_from_dict",
    "host_response_from_dict",
    "host_wire_to_json_dict",
    "redact_host_log",
    "run_provider_host_stdio",
]
