"""Beautiful agent tab strip: descriptors, accents, tiers, and overflow.

Public facade: the render model lives in ``_agent_tab_strip_model``,
the tier/overflow helpers live in ``_agent_tab_strip_overflow``, and the
clickable widget lives in ``_agent_tab_strip_strip``. Only the public
names below are re-exported here.
"""

from ._agent_tab_strip_model import (
    ACTIVE_PILL_LEFT,
    ACTIVE_PILL_RIGHT,
    ACTIVE_TEXT_STYLE,
    ARRIVAL_DOT,
    ATTENTION_STYLES,
    INVALID_LABEL_STYLE,
    KIND_DIVIDER,
    LOCAL_MACHINE_GLYPH,
    LOCAL_MACHINE_STYLE,
    MACHINE_GLYPH,
    MACHINE_GLYPH_STYLE,
    MAIN_LABEL_STYLE,
    NEUTRAL_COUNT_STYLE,
    OVERFLOW_NEXT_ID,
    OVERFLOW_PREV_ID,
    SEPARATOR_STYLE,
    STALE_LABEL_STYLE,
    TAB_SEPARATOR,
    AgentTabDescriptor,
    AgentTabEmptyKind,
    AgentTabEmptyState,
    AgentTabHealth,
    AgentTabStripTier,
    agent_tab_accent_for_name,
    agent_tab_chip_for_key,
    agent_tab_empty_state,
    agent_tab_glyph_style,
    agent_tab_label_style,
    local_machine_tab_label,
)
from ._agent_tab_strip_strip import AgentTabStrip

__all__ = [
    "ACTIVE_PILL_LEFT",
    "ACTIVE_PILL_RIGHT",
    "ACTIVE_TEXT_STYLE",
    "ARRIVAL_DOT",
    "ATTENTION_STYLES",
    "INVALID_LABEL_STYLE",
    "KIND_DIVIDER",
    "LOCAL_MACHINE_GLYPH",
    "LOCAL_MACHINE_STYLE",
    "MACHINE_GLYPH",
    "MACHINE_GLYPH_STYLE",
    "MAIN_LABEL_STYLE",
    "NEUTRAL_COUNT_STYLE",
    "OVERFLOW_NEXT_ID",
    "OVERFLOW_PREV_ID",
    "SEPARATOR_STYLE",
    "STALE_LABEL_STYLE",
    "TAB_SEPARATOR",
    "AgentTabDescriptor",
    "AgentTabEmptyKind",
    "AgentTabEmptyState",
    "AgentTabHealth",
    "AgentTabStrip",
    "AgentTabStripTier",
    "agent_tab_accent_for_name",
    "agent_tab_chip_for_key",
    "agent_tab_empty_state",
    "agent_tab_glyph_style",
    "agent_tab_label_style",
    "local_machine_tab_label",
]
