"""Constants for subscription-capacity usage state."""

PROVIDER_USAGE_OBSERVATION_SCHEMA_VERSION = 1
PROVIDER_USAGE_PUBLIC_SCHEMA_VERSION = 1
PROVIDER_USAGE_STORE_SCHEMA_VERSION = 1
PROVIDER_USAGE_STATE_FILENAME = "llm_provider_usage.json"

DEFAULT_USAGE_CADENCE_SECONDS = 300.0
DEFAULT_USAGE_WARN_PERCENT = 75.0
DEFAULT_USAGE_CRITICAL_PERCENT = 90.0

PROVIDER_USAGE_STORE_WRITE_RECORDED = "recorded"
PROVIDER_USAGE_STORE_WRITE_UNCHANGED = "unchanged"
PROVIDER_USAGE_STORE_WRITE_STALE_WRITER = "stale_writer"
PROVIDER_USAGE_STORE_WRITE_STATUSES = (
    PROVIDER_USAGE_STORE_WRITE_RECORDED,
    PROVIDER_USAGE_STORE_WRITE_UNCHANGED,
    PROVIDER_USAGE_STORE_WRITE_STALE_WRITER,
)

PROVIDER_USAGE_REFRESH_RESERVED = "reserved"
PROVIDER_USAGE_REFRESH_JOINED = "joined"
PROVIDER_USAGE_REFRESH_DEFERRED = "deferred"
PROVIDER_USAGE_REFRESH_STATUSES = (
    PROVIDER_USAGE_REFRESH_RESERVED,
    PROVIDER_USAGE_REFRESH_JOINED,
)
PROVIDER_USAGE_REFRESH_ADMIT_STATUSES = (
    PROVIDER_USAGE_REFRESH_RESERVED,
    PROVIDER_USAGE_REFRESH_JOINED,
    PROVIDER_USAGE_REFRESH_DEFERRED,
)

__all__ = [
    "DEFAULT_USAGE_CADENCE_SECONDS",
    "DEFAULT_USAGE_CRITICAL_PERCENT",
    "DEFAULT_USAGE_WARN_PERCENT",
    "PROVIDER_USAGE_OBSERVATION_SCHEMA_VERSION",
    "PROVIDER_USAGE_PUBLIC_SCHEMA_VERSION",
    "PROVIDER_USAGE_REFRESH_ADMIT_STATUSES",
    "PROVIDER_USAGE_REFRESH_DEFERRED",
    "PROVIDER_USAGE_REFRESH_JOINED",
    "PROVIDER_USAGE_REFRESH_RESERVED",
    "PROVIDER_USAGE_REFRESH_STATUSES",
    "PROVIDER_USAGE_STATE_FILENAME",
    "PROVIDER_USAGE_STORE_SCHEMA_VERSION",
    "PROVIDER_USAGE_STORE_WRITE_RECORDED",
    "PROVIDER_USAGE_STORE_WRITE_STALE_WRITER",
    "PROVIDER_USAGE_STORE_WRITE_STATUSES",
    "PROVIDER_USAGE_STORE_WRITE_UNCHANGED",
]
