"""Python presentation facade for historical SASE statistics."""

from sase.stats._perf_view import build_perf_view
from sase.stats._view_models import (
    PerfCoverage,
    PerfHeroTile,
    PerfLatencyRow,
    PerfLatencySection,
    PerfLaunchStage,
    PerfLaunchesSection,
    PerfLogCoverage,
    PerfProbeStatus,
    PerfSlowestSession,
    PerfStallContextRow,
    PerfStallEventRow,
    PerfStallsSection,
    PerfStartupSection,
    PerfStartupStageRow,
    PerfTelemetryCoverage,
    PerfView,
)
from sase.stats.query import query_activity_stats, query_run_stats
from sase.stats.ranges import (
    DEFAULT_PRESET,
    PRESETS,
    PRESET_ORDER,
    PresetKey,
    RangePreset,
    StatsRange,
    parse_custom_range,
    resolve_preset,
)
from sase.stats.views import StatisticsViews, build_statistics_views

__all__ = [
    "DEFAULT_PRESET",
    "PRESETS",
    "PRESET_ORDER",
    "PerfCoverage",
    "PerfHeroTile",
    "PerfLatencyRow",
    "PerfLatencySection",
    "PerfLaunchStage",
    "PerfLaunchesSection",
    "PerfLogCoverage",
    "PerfProbeStatus",
    "PerfSlowestSession",
    "PerfStallContextRow",
    "PerfStallEventRow",
    "PerfStallsSection",
    "PerfStartupSection",
    "PerfStartupStageRow",
    "PerfTelemetryCoverage",
    "PerfView",
    "PresetKey",
    "RangePreset",
    "StatisticsViews",
    "StatsRange",
    "build_perf_view",
    "build_statistics_views",
    "parse_custom_range",
    "query_activity_stats",
    "query_run_stats",
    "resolve_preset",
]
