"""Notification system: data model, storage, and helpers."""

from sase.notifications.catalog import (
    NotificationInfo,
    list_notification_infos,
    notification_info_to_json,
    resolve_notification_ref,
)
from sase.notifications.filters import (
    ClientNotificationSnapshot,
    KNOWN_SEMANTIC_TYPES,
    NotificationCounts,
    SuppressionRule,
    classify_notification,
    compute_counts,
    filter_notifications_for_client,
    is_suppressed_for_client,
    parse_suppression_rules,
    read_notification_snapshot_for_client,
    suppressed_types_for_client,
)
from sase.notifications.models import (
    Notification,
    format_relative_time,
    format_relative_until,
)
from sase.notifications.priority import is_error, is_priority
from sase.notifications.senders import (
    notify_axe_error_digest,
    notify_hitl_request,
    notify_mentors_complete,
    notify_sync_result,
    notify_workflow_complete,
)
from sase.notifications.store import (
    append_notification,
    dismiss_notifications_matching_agents,
    expire_due_snoozes,
    load_notifications,
    mark_all_read,
    mark_dismissed,
    mark_many_dismissed,
    mark_muted,
    mark_read,
    mark_snoozed,
    read_notification_snapshot,
    rewrite_notifications,
)

__all__ = [
    "ClientNotificationSnapshot",
    "KNOWN_SEMANTIC_TYPES",
    "Notification",
    "NotificationCounts",
    "NotificationInfo",
    "SuppressionRule",
    "append_notification",
    "classify_notification",
    "compute_counts",
    "filter_notifications_for_client",
    "is_suppressed_for_client",
    "parse_suppression_rules",
    "read_notification_snapshot_for_client",
    "suppressed_types_for_client",
    "dismiss_notifications_matching_agents",
    "expire_due_snoozes",
    "format_relative_time",
    "format_relative_until",
    "is_error",
    "is_priority",
    "list_notification_infos",
    "load_notifications",
    "mark_all_read",
    "mark_dismissed",
    "mark_many_dismissed",
    "mark_muted",
    "mark_read",
    "mark_snoozed",
    "notification_info_to_json",
    "read_notification_snapshot",
    "resolve_notification_ref",
    "rewrite_notifications",
    "notify_axe_error_digest",
    "notify_hitl_request",
    "notify_mentors_complete",
    "notify_sync_result",
    "notify_workflow_complete",
]
