[tox]
min_version = 4.0
env_list = py312, py313, py314

[testenv]
deps = .[dev]
commands =
    coverage erase
    pytest {posargs:--cov=sase --cov-report=term-missing --cov-branch}
    coverage report
