"""Tests for sase.completion.emit_bash over hand-built specs and the live tree."""

from __future__ import annotations

from typing import Any

import pytest

from sase.completion.build import build_spec
from sase.completion.emit_bash import emit_bash
from sase.completion.kinds import ValueKind
from sase.completion.model import (
    CommandSpec,
    CompletionSpec,
    OptionSpec,
    PositionalSpec,
)


def _option(**overrides: Any) -> OptionSpec:
    base: dict[str, Any] = {
        "strings": ("-j", "--json"),
        "dest": "json",
        "summary": "Emit machine-readable JSON",
        "takes_value": False,
        "repeatable": False,
        "choices": None,
        "kind": None,
        "hidden": False,
    }
    base.update(overrides)
    return OptionSpec(**base)


def _positional(**overrides: Any) -> PositionalSpec:
    base: dict[str, Any] = {
        "metavar": "ID",
        "dest": "id",
        "summary": "Full or shorthand issue ID",
        "nargs": None,
        "choices": None,
        "kind": ValueKind.BEAD,
        "is_remainder": False,
    }
    base.update(overrides)
    return PositionalSpec(**base)


def _command(**overrides: Any) -> CommandSpec:
    base: dict[str, Any] = {
        "name": "show",
        "path": ("bead", "show"),
        "aliases": (),
        "hidden": False,
        "summary": "Show issue details",
        "options": (),
        "positionals": (),
        "subcommands": (),
        "default_child": None,
        "mutex_groups": (),
    }
    base.update(overrides)
    return CommandSpec(**base)


def _spec(*children: CommandSpec, **root_overrides: Any) -> CompletionSpec:
    root = _command(
        name="sase",
        path=(),
        summary="",
        subcommands=children,
        **root_overrides,
    )
    return CompletionSpec(prog="sase", version="0.0-test", root=root)


def _fn(script: str, name: str) -> str:
    start = script.index(f"{name}() {{")
    end = script.index("\n}", start)
    return script[start : end + 2]


def test_emit_bash_registration_and_placeholder() -> None:
    script = emit_bash(_spec())
    assert "complete -o default -F _sase sase" in script
    assert "__sase_candidates()" in script
    assert "_sase()" in script
    assert "Generated by sase completion bash" in script


def test_nested_command_path_is_reachable() -> None:
    listing = _command(name="list", path=("bead", "list"), summary="List beads")
    show = _command(
        name="show",
        path=("bead", "show"),
        summary="Show a bead",
        positionals=(_positional(),),
    )
    bead = _command(
        name="bead",
        path=("bead",),
        summary="Inspect beads",
        default_child="list",
        subcommands=(listing, show),
    )
    script = emit_bash(_spec(bead))
    subs_root = _fn(script, "_sase_subs")
    assert "list show" in _fn(script, "_sase_subs") or "list" in subs_root
    assert "/bead) _sase_reply=" in script
    assert "list show" in script
    assert "/bead/show) _sase_reply=" in _fn(script, "_sase_pos")
    assert "kind:bead" in script


def test_static_choices_and_kind_placeholders() -> None:
    fmt = _option(
        strings=("-f", "--format"),
        dest="format",
        summary="Output format",
        takes_value=True,
        choices=("json", "text"),
    )
    project = _option(
        strings=("-p", "--project"),
        dest="project",
        summary="Project name",
        takes_value=True,
        kind=ValueKind.PROJECT,
    )
    out = _option(
        strings=("-o", "--output"),
        dest="output",
        summary="Write to a file",
        takes_value=True,
        kind=ValueKind.PATH,
    )
    directory = _option(
        strings=("-d", "--dir"),
        dest="dir",
        summary="A directory",
        takes_value=True,
        kind=ValueKind.DIR,
    )
    script = emit_bash(_spec(_command(options=(fmt, project, out, directory))))
    optval = _fn(script, "_sase_optval")
    assert "choices:json text" in optval
    assert "kind:project" in optval
    assert "kind:path" in optval
    assert "kind:dir" in optval
    assert "__sase_candidates" in script


def test_aliases_are_matched_but_not_offered() -> None:
    patch = _command(
        name="patch",
        path=("patch",),
        aliases=("changespec",),  # legacy command alias
        summary="Inspect patches",
    )
    script = emit_bash(_spec(patch))
    assert "changespec" not in _fn(script, "_sase_subs")  # legacy command alias
    assert "patch" in _fn(script, "_sase_subs")
    child = _fn(script, "_sase_child")
    assert "changespec" in child  # legacy command alias
    assert "/patch" in child


def test_plus_one_is_quoted() -> None:
    plus = _command(
        name="+1",
        path=("bead", "+1"),
        summary="Add a plus-one",
        positionals=(_positional(),),
    )
    listing = _command(name="list", path=("bead", "list"), summary="List beads")
    bead = _command(
        name="bead",
        path=("bead",),
        summary="Inspect beads",
        subcommands=(plus, listing),
    )
    script = emit_bash(_spec(bead))
    assert "_sase_reply='+1 list'" in script
    assert "/bead/+1" in script
    assert "'/bead|+1'" in script


def test_dollar_and_quote_in_choice_are_quoted() -> None:
    option = _option(
        strings=("-m", "--mode"),
        dest="mode",
        summary="Don't use $this",
        takes_value=True,
        choices=("don't", "$x"),
    )
    script = emit_bash(_spec(_command(options=(option,))))
    optval = _fn(script, "_sase_optval")
    assert "$x" in optval
    assert r"'\''" in optval


def test_hidden_option_is_not_emitted() -> None:
    hidden = _option(
        strings=("--secret",),
        dest="secret",
        summary="Hidden",
        hidden=True,
    )
    visible = _option()
    script = emit_bash(_spec(_command(options=(hidden, visible))))
    assert "--secret" not in script
    assert "--json" in script


@pytest.fixture(scope="module")
def live_script() -> str:
    return emit_bash(build_spec())


def test_live_script_registers_and_hides_helper_bridge(live_script: str) -> None:
    assert "complete -o default -F _sase sase" in live_script
    assert "helper-bridge" not in live_script
    assert "__sase_candidates()" in live_script


def test_live_script_treats_changespec_as_alias(live_script: str) -> None:
    assert "changespec" not in _fn(live_script, "_sase_subs")  # legacy command alias
    assert "changespec" in _fn(live_script, "_sase_child")  # legacy command alias
    assert "/patch" in _fn(live_script, "_sase_child")


def test_live_script_plus_one_and_nested_paths(live_script: str) -> None:
    assert "/bead/+1" in live_script
    assert "/completion/zsh" in live_script or "/completion" in live_script
    assert "_sase_reply='+1 " in _fn(live_script, "_sase_subs")
