"""Tests for sase.completion.emit_fish over hand-built specs and the live tree."""

from __future__ import annotations

import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Any

import pytest

from sase.completion.build import build_spec
from sase.completion.emit_fish import emit_fish
from sase.completion.kinds import ValueKind
from sase.completion.model import (
    CommandSpec,
    CompletionSpec,
    OptionSpec,
    PositionalSpec,
)


def _option(**overrides: Any) -> OptionSpec:
    base: dict[str, Any] = {
        "strings": ("-j", "--json"),
        "dest": "json",
        "summary": "Emit machine-readable JSON",
        "takes_value": False,
        "repeatable": False,
        "choices": None,
        "kind": None,
        "hidden": False,
    }
    base.update(overrides)
    return OptionSpec(**base)


def _positional(**overrides: Any) -> PositionalSpec:
    base: dict[str, Any] = {
        "metavar": "ID",
        "dest": "id",
        "summary": "Full or shorthand issue ID",
        "nargs": None,
        "choices": None,
        "kind": ValueKind.BEAD,
        "is_remainder": False,
    }
    base.update(overrides)
    return PositionalSpec(**base)


def _command(**overrides: Any) -> CommandSpec:
    base: dict[str, Any] = {
        "name": "show",
        "path": ("bead", "show"),
        "aliases": (),
        "hidden": False,
        "summary": "Show issue details",
        "options": (),
        "positionals": (),
        "subcommands": (),
        "default_child": None,
        "mutex_groups": (),
    }
    base.update(overrides)
    return CommandSpec(**base)


def _spec(*children: CommandSpec, **root_overrides: Any) -> CompletionSpec:
    root = _command(
        name="sase",
        path=(),
        summary="",
        subcommands=children,
        **root_overrides,
    )
    return CompletionSpec(prog="sase", version="0.0-test", root=root)


def test_emit_fish_registration_and_helper() -> None:
    script = emit_fish(_spec())
    assert "complete -c sase -e" in script
    assert "complete -c sase -f" in script
    assert "function __sase_cmd" in script
    assert "function __sase_candidates" in script
    assert "Generated by sase completion fish" in script


def test_candidates_helper_resolves_sase_and_calls_fast_path() -> None:
    script = emit_fish(_spec())
    assert "function __sase_run" in script
    assert r"/sase_[0-9]+/\.venv/bin/sase$" in script
    assert "__sase_run completion candidates $argv[1] 2>/dev/null" in script


def test_nested_command_path_and_descriptions() -> None:
    listing = _command(name="list", path=("bead", "list"), summary="List beads")
    show = _command(
        name="show",
        path=("bead", "show"),
        summary="Show a bead",
        positionals=(_positional(),),
    )
    bead = _command(
        name="bead",
        path=("bead",),
        summary="Inspect beads",
        default_child="list",
        subcommands=(listing, show),
    )
    script = emit_fish(_spec(bead))
    assert "-n '__sase_cmd /'" in script
    assert "-a 'bead'" in script
    assert "-d 'Inspect beads'" in script
    assert "-n '__sase_cmd /bead'" in script
    assert "-a 'show'" in script
    assert "-a 'list'" in script
    assert "(__sase_candidates bead)" in script


def test_static_choices_and_kind_calls() -> None:
    fmt = _option(
        strings=("-f", "--format"),
        dest="format",
        summary="Output format",
        takes_value=True,
        choices=("json", "text"),
    )
    project = _option(
        strings=("-p", "--project"),
        dest="project",
        summary="Project name",
        takes_value=True,
        kind=ValueKind.PROJECT,
    )
    out = _option(
        strings=("-o", "--output"),
        dest="output",
        summary="Write to a file",
        takes_value=True,
        kind=ValueKind.PATH,
    )
    directory = _option(
        strings=("-d", "--dir"),
        dest="dir",
        summary="A directory",
        takes_value=True,
        kind=ValueKind.DIR,
    )
    script = emit_fish(_spec(_command(options=(fmt, project, out, directory))))
    assert "-s 'f' -l 'format' -xa 'json text'" in script
    assert "(__sase_candidates project)" in script
    assert "-rF" in script
    assert "(__fish_complete_directories)" in script


def test_run_prompt_positional_combines_files_and_xprompts() -> None:
    prompt = _positional(
        metavar="PROMPT",
        dest="prompt",
        summary="Prompt text",
        nargs="?",
        choices=None,
        kind=None,
    )
    script = emit_fish(
        _spec(_command(name="run", path=("run",), positionals=(prompt,)))
    )
    assert "function __sase_run_prompt_fragment" in script
    assert "function __sase_run_prompt_candidates" in script
    assert "-rFa '(__sase_run_prompt_candidates)'" in script
    assert "set kind directive" in script
    assert "set kind artifact_ref" in script


def test_aliases_are_matched_but_not_offered() -> None:
    patch = _command(
        name="patch",
        path=("patch",),
        aliases=("changespec",),  # legacy command alias
        summary="Inspect patches",
    )
    script = emit_fish(_spec(patch))
    assert "-a 'patch'" in script
    assert "-a 'changespec'" not in script  # legacy command alias
    assert "'/|changespec'" in script  # legacy command alias
    assert "echo -n '/patch'" in script or "echo -n /patch" in script


def test_plus_one_and_description_quoting() -> None:
    plus = _command(
        name="+1",
        path=("bead", "+1"),
        summary="Don't use $this",
        positionals=(_positional(),),
    )
    listing = _command(name="list", path=("bead", "list"), summary="List beads")
    bead = _command(
        name="bead",
        path=("bead",),
        summary="Inspect beads",
        subcommands=(plus, listing),
    )
    script = emit_fish(_spec(bead))
    assert "-a '+1'" in script
    assert "-n '__sase_cmd /bead/+1'" in script
    assert "-d 'Don'\\''t use $this'" in script
    assert "$this" in script


def test_hidden_option_is_not_emitted() -> None:
    hidden = _option(
        strings=("--secret",),
        dest="secret",
        summary="Hidden",
        hidden=True,
    )
    visible = _option()
    script = emit_fish(_spec(_command(options=(hidden, visible))))
    assert "--secret" not in script
    assert "secret" not in script
    assert "-l 'json'" in script


@pytest.fixture(scope="module")
def live_script() -> str:
    return emit_fish(build_spec())


def test_live_script_registers_and_hides_helper_bridge(live_script: str) -> None:
    assert "complete -c sase -e" in live_script
    assert "function __sase_cmd" in live_script
    assert "helper-bridge" not in live_script


def test_live_script_treats_changespec_as_alias(live_script: str) -> None:
    assert "-a 'changespec'" not in live_script  # legacy command alias
    assert "-a 'patch'" in live_script
    assert "changespec" in live_script  # legacy command alias


def test_live_script_plus_one_quoted(live_script: str) -> None:
    assert "-a '+1'" in live_script
    assert "__sase_cmd /bead/+1" in live_script


_FISH = shutil.which("fish")


@pytest.mark.skipif(_FISH is None, reason="fish is not on PATH")
def test_fish_sources_generated_script(tmp_path: Path, live_script: str) -> None:
    fish = _FISH
    assert fish is not None
    path = tmp_path / "sase.fish"
    path.write_text(live_script, encoding="utf-8")
    result = subprocess.run(
        [fish, "-c", f"source {shlex.quote(str(path))}; functions -q __sase_cmd"],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr


@pytest.mark.skipif(_FISH is None, reason="fish is not on PATH")
@pytest.mark.parametrize(
    ("typed", "expected"),
    [
        ('sase run "ask #zz', "ask #zzz-fixture-xprompt"),
        ('sase run "ask %mo', "ask %model"),
        ('sase run "ask @file:e', "ask @file:explicit:abc123"),
    ],
)
def test_fish_completes_run_prompt_embedded_markers(
    tmp_path: Path,
    live_script: str,
    typed: str,
    expected: str,
) -> None:
    fish = _FISH
    assert fish is not None
    script = tmp_path / "sase.fish"
    script.write_text(live_script, encoding="utf-8")
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    fixture = bin_dir / "sase"
    fixture.write_text(
        "#!/usr/bin/env bash\n"
        'if [[ "$1" == completion && "$2" == candidates ]]; then\n'
        '  case "$3" in\n'
        "    xprompt) printf 'zzz-fixture-xprompt\\tA fixture xprompt\\n' ;;\n"
        "    directive) printf 'model\\tOverride the LLM model\\n' ;;\n"
        "    artifact_ref) printf 'file:explicit:abc123\\tScreenshot\\n' ;;\n"
        "  esac\n"
        "fi\n",
        encoding="utf-8",
    )
    fixture.chmod(0o755)
    snippet = (
        f"set -gx PATH {shlex.quote(str(bin_dir))} $PATH; "
        f"source {shlex.quote(str(script))}; "
        f"complete -C {shlex.quote(typed)}"
    )
    result = subprocess.run(
        [fish, "-c", snippet],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert expected in result.stdout, result.stdout
