"""Tests for repository inventory generated by ``sase memory init``."""

from __future__ import annotations

from pathlib import Path

import pytest

from sase.amd.constants import PROVIDER_SHIM_FILES
from tests.main.init_memory_handler_helpers import (
    SASE_MEMORY_HEADER,
    patch_standard_paths,
    run_handler,
    single_line,
    write,
)


def test_init_memory_uses_local_linked_repos_for_project_and_global_for_home(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )

    # The project config uses the canonical ``linked_repos`` key while the
    # global config keeps the deprecated ``sibling_repos`` alias, proving both
    # the canonical key and the legacy fallback drive memory generation.
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
linked_repos:
  - name: core
    path: ../local-core
    description: Local Rust core.
""",
    )
    write(
        config_dir / "sase.yml",
        """
sibling_repos:
  - name: github
    path: /global/github
    description: Global GitHub plugin.
""",
    )

    assert run_handler() == 0
    out = capsys.readouterr().out
    assert "init memory: initialized memory" in out

    project_memory = (project_root / "sase" / "memory" / "sase.md").read_text()
    home_memory = (home_root / "sase" / "memory" / "sase.md").read_text()
    assert "`core`: Local Rust core." in project_memory
    assert "`github`: Global GitHub plugin." not in project_memory
    assert "../local-core" not in project_memory
    assert "`github`: Global GitHub plugin." in home_memory
    assert "`core`: Local Rust core." not in home_memory
    assert "/global/github" not in home_memory
    assert SASE_MEMORY_HEADER in project_memory
    assert SASE_MEMORY_HEADER in home_memory

    repo_trigger = (
        "When you need to read or modify files in any repository other than your "
        "own workspace checkout, agents MUST use your `/sase_repo` skill first."
    )
    for memory in (project_memory, home_memory):
        memory_line = single_line(memory)
        assert "## Repositories" in memory
        assert repo_trigger in memory_line
        assert "another SASE project's repo" in memory_line
        assert "GitHub repo not linked to the current project" in memory_line
        assert "Open different-project and unlinked GitHub repos as external repos" in (
            memory_line
        )
        assert "Use the path it prints as the only path for reads and writes" in (
            memory_line
        )
        assert (
            "This rule applies regardless of transport. Fetching a repository's "
            "files or history over the web"
        ) in memory_line
        assert "raw.githubusercontent.com" in memory_line
        assert "GitHub-API/`gh` file-content reads" in memory_line
        assert (
            "Web tools remain appropriate only for content a checkout does not contain"
        ) in memory_line
        assert (
            "IMPORTANT REMINDER: Do NOT locate, clone, or web-fetch another "
            "repo's contents any other way than by using `/sase_repo`!"
        ) in memory_line
        assert 'sase repo open <linked_repo> -r "<reason>"' not in memory

    for root in (project_root, home_root):
        assert not (root / "sase" / "memory" / "long").exists()
        assert (root / "sase" / "memory" / "README.md").is_file()
        readme = (root / "sase" / "memory" / "README.md").read_text()
        assert "`sase memory list`" in readme
        assert "`sase memory init`" in readme
        assert "`memory_sase_template`" in readme
        assert "`memory_readme_template`" in readme
        assert "Non-README Markdown files live directly under `sase/memory/`" in readme
        assert "`type: long` notes are detailed reference material" in readme
        agents = (root / "AGENTS.md").read_text()
        assert "### 1. SASE = Structured Agentic Software Engineering (sase)" in agents
        assert "@sase/memory/sase.md" not in agents
        # Provider files are byte-for-byte copies of ``AGENTS.md``.
        for filename in PROVIDER_SHIM_FILES:
            assert (root / filename).read_text() == agents


def test_init_memory_excludes_auto_clone_and_does_not_inject_managed_research(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
linked_repos:
  - name: core
    path: ../core
    description: Always-present core.
    auto_clone: true
  - name: plugin
    path: ../plugin
    description: Lazy plugin.
""",
    )

    assert run_handler() == 0

    memory = (project_root / "sase" / "memory" / "sase.md").read_text(encoding="utf-8")
    assert "`core`: Always-present core." not in memory
    assert "`plugin`: Lazy plugin." in memory
    assert "project--research" not in memory


def test_init_memory_renders_project_and_home_sidecars_with_expected_slugs(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "sase"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
repos:
  sidecar:
    - name: research
      description: Durable SASE research reports and generated media.
    - name: reports
      repo: example-org/custom-reports
      description: Project reports.
""",
    )
    write(
        config_dir / "sase.yml",
        """
repos:
  sidecar:
    - name: notes
      description: Home notes.
""",
    )

    assert run_handler() == 0

    project_memory = (project_root / "sase" / "memory" / "sase.md").read_text()
    home_memory = (home_root / "sase" / "memory" / "sase.md").read_text()
    assert (
        "- `sase--research`: Durable SASE research reports and generated media."
        in project_memory
    )
    assert "- `custom-reports`: Project reports." in project_memory
    assert "`notes`: Home notes." not in project_memory
    assert "- `notes`: Home notes." in home_memory
    assert "sase--research" not in home_memory
    assert "custom-reports" not in home_memory


def test_init_memory_skips_auto_cloned_and_disabled_sidecars_before_validation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
repos:
  sidecar:
    - auto_clone: true
    - disabled: true
    - name: artifacts
      description: Lazy project artifacts.
""",
    )

    assert run_handler() == 0

    memory = (project_root / "sase" / "memory" / "sase.md").read_text(encoding="utf-8")
    assert "- `project--artifacts`: Lazy project artifacts." in memory


def test_init_memory_default_linked_repos_opt_out(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
default_linked_repos: false
linked_repos: []
""",
    )

    assert run_handler() == 0

    memory = (project_root / "sase" / "memory" / "sase.md").read_text(encoding="utf-8")
    assert "project--research" not in memory


def test_init_memory_reports_missing_linked_repo_descriptions(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
linked_repos:
  - name: core
    path: ../sase-core
""",
    )

    assert run_handler() == 1
    err = capsys.readouterr().err
    assert "cannot generate project memory" in err
    assert "field 'description'" in err
    assert not (project_root / "sase" / "memory").exists()


def test_init_memory_reports_missing_sidecar_descriptions(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
repos:
  sidecar:
    - name: research
""",
    )

    assert run_handler() == 1
    err = capsys.readouterr().err
    assert "cannot generate project memory" in err
    assert "repos.sidecar[0] ('research')" in err
    assert "field 'description'" in err
    assert not (project_root / "sase" / "memory").exists()


def test_init_memory_omits_minimal_hidden_agents_sidecar(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
repos:
  sidecar:
    - name: agents
      auto_clone: true
""",
    )

    assert run_handler() == 0

    memory = (project_root / "sase" / "memory" / "sase.md").read_text(encoding="utf-8")
    assert "project--agents" not in memory
