"""Tests for managed AGENTS memory generated by ``sase memory init``."""

from __future__ import annotations

from pathlib import Path
import subprocess

import pytest

from sase.amd._agents_doc import parse_amd_agents_document
from sase.amd._memory import _existing_agents_long_descriptions
from sase.amd.constants import PROVIDER_SHIM_FILES
from tests.main.init_memory_handler_helpers import (
    long_note,
    patch_standard_paths,
    plan_memory,
    prettier_command,
    run_handler,
    short_note,
    write,
)


def test_init_memory_overwrites_provider_shims(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(project_root / "AGENTS.md", "@sase/memory/sase.md\n")
    write(project_root / "CLAUDE.md", "old instructions\n")

    assert run_handler() == 0

    # Every provider file is overwritten with a byte-for-byte copy of AGENTS.md.
    agents = (project_root / "AGENTS.md").read_text()
    for filename in PROVIDER_SHIM_FILES:
        assert (project_root / filename).read_text() == agents


def test_init_memory_allows_transitive_memory_references(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "AGENTS.md",
        "@sase/memory/sase.md\n\nsase/memory/index.md\n",
    )
    write(
        project_root / "sase" / "memory" / "index.md",
        long_note("# Index\n\n@sase/memory/detail.md\n", description="Index."),
    )
    write(
        project_root / "sase" / "memory" / "detail.md",
        long_note("# Detail\n", description="Detail."),
    )

    assert run_handler() == 0


def test_init_memory_syncs_amd_agents_and_long_memory_descriptions(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        'is_sase_managed: true\nmemory:\n  h1_title: "Managed Instructions"\n',
    )
    write(
        project_root / "sase" / "memory" / "extra.md",
        short_note("# Extra\n\n## Section\n"),
    )
    write(
        project_root / "sase" / "memory" / "described.md",
        long_note(
            "# Described\n",
            description="Existing description.",
            extra_frontmatter="keywords:\n  - existing\nowner: docs",
        ),
    )
    write(
        project_root / "sase" / "memory" / "curated.md",
        long_note(
            "# Curated\n\nFallback body should not be used.\n",
            description=None,
        ),
    )
    write(
        project_root / "AGENTS.md",
        "# Previous\n\n"
        "**`sase/memory/curated.md`**  \n"
        "Curated description survives. _Read when touching curated memory._\n",
    )

    assert run_handler() == 0

    agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
    assert agents.startswith("# Managed Instructions\n")
    assert "## Tier 1 (short-term) Memory" in agents
    assert "The following memories contain core (always loaded) context:" in agents
    # Short memory is inlined (no ``@sase/memory/...`` imports) under H3 headers.
    assert "### 1. Extra (extra)" in agents
    assert "#### 1.1 Section" in agents
    assert "### 2. SASE = Structured Agentic Software Engineering (sase)" in agents
    assert "@sase/memory/extra.md" not in agents
    assert "@sase/memory/sase.md" not in agents
    assert "## Tier 2 (dynamic) Memory" not in agents
    assert "## Dynamic Memory Files" not in agents
    assert "### DYNAMIC MEMORY" not in agents
    assert "## Tier 2 (long-term) Memory" in agents
    assert "## Tier 3 (long-term) Memory" not in agents
    assert "#### Long-Term Memory Files" not in agents
    assert "**`sase/memory/curated.md`**  \nCurated description survives." in agents
    assert "**`sase/memory/described.md`**  \nExisting description." in agents
    assert ("sase-" + "amd:") not in agents

    curated = (project_root / "sase" / "memory" / "curated.md").read_text(
        encoding="utf-8"
    )
    assert curated.startswith(
        "---\n"
        "type: long\n"
        "parent: AGENTS.md\n"
        "description: Curated description survives.\n"
        "---\n"
    )
    described = (project_root / "sase" / "memory" / "described.md").read_text(
        encoding="utf-8"
    )
    assert "description: Existing description." in described
    assert "keywords:" not in described
    assert "owner: docs" in described

    # The inlined managed AGENTS.md must stay prettier-stable.
    agents_path = project_root / "AGENTS.md"
    assert agents_path.read_bytes().endswith(b"\n")
    result = subprocess.run(
        [
            *prettier_command(),
            "--check",
            str(agents_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"prettier --check failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )


def test_init_memory_managed_agents_wraps_long_memory_descriptions(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        'is_sase_managed: true\nmemory:\n  h1_title: "Managed Instructions"\n',
    )
    write(
        project_root / "sase" / "memory" / "generated_skills.md",
        long_note(
            "# Generated Skills\n",
            description=(
                "Read when working with sase agent skills (aka xprompt skills), "
                "which are generated from source templates in the "
                "`src/sase/xprompts/skills/` and deployed to managed locations "
                "(my chezmoi repo, for example)."
            ),
        ),
    )

    assert run_handler() == 0

    agents_path = project_root / "AGENTS.md"
    result = subprocess.run(
        [
            *prettier_command(),
            "--check",
            str(agents_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"prettier --check failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )

    plan = plan_memory()
    assert plan.blockers == ()
    assert plan.actions == ()


def test_init_memory_managed_agents_renders_block_long_memory_descriptions(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        'is_sase_managed: true\nmemory:\n  h1_title: "Managed Instructions"\n',
    )
    write(
        project_root / "sase" / "memory" / "block.md",
        "---\n"
        "type: long\n"
        "parent: AGENTS.md\n"
        "description: |-\n"
        "  Lead paragraph.\n"
        "\n"
        "  - One\n"
        "  - Two\n"
        "\n"
        "  Trailer.\n"
        "---\n"
        "# Block\n",
    )

    assert run_handler() == 0

    agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
    assert (
        "**`sase/memory/block.md`**  \nLead paragraph.\n\n- One\n- Two\n\nTrailer.\n"
    ) in agents
    parsed = parse_amd_agents_document(agents)
    block_entry = next(
        entry
        for entry in parsed.long_memory_entries
        if entry.path == "sase/memory/block.md"
    )
    assert block_entry.description == "Lead paragraph.\n\n- One\n- Two\n\nTrailer."
    assert plan_memory().actions == ()


def test_existing_agents_long_descriptions_preserves_legacy_block_descriptions(
    tmp_path: Path,
) -> None:
    root = tmp_path / "project"
    root.mkdir()
    write(
        root / "AGENTS.md",
        "# Legacy\n\n"
        "**`memory/block.md`**  \n"
        "Lead paragraph.\n"
        "\n"
        "- One\n"
        "\n"
        "Trailer. _Read when touching block memory._\n"
        "\n"
        "**`memory/next.md`**  \n"
        "Next description.\n",
    )

    assert _existing_agents_long_descriptions(root) == {
        "sase/memory/block.md": "Lead paragraph.\n\n- One\n\nTrailer.",
        "sase/memory/next.md": "Next description.",
    }


def test_init_memory_managed_agents_inline_short_memory_is_single_pass_idempotent(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        'is_sase_managed: true\nmemory:\n  h1_title: "Managed Instructions"\n',
    )
    write(
        project_root / "sase" / "memory" / "described.md",
        long_note("# Described\n", description="A long note."),
    )

    assert run_handler() == 0

    agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
    assert "### 1. SASE = Structured Agentic Software Engineering (sase)" in agents
    assert "@sase/memory/sase.md" not in agents

    # ``sase/memory/sase.md`` is regenerated every run, and its *fresh* body is the one
    # inlined into ``AGENTS.md``; a follow-up plan must therefore be a no-op.
    plan = plan_memory()
    assert plan.blockers == ()
    assert plan.actions == ()


def test_init_memory_rejects_short_memory_with_deep_heading(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        'is_sase_managed: true\nmemory:\n  h1_title: "Managed Instructions"\n',
    )
    # A short note with an H4 heading cannot be inlined and must block init.
    write(
        project_root / "sase" / "memory" / "bad.md",
        short_note("# Bad\n\n#### Too Deep\n"),
    )

    assert run_handler() == 1
    err = capsys.readouterr().err
    assert "sase/memory/bad.md" in err
    assert "deeper than H3" in err


def test_init_memory_rejects_missing_memory_parent(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(project_root / "AGENTS.md", "@sase/memory/sase.md\n")
    write(
        project_root / "sase" / "memory" / "orphan.md",
        "---\ntype: long\nparent: sase/memory/ghost.md\ndescription: Orphan.\n---\n"
        "# Orphan\n",
    )

    assert run_handler() == 1
    err = capsys.readouterr().err
    assert "invalid memory parent for sase/memory/orphan.md" in err
    assert "sase/memory/ghost.md" in err
    assert "parent target does not exist" in err
    assert "sase/memory/orphan.md" in err
