"""Tests for repository access guidance generated by ``sase memory init``."""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.main.init_memory_handler_helpers import (
    patch_standard_paths,
    run_handler,
    single_line,
    write,
)


def test_init_memory_legacy_workspace_config_uses_repo_open(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    static_one = tmp_path / "static-one"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    monkeypatch.setenv("STATIC_ONE", str(static_one))
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
linked_repos:
  - name: dotfiles
    path: $STATIC_ONE
    description: User dotfiles source.
    workspace:
      strategy: none
  - name: notes
    path: ../static-two
    description: Static notes checkout.
    workspace:
      strategy: none
""",
    )

    assert run_handler() == 0

    project_memory = (project_root / "sase" / "memory" / "sase.md").read_text()
    project_memory_line = single_line(project_memory)
    assert "Static-path linked repositories (`workspace.strategy: none`)" not in (
        project_memory
    )
    assert "- `dotfiles`: User dotfiles source." in project_memory_line
    assert "- `notes`: Static notes checkout." in project_memory_line
    assert "agents MUST use your `/sase_repo` skill first" in project_memory_line


def test_init_memory_mixed_linked_repos_render_repo_open(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
linked_repos:
  - name: core
    path: ../sase-core
    description: Numbered Rust core checkout.
  - name: dotfiles
    path: ../dotfiles
    description: Static dotfiles source.
    workspace:
      strategy: none
""",
    )

    assert run_handler() == 0

    project_memory = (project_root / "sase" / "memory" / "sase.md").read_text()
    project_memory_line = single_line(project_memory)
    assert "Static-path linked repositories (`workspace.strategy: none`)" not in (
        project_memory
    )
    assert "- `dotfiles`: Static dotfiles source." in project_memory_line
    assert "configured linked repos and sidecars" in project_memory_line
    assert "agents MUST use your `/sase_repo` skill first" in project_memory_line
    assert "Use the path it prints as the only path" in project_memory_line


def test_init_memory_legacy_relative_paths_use_repo_open(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    primary_root = tmp_path / "primary" / "project"
    project_root = tmp_path / "managed" / "project_10"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    numbered_relative_path = tmp_path / "managed" / "shared"
    primary_root.mkdir(parents=True)
    project_root.mkdir(parents=True)
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / ".sase" / "checkout.json",
        f"""
{{
  "project_key": "org/project",
  "project_name": "project",
  "workspace_num": 10,
  "primary_workspace_dir": "{primary_root}",
  "registry_path": "/work/registry.json",
  "schema_version": 1
}}
""",
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
linked_repos:
  - name: shared
    path: ../shared
    description: Static shared checkout.
    workspace:
      strategy: none
""",
    )

    assert run_handler() == 0

    project_memory = (project_root / "sase" / "memory" / "sase.md").read_text()
    assert "- `shared`: Static shared checkout." in single_line(project_memory)
    assert str((tmp_path / "primary" / "shared").resolve(strict=False)) not in (
        project_memory
    )
    assert str(numbered_relative_path.resolve(strict=False)) not in project_memory
    assert "agents MUST use your `/sase_repo` skill first" in single_line(
        project_memory
    )
