"""Tests for files and workspace guidance generated by ``sase memory init``."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest

from sase.main import init_memory_handler
from sase.main.init_memory.roots import read_memory_directory_map_bytes
from sase.memory.inventory import stats_for_text
from tests.main.init_memory_handler_helpers import (
    SASE_MEMORY_HEADER,
    long_note,
    patch_standard_paths,
    plan_memory,
    run_handler,
    single_line,
    short_note,
    write,
)


def test_init_memory_non_project_initializes_home_only_without_project_git(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    project_root = tmp_path / "not-project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
        project_is_vcs=False,
    )
    write(
        project_root / "sase.yml",
        """
is_sase_managed: true
linked_repos:
  - name: core
    path: ../sase-core
""",
    )
    git_run = MagicMock(return_value=MagicMock(returncode=0, stdout="", stderr=""))
    monkeypatch.setattr(init_memory_handler.subprocess, "run", git_run)

    assert run_handler(no_commit=False) == 0

    out = capsys.readouterr().out
    assert "project memory target" not in out
    assert "home memory target" in out
    assert not (project_root / "sase" / "memory").exists()
    assert not (project_root / "AGENTS.md").exists()
    assert (home_root / "sase" / "memory" / "sase.md").exists()
    assert (home_root / "AGENTS.md").exists()
    git_run.assert_not_called()


def test_init_memory_renders_data_driven_readme_and_asset(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    real_directory_map_assets: None,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    extra_note = short_note("# Extra\n\nAlways loaded.\n")
    reference_note = long_note(
        "# Reference\n\nDetailed reference.\n",
        description="Detailed reference note.",
    )
    write(project_root / "sase" / "memory" / "extra.md", extra_note)
    write(project_root / "sase" / "memory" / "reference.md", reference_note)

    assert run_handler() == 0

    readme = (project_root / "sase" / "memory" / "README.md").read_text(
        encoding="utf-8"
    )
    assert (
        "![How SASE memory files are used](assets/memory-directory-map.png)" in readme
    )
    assert "## How Memory Files Are Used" in readme
    assert "## Memory Notes" in readme
    assert "## Statistics" in readme
    assert "## Commands" in readme
    assert readme.index("### `sase/memory/extra.md`") < readme.index(
        "### `sase/memory/sase.md`"
    )
    assert readme.index("### `sase/memory/sase.md`") < readme.index(
        "### `sase/memory/sase_beads.md`"
    )
    assert readme.index("### `sase/memory/reference.md`") < readme.index(
        "### `sase/memory/sase_beads.md`"
    )
    assert readme.index("### `sase/memory/sase_beads.md`") < readme.index(
        "### `sase/memory/sase_sizes.md`"
    )
    assert "- Type: `short`" in readme
    assert "- Type: `long`" in readme
    assert "- Description: Detailed reference note." in readme
    assert "- Parent: `AGENTS.md`" in readme
    extra_stats = stats_for_text(
        (project_root / "sase" / "memory" / "extra.md").read_text(encoding="utf-8")
    )
    reference_stats = stats_for_text(
        (project_root / "sase" / "memory" / "reference.md").read_text(encoding="utf-8")
    )
    assert f"- Lines: {extra_stats.line_count}" in readme
    assert f"- Approx. tokens: {extra_stats.approx_token_count}" in readme
    assert f"- Lines: {reference_stats.line_count}" in readme
    assert f"- Approx. tokens: {reference_stats.approx_token_count}" in readme
    assert "- Total notes: 5" in readme
    assert "- Short notes: 2" in readme
    assert "- Long notes: 3" in readme

    asset_path = (
        project_root / "sase" / "memory" / "assets" / "memory-directory-map.png"
    )
    expected_asset = read_memory_directory_map_bytes()
    assert asset_path.read_bytes() == expected_asset
    assert run_handler(check=True) == 0

    asset_path.write_bytes(b"stale asset")
    plan = plan_memory()
    assert any(
        action.path == asset_path
        and action.operation == "update"
        and action.detail == "memory directory map asset"
        for action in plan.actions
    )
    assert run_handler() == 0
    assert asset_path.read_bytes() == expected_asset
    assert run_handler(check=True) == 0


def test_init_memory_project_memory_includes_workspace_section(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )

    assert run_handler() == 0

    project_memory = (project_root / "sase" / "memory" / "sase.md").read_text()
    home_memory = (home_root / "sase" / "memory" / "sase.md").read_text()
    assert SASE_MEMORY_HEADER in project_memory
    flat_project_memory = single_line(project_memory)
    assert "## Ephemeral `project_<N>` Workspace Directories" in project_memory
    assert "full clones of the project repo" in flat_project_memory
    assert "directories are named `project_<N>`" in flat_project_memory
    assert "project--research" not in project_memory
    assert "agents MUST use your `/sase_repo` skill first" in single_line(
        project_memory
    )
    assert "agents MUST use your `/sase_repo` skill first" in single_line(home_memory)
    assert "No linked repositories are configured for this context." in home_memory
    assert "{{ project }}" not in project_memory
    assert "Ephemeral" not in home_memory
    assert SASE_MEMORY_HEADER in home_memory
    assert "## Feature Flags" not in project_memory
    assert "## Feature Flags" not in home_memory

    plan_warning = (
        "IMPORTANT: Do NOT mention your workspace directory (or any sibling "
        "workspace directory) in any plan files that you generate using your "
        "`/sase_plan` skill. The agent(s) that implement the plan might not run "
        "in the same workspace directory as you!"
    )
    assert plan_warning in single_line(project_memory)
    assert "/sase_plan" not in home_memory


def test_init_memory_project_memory_uses_managed_checkout_marker_name(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_root = tmp_path / "project_10"
    home_root = tmp_path / "home"
    config_dir = tmp_path / "config"
    project_root.mkdir()
    home_root.mkdir()
    patch_standard_paths(
        monkeypatch,
        project_root=project_root,
        home_root=home_root,
        config_dir=config_dir,
    )
    write(
        project_root / ".sase" / "checkout.json",
        """
{
  "project_key": "org/project",
  "project_name": "project",
  "workspace_num": 10,
  "primary_workspace_dir": "/work/project",
  "registry_path": "/work/registry.json",
  "schema_version": 1
}
""",
    )

    assert run_handler() == 0

    project_memory = (project_root / "sase" / "memory" / "sase.md").read_text()
    assert "## Ephemeral `project_<N>` Workspace Directories" in project_memory
    assert "full clones of the project repo" in single_line(project_memory)
    assert "project_10_<N>" not in project_memory
