"""Durable background-task models, ids, logs, paths, and store facade."""

from .ids import TaskRefError, new_task_id, resolve_task_ref, short_task_id
from .logs import (
    append_task_log_text,
    delete_task_logs,
    open_task_log,
    read_task_log_tail,
    task_log_path,
)
from .models import (
    ACTIVE_TASK_STATUSES,
    COMMAND_TASK_KIND,
    DETACHED_TASK_KIND,
    TASK_KINDS,
    TASK_WIRE_SCHEMA_VERSION,
    TERMINAL_TASK_STATUSES,
    TUI_TASK_KIND,
    UNSET,
    BackgroundTask,
    TaskAppendOutcome,
    TaskPruneOutcome,
    TaskStoreSnapshot,
    TaskStoreStats,
    TaskUpdate,
    TaskUpdateOutcome,
)
from .paths import task_logs_dir, task_store_path, tasks_dir
from .runner import (
    TaskControlError,
    TaskSubmitError,
    kill_task,
    reconcile_running_tasks,
    submit_detached_task,
    submit_task,
    wait_for_task,
)
from .store import (
    TaskStoreLockTimeoutError,
    append_task,
    filter_tasks,
    get_task,
    prune_tasks,
    read_tasks,
    update_task,
)

__all__ = [
    "ACTIVE_TASK_STATUSES",
    "COMMAND_TASK_KIND",
    "DETACHED_TASK_KIND",
    "TASK_KINDS",
    "TASK_WIRE_SCHEMA_VERSION",
    "TERMINAL_TASK_STATUSES",
    "TUI_TASK_KIND",
    "UNSET",
    "BackgroundTask",
    "TaskAppendOutcome",
    "TaskControlError",
    "TaskPruneOutcome",
    "TaskRefError",
    "TaskStoreLockTimeoutError",
    "TaskStoreSnapshot",
    "TaskStoreStats",
    "TaskSubmitError",
    "TaskUpdate",
    "TaskUpdateOutcome",
    "append_task",
    "append_task_log_text",
    "delete_task_logs",
    "filter_tasks",
    "get_task",
    "kill_task",
    "new_task_id",
    "open_task_log",
    "prune_tasks",
    "read_task_log_tail",
    "read_tasks",
    "reconcile_running_tasks",
    "resolve_task_ref",
    "short_task_id",
    "submit_detached_task",
    "submit_task",
    "task_log_path",
    "task_logs_dir",
    "task_store_path",
    "tasks_dir",
    "update_task",
    "wait_for_task",
]
