"""Pinned string-literal pairs for the macro terminology guard.

Generated by the strings-guard phase (bead sase-1eq.4.1.5); do not hand-edit.
Each row is one surviving legacy string literal the guard must keep passing.
Reasons live per-file in tests._macro_terminology_strings._MACRO_SRC_STRING_REASONS.
"""

from __future__ import annotations

from tests._macro_terminology_string_pairs_b_early import (
    STRING_PAIRS as STRING_PAIRS_EARLY,
)
from tests._macro_terminology_string_pairs_b_late import (
    STRING_PAIRS as STRING_PAIRS_LATE,
)

STRING_PAIRS: set[tuple[str, str]] = STRING_PAIRS_EARLY | STRING_PAIRS_LATE
