"""Shared public helpers for the private macro terminology test modules."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TUI_SCOPES = (Path("src/sase/ace/tui"), Path("tests/ace"))
LEGACY_FIXTURE_MARK = "legacy_xprompt"
SELF_TESTS = frozenset(
    {
        Path("tests/test_macro_terminology.py"),
        Path("tests/_macro_terminology_common.py"),
        Path("tests/_macro_terminology_identifiers.py"),
        Path("tests/_macro_terminology_strings.py"),
        Path("tests/_macro_terminology_docs.py"),
    }
)

# Legacy homes and the temporary shim, each kept on purpose (the shim serves
# external plugins until audit-deploy). The syntax home joins when it lands.
MACRO_PATH_ALLOWLIST = {
    Path("src/sase/legacy_xprompt_names.py"),
    Path("src/sase/xprompt/__init__.py"),
}
if (ROOT / "src/sase/legacy_xprompt_syntax.py").exists():
    MACRO_PATH_ALLOWLIST.add(Path("src/sase/legacy_xprompt_syntax.py"))


def in_scope(path: Path) -> bool:
    relative = path.relative_to(ROOT)
    return not any(
        relative == scope or scope in relative.parents for scope in TUI_SCOPES
    )


def iter_scope_files(suffix: str | None = None) -> list[Path]:
    found: list[Path] = []
    for scope in (Path("src"), Path("tests")):
        root = ROOT / scope
        candidates = sorted(root.rglob(f"*{suffix}" if suffix else "*"))
        for path in candidates:
            if not path.is_file():
                continue
            if "__pycache__" in path.parts:
                # Generated bytecode mirrors source names; never source.
                continue
            if in_scope(path):
                found.append(path)
    return found


def literal_key(line: str) -> str:
    return line.strip()[:200]
