"""Justfile lint wiring contract.

Split into focused modules; this module re-exports every test so the
original import path keeps working.
"""

from __future__ import annotations

import pytest

from tests._justfile_lint_helpers import ROOT
from tests.test_justfile_lint_check import (
    test_check_and_check_full_recipes_exist,
    test_check_and_check_full_share_an_identical_gate_list,
    test_check_ends_in_the_scoped_test_lane,
    test_check_full_does_not_print_a_scoped_summary,
    test_check_full_ends_in_the_full_test_lane,
    test_check_full_runs_the_flake_baseline_gate_after_the_full_lane,
    test_check_lint_and_fix_do_not_run_screenshot_maintenance,
    test_check_mirrors_feature_flags_stage,
    test_check_prints_the_scoped_summary_after_run_silent_returns,
    test_ci_telemetry_runs_scheduled_measurement_lanes_off_full_ci,
    test_feature_flags_lint_recipe_uses_bead_handshake,
    test_legacy_pyvision_wiring_is_absent,
    test_lint_includes_feature_flags_stage,
    test_mypy_lint_recipe_runs_extensionless_tool_helper,
    test_refresh_contexts_baseline_recipe_runs_the_fetch_tool,
    test_retired_test_wait_lint_recipe_runs_the_tool,
    test_selection_backtest_is_not_a_check_gate,
    test_selection_backtest_recipe_runs_the_backtest_tool,
    test_selection_health_recipe_runs_the_reporting_tool,
    test_test_contexts_recipe_caches_the_recorded_baseline,
    test_test_scoped_runs_the_scoped_runner_mode,
    test_test_scoped_skips_the_visual_dependency_install,
    test_test_skips_the_visual_dependency_install,
    test_validate_runs_static_feature_flag_checks,
)
from tests.test_justfile_lint_lint import (
    test_check_and_check_full_skip_toobig_stage,
    test_check_mirrors_lint_symvision_stage,
    test_check_mirrors_retired_test_wait_stage,
    test_check_retains_sase_validation_stage,
    test_ci_lint_job_derives_sdd_sidecars_from_config,
    test_ci_lint_job_retains_sase_validation_stage,
    test_fix_uses_formatter_venv_without_application_setup,
    test_formatter_recipes_honor_custom_format_venv_dir,
    test_lint_does_not_run_sase_validation,
    test_lint_includes_retired_test_wait_stage,
    test_lint_includes_symvision_stage,
    test_lint_includes_toobig_stage,
    test_private_symvision_stage_uses_published_cli,
    test_public_symvision_target_uses_private_lint_stage,
    test_public_toobig_target_uses_private_lint_stage,
)
from tests.test_justfile_lint_setup import (
    test_refresh_sase_core_checkout_fetches_when_stale_core_is_not_allowed,
    test_refresh_sase_core_checkout_skips_fetch_when_stale_core_is_allowed,
    test_rust_dev_install_disables_cargo_incremental_cache,
    test_rust_dev_install_isolates_cargo_build_dir_with_target,
    test_rust_dev_install_writes_the_core_source_stamp,
    test_rust_install_also_refreshes_the_macro_lsp_binary,
    test_rust_install_consults_sase_core_wheel_cache,
    test_rust_install_is_fatal_on_a_behind_status,
    test_rust_install_notes_other_nonzero_status_as_normal,
    test_rust_install_recipes_skip_refresh_helper_when_stale_core_is_allowed,
    test_rust_lsp_install_consults_sase_core_artifact_cache,
    test_rust_lsp_install_isolates_cargo_build_dir_with_target,
    test_rust_recipes_are_grouped_and_documented,
    test_rust_uv_tool_recipes_fail_when_prerequisites_are_missing,
    test_setup_is_fatal_on_the_core_version_behind_bit,
    test_setup_notes_the_core_version_ahead_bit_as_normal,
    test_setup_propagates_the_post_rebuild_bindings_check_exit_status,
)

pytestmark = pytest.mark.contract

__test__ = False

__all__ = [
    "ROOT",
    "test_check_and_check_full_recipes_exist",
    "test_check_and_check_full_share_an_identical_gate_list",
    "test_check_and_check_full_skip_toobig_stage",
    "test_check_ends_in_the_scoped_test_lane",
    "test_check_full_does_not_print_a_scoped_summary",
    "test_check_full_ends_in_the_full_test_lane",
    "test_check_full_runs_the_flake_baseline_gate_after_the_full_lane",
    "test_check_lint_and_fix_do_not_run_screenshot_maintenance",
    "test_check_mirrors_feature_flags_stage",
    "test_check_mirrors_lint_symvision_stage",
    "test_check_mirrors_retired_test_wait_stage",
    "test_check_prints_the_scoped_summary_after_run_silent_returns",
    "test_check_retains_sase_validation_stage",
    "test_ci_lint_job_derives_sdd_sidecars_from_config",
    "test_ci_lint_job_retains_sase_validation_stage",
    "test_ci_telemetry_runs_scheduled_measurement_lanes_off_full_ci",
    "test_feature_flags_lint_recipe_uses_bead_handshake",
    "test_fix_uses_formatter_venv_without_application_setup",
    "test_formatter_recipes_honor_custom_format_venv_dir",
    "test_legacy_pyvision_wiring_is_absent",
    "test_lint_does_not_run_sase_validation",
    "test_lint_includes_feature_flags_stage",
    "test_lint_includes_retired_test_wait_stage",
    "test_lint_includes_symvision_stage",
    "test_lint_includes_toobig_stage",
    "test_mypy_lint_recipe_runs_extensionless_tool_helper",
    "test_private_symvision_stage_uses_published_cli",
    "test_public_symvision_target_uses_private_lint_stage",
    "test_public_toobig_target_uses_private_lint_stage",
    "test_refresh_contexts_baseline_recipe_runs_the_fetch_tool",
    "test_refresh_sase_core_checkout_fetches_when_stale_core_is_not_allowed",
    "test_refresh_sase_core_checkout_skips_fetch_when_stale_core_is_allowed",
    "test_retired_test_wait_lint_recipe_runs_the_tool",
    "test_rust_dev_install_disables_cargo_incremental_cache",
    "test_rust_dev_install_isolates_cargo_build_dir_with_target",
    "test_rust_dev_install_writes_the_core_source_stamp",
    "test_rust_install_also_refreshes_the_macro_lsp_binary",
    "test_rust_install_consults_sase_core_wheel_cache",
    "test_rust_install_is_fatal_on_a_behind_status",
    "test_rust_install_notes_other_nonzero_status_as_normal",
    "test_rust_install_recipes_skip_refresh_helper_when_stale_core_is_allowed",
    "test_rust_lsp_install_consults_sase_core_artifact_cache",
    "test_rust_lsp_install_isolates_cargo_build_dir_with_target",
    "test_rust_recipes_are_grouped_and_documented",
    "test_rust_uv_tool_recipes_fail_when_prerequisites_are_missing",
    "test_selection_backtest_is_not_a_check_gate",
    "test_selection_backtest_recipe_runs_the_backtest_tool",
    "test_selection_health_recipe_runs_the_reporting_tool",
    "test_setup_is_fatal_on_the_core_version_behind_bit",
    "test_setup_notes_the_core_version_ahead_bit_as_normal",
    "test_setup_propagates_the_post_rebuild_bindings_check_exit_status",
    "test_test_contexts_recipe_caches_the_recorded_baseline",
    "test_test_scoped_runs_the_scoped_runner_mode",
    "test_test_scoped_skips_the_visual_dependency_install",
    "test_test_skips_the_visual_dependency_install",
    "test_validate_runs_static_feature_flag_checks",
]
