"""Tests for the command palette modal (Phase 2).

Split into focused modules; this module re-exports every test so the
original import path keeps working.
"""

from __future__ import annotations

from tests.test_command_palette_modal_display import (
    test_modal_empty_state_shown_when_no_match,
    test_modal_filtering_narrows_list,
    test_modal_filtering_resets_highlight_to_top,
    test_modal_focuses_input_on_mount,
    test_modal_renders_key_filter_hint,
    test_modal_renders_nonempty_applicable_list,
    test_modal_status_count_switches_to_filtered_form,
    test_modal_status_empty_filter_shows_zero_position,
    test_modal_title_includes_tab_badge,
)
from tests.test_command_palette_modal_filter import (
    test_build_count_text_filtered_plural,
    test_build_count_text_singular,
    test_build_count_text_unfiltered_plural,
    test_build_position_text_contains_fraction_and_accent_style,
    test_build_row_text_includes_key_label_and_category,
    test_filter_specs_bare_key_filter_returns_all_in_order,
    test_filter_specs_empty_query_returns_all_in_order,
    test_filter_specs_excludes_non_matches,
    test_filter_specs_is_stable_on_ties,
    test_filter_specs_key_filter_does_not_match_text_metadata,
    test_filter_specs_key_filter_matches_app_binding_alternatives,
    test_filter_specs_key_filter_matches_display_chord,
    test_filter_specs_key_filter_matches_raw_keys_and_chords,
    test_filter_specs_key_filter_prefix_is_case_insensitive,
    test_render_gauge_clamps_position_to_range,
    test_render_gauge_handles_single_and_empty_totals,
    test_render_gauge_top_middle_bottom,
    test_score_match_alias_substring,
    test_score_match_empty_query_is_truthy,
    test_score_match_label_outranks_key,
    test_score_match_prefix_outranks_substring,
    test_score_match_zero_when_no_match,
)
from tests.test_command_palette_modal_interaction import (
    test_modal_colon_on_empty_filter_hops_to_command_line,
    test_modal_ctrl_n_ctrl_p_navigate,
    test_modal_down_arrow_moves_highlight,
    test_modal_empty_state_names_command_line_fallback,
    test_modal_enter_after_filter_returns_filtered_top,
    test_modal_enter_returns_highlighted_id,
    test_modal_enter_with_no_results_offers_command_line_fallback,
    test_modal_escape_returns_none,
    test_modal_position_updates_after_navigation,
    test_modal_typing_q_does_not_cancel,
)

__test__ = False

__all__ = [
    "test_build_count_text_filtered_plural",
    "test_build_count_text_singular",
    "test_build_count_text_unfiltered_plural",
    "test_build_position_text_contains_fraction_and_accent_style",
    "test_build_row_text_includes_key_label_and_category",
    "test_filter_specs_bare_key_filter_returns_all_in_order",
    "test_filter_specs_empty_query_returns_all_in_order",
    "test_filter_specs_excludes_non_matches",
    "test_filter_specs_is_stable_on_ties",
    "test_filter_specs_key_filter_does_not_match_text_metadata",
    "test_filter_specs_key_filter_matches_app_binding_alternatives",
    "test_filter_specs_key_filter_matches_display_chord",
    "test_filter_specs_key_filter_matches_raw_keys_and_chords",
    "test_filter_specs_key_filter_prefix_is_case_insensitive",
    "test_modal_colon_on_empty_filter_hops_to_command_line",
    "test_modal_ctrl_n_ctrl_p_navigate",
    "test_modal_down_arrow_moves_highlight",
    "test_modal_empty_state_names_command_line_fallback",
    "test_modal_empty_state_shown_when_no_match",
    "test_modal_enter_after_filter_returns_filtered_top",
    "test_modal_enter_returns_highlighted_id",
    "test_modal_enter_with_no_results_offers_command_line_fallback",
    "test_modal_escape_returns_none",
    "test_modal_filtering_narrows_list",
    "test_modal_filtering_resets_highlight_to_top",
    "test_modal_focuses_input_on_mount",
    "test_modal_position_updates_after_navigation",
    "test_modal_renders_key_filter_hint",
    "test_modal_renders_nonempty_applicable_list",
    "test_modal_status_count_switches_to_filtered_form",
    "test_modal_status_empty_filter_shows_zero_position",
    "test_modal_title_includes_tab_badge",
    "test_modal_typing_q_does_not_cancel",
    "test_render_gauge_clamps_position_to_range",
    "test_render_gauge_handles_single_and_empty_totals",
    "test_render_gauge_top_middle_bottom",
    "test_score_match_alias_substring",
    "test_score_match_empty_query_is_truthy",
    "test_score_match_label_outranks_key",
    "test_score_match_prefix_outranks_substring",
    "test_score_match_zero_when_no_match",
]
