"""Tests for the Python project-tag backend (D2–D4).

Split into focused modules; this module re-exports every test so the
original import path keeps working.
"""

from __future__ import annotations

from tests.test_project_tags_catalog import (
    test_accent_index_matches_accent,
    test_build_catalog_keeps_a_real_home_spec,
    test_catalog_known_tags_are_sorted,
    test_catalog_peek_never_builds,
    test_catalog_targets_carry_d2_fields,
    test_catalog_wire_targets_match_core_shape,
    test_home_target_is_synthetic_before_its_spec_exists,
    test_tag_name_grammar,
)
from tests.test_project_tags_expansion import (
    test_canonicalize_expands_tags_before_the_hash_guard,
    test_effective_tags_resolve_before_extraction,
    test_expand_ignores_non_tags,
    test_expand_is_case_insensitive,
    test_expand_leaves_unknown_tags_verbatim,
    test_expand_rewrites_tag_to_canonical_key,
    test_find_project_tags_reports_anchored_spans,
    test_launch_toast_prefix_never_loads_catalog,
    test_project_tag_for_spellings,
    test_snapshot_effective_tags_never_load,
    test_validate_alt_branches_are_separate_units,
    test_validate_disabled_tag_errors,
    test_validate_segments_are_separate_units,
    test_validate_tag_plus_ref_errors,
    test_validate_two_targets_in_one_unit_errors,
    test_validate_unknown_anchored_suggests,
    test_validate_unknown_unanchored_is_plain_text,
)
from tests.test_project_tags_tagify import (
    test_known_project_tag_for_matches_key_name_and_alias,
    test_known_project_tag_for_rejects_unknown_names,
    test_tagify_flag_off_and_cold_catalog_keep_hash_form,
    test_tagify_keeps_refs_outside_tag_positions,
    test_tagify_leaves_fenced_refs_verbatim,
    test_tagify_matches_keys_names_and_aliases_case_insensitively,
    test_tagify_never_rewrites_non_project_refs,
    test_tagify_rewrites_matching_workflow_refs,
)
from tests.test_project_tags_trigger import (
    test_apply_selection_accepts_pr_ref_spelling,
    test_apply_selection_inserts_tag_at_leading_position,
    test_apply_selection_keeps_other_segments,
    test_apply_selection_replaces_existing_target_in_segment,
    test_apply_selection_replaces_mid_line_target_and_drops_extra,
    test_apply_selection_switches_projects,
    test_apply_selection_uses_leading_position_without_target,
    test_find_project_tag_trigger_at_d1_boundaries,
    test_find_project_tag_trigger_rejects_non_triggers,
    test_validate_with_catalog_allows_unanchored_unknown,
    test_validate_with_catalog_rejects_disabled,
    test_validate_with_catalog_rejects_two_targets,
    test_validate_with_catalog_rejects_unknown_anchored,
)

__test__ = False

__all__ = [
    "test_accent_index_matches_accent",
    "test_apply_selection_accepts_pr_ref_spelling",
    "test_apply_selection_inserts_tag_at_leading_position",
    "test_apply_selection_keeps_other_segments",
    "test_apply_selection_replaces_existing_target_in_segment",
    "test_apply_selection_replaces_mid_line_target_and_drops_extra",
    "test_apply_selection_switches_projects",
    "test_apply_selection_uses_leading_position_without_target",
    "test_build_catalog_keeps_a_real_home_spec",
    "test_canonicalize_expands_tags_before_the_hash_guard",
    "test_catalog_known_tags_are_sorted",
    "test_catalog_peek_never_builds",
    "test_catalog_targets_carry_d2_fields",
    "test_catalog_wire_targets_match_core_shape",
    "test_effective_tags_resolve_before_extraction",
    "test_expand_ignores_non_tags",
    "test_expand_is_case_insensitive",
    "test_expand_leaves_unknown_tags_verbatim",
    "test_expand_rewrites_tag_to_canonical_key",
    "test_find_project_tag_trigger_at_d1_boundaries",
    "test_find_project_tag_trigger_rejects_non_triggers",
    "test_find_project_tags_reports_anchored_spans",
    "test_home_target_is_synthetic_before_its_spec_exists",
    "test_known_project_tag_for_matches_key_name_and_alias",
    "test_known_project_tag_for_rejects_unknown_names",
    "test_launch_toast_prefix_never_loads_catalog",
    "test_project_tag_for_spellings",
    "test_snapshot_effective_tags_never_load",
    "test_tag_name_grammar",
    "test_tagify_flag_off_and_cold_catalog_keep_hash_form",
    "test_tagify_keeps_refs_outside_tag_positions",
    "test_tagify_leaves_fenced_refs_verbatim",
    "test_tagify_matches_keys_names_and_aliases_case_insensitively",
    "test_tagify_never_rewrites_non_project_refs",
    "test_tagify_rewrites_matching_workflow_refs",
    "test_validate_alt_branches_are_separate_units",
    "test_validate_disabled_tag_errors",
    "test_validate_segments_are_separate_units",
    "test_validate_tag_plus_ref_errors",
    "test_validate_two_targets_in_one_unit_errors",
    "test_validate_unknown_anchored_suggests",
    "test_validate_unknown_unanchored_is_plain_text",
    "test_validate_with_catalog_allows_unanchored_unknown",
    "test_validate_with_catalog_rejects_disabled",
    "test_validate_with_catalog_rejects_two_targets",
    "test_validate_with_catalog_rejects_unknown_anchored",
]
