"""Workspace provider plugin system.

Usage::

    from sase.workspace_provider import detect_workflow_type, get_change_label

    wf_type = detect_workflow_type(project_file)
    label = get_change_label(project_file)
"""

from ._hookspec import (
    ExternalRepoCloneResult,
    ResolvedRef,
    SddSidecarPreflight,
    SddSidecarPreflightStatus,
    SUBMITTED_CHECK_EXIT_CODE_CLOSED,
    VcsNamespaceEntry,
    VcsRefNamespaces,
    VcsRepoCandidates,
    VcsRepoEntry,
    WorkflowMetadata,
    WorkspaceHookSpec,
    hookimpl,
    hookspec,
)
from ._plugin_manager import WorkspacePluginManager
from .lookup import resolve_consistent_workspace_pair, resolve_workspace_num_for_dir
from .marker import (
    CheckoutMarker,
    find_marker_from_cwd,
    read_marker,
    write_marker,
)
from .ownership import (
    AccessKind,
    MutationOrigin,
    OperationContext,
    WorkspaceOwnershipError,
    authorize_store_mutation,
    leased_operational_context,
    normalize_workspace_num,
    primary_sidecar_sync_context,
    read_only_canonical_context,
    user_directed_context,
    writable_beads_dir,
    writable_checkout_dir,
    writable_kind_root,
    writable_plans_dir,
    writable_sidecar_root,
)
from .registry import (
    WorkspaceEntry,
    WorkspaceRegistry,
    load_or_init_registry,
    record_workspace,
    remove_workspace,
    save_registry,
)
from ._registry import (
    clone_external_repo,
    create_sdd_remote,
    detect_workflow_type,
    extract_change_identifier,
    format_commit_description,
    generate_reviewer_comments_script,
    generate_submitted_check_script,
    get_all_workflow_metadata,
    get_change_label,
    get_display_name,
    get_display_name_by_vcs,
    get_display_name_by_vcs_family,
    get_pre_allocated_env_prefix,
    get_sdd_storage_policy_by_vcs,
    get_embedded_vcs_tag_pattern,
    get_external_repo_schemes,
    get_ref_patterns,
    get_vcs_tag_pattern,
    get_workflow_names,
    get_workspace_directory,
    get_workspace_name,
    list_ref_namespaces,
    list_repo_candidates,
    materialize_sdd_store,
    peek_ref,
    preflight_sdd_sidecar,
    prepare_mail,
    reset_workflow_metadata_caches,
    resolve_ref,
    submit_patch,
    supports_reviewer_comments,
)

submit_patch = submit_patch

__all__ = [
    "AccessKind",
    "CheckoutMarker",
    "ExternalRepoCloneResult",
    "MutationOrigin",
    "OperationContext",
    "WorkspaceOwnershipError",
    "ResolvedRef",
    "SddSidecarPreflight",
    "SddSidecarPreflightStatus",
    "SUBMITTED_CHECK_EXIT_CODE_CLOSED",
    "VcsNamespaceEntry",
    "VcsRefNamespaces",
    "VcsRepoCandidates",
    "VcsRepoEntry",
    "WorkflowMetadata",
    "WorkspaceEntry",
    "WorkspaceHookSpec",
    "WorkspacePluginManager",
    "WorkspaceRegistry",
    "authorize_store_mutation",
    "clone_external_repo",
    "create_sdd_remote",
    "detect_workflow_type",
    "extract_change_identifier",
    "find_marker_from_cwd",
    "format_commit_description",
    "generate_reviewer_comments_script",
    "generate_submitted_check_script",
    "get_all_workflow_metadata",
    "get_change_label",
    "get_display_name",
    "get_display_name_by_vcs",
    "get_display_name_by_vcs_family",
    "get_embedded_vcs_tag_pattern",
    "get_external_repo_schemes",
    "get_pre_allocated_env_prefix",
    "get_sdd_storage_policy_by_vcs",
    "get_ref_patterns",
    "get_vcs_tag_pattern",
    "get_workflow_names",
    "get_workspace_directory",
    "get_workspace_name",
    "hookimpl",
    "hookspec",
    "list_ref_namespaces",
    "leased_operational_context",
    "list_repo_candidates",
    "load_or_init_registry",
    "materialize_sdd_store",
    "normalize_workspace_num",
    "peek_ref",
    "preflight_sdd_sidecar",
    "prepare_mail",
    "primary_sidecar_sync_context",
    "read_marker",
    "read_only_canonical_context",
    "record_workspace",
    "remove_workspace",
    "reset_workflow_metadata_caches",
    "resolve_consistent_workspace_pair",
    "resolve_ref",
    "resolve_workspace_num_for_dir",
    "save_registry",
    "submit_patch",
    "submit_patch",
    "supports_reviewer_comments",
    "user_directed_context",
    "writable_beads_dir",
    "writable_checkout_dir",
    "writable_kind_root",
    "writable_plans_dir",
    "writable_sidecar_root",
    "write_marker",
]
