def run_payload() -> dict[str, object]:
    return {
        "start_ts": 0,
        "end_ts": 7_200,
        "runtime_group_by": "agent",
        "bucket_seconds": 3_600,
        "totals": {
            "runs": 6,
            "completed": 3,
            "failed": 1,
            "other_terminal": 1,
            "in_progress": 1,
            "waiting": 0,
        },
        "outcomes": [
            {"name": "completed", "count": 3},
            {"name": "failed", "count": 1},
            {"name": "stopped", "count": 1},
        ],
        "retries": {"chains": 2, "attempts": 3, "kills": 1},
        "providers": [
            {
                "provider": "codex",
                "model": "gpt-5",
                "effort": "high",
                "runs": 4,
                "success_rate": 0.75,
                "mean_runtime_seconds": 200.0,
            },
            {
                "provider": "codex",
                "model": "gpt-5",
                "effort": "default",
                "runs": 1,
                "success_rate": 1.0,
                "mean_runtime_seconds": 50.0,
            },
            {
                "provider": "claude",
                "model": "opus",
                "effort": "xhigh",
                "runs": 1,
                "success_rate": 0.0,
                "mean_runtime_seconds": None,
            },
        ],
        "commits": {
            "total_commits": 7,
            "committing_agents": 3,
            "average_per_committing_agent": 7 / 3,
            "distribution": {"zero": 3, "one": 1, "two": 1, "three_plus": 1},
            "top_repos": [
                {"name": "sase", "count": 5},
                {"name": "core", "count": 2},
            ],
        },
        "plans": {
            "proposed": 4,
            "approved": 1,
            "rejected": 2,
            "pending": 1,
        },
        "questions": {"sessions": 1, "asking_agents": 1},
        "workspaces": [
            {"project": "sase", "workspace_num": 17, "runs": 4},
            {"project": "core", "workspace_num": 2, "runs": 2},
        ],
        "buckets": [
            {"start_ts": 0, "runs": 2},
            {"start_ts": 3_600, "runs": 4},
        ],
        "runtime_groups": [
            {
                "group": "alpha",
                "runs": 2,
                "total_seconds": 1_000.0,
                "mean_seconds": 500.0,
                "p50_seconds": 450.0,
                "p95_seconds": 700.0,
                "max_seconds": 750.0,
            },
            {
                "group": "beta",
                "runs": 1,
                "total_seconds": 500.0,
                "mean_seconds": 500.0,
                "p50_seconds": 500.0,
                "p95_seconds": 500.0,
                "max_seconds": 500.0,
            },
        ],
        "work": {
            "projects": [
                {
                    "project": "sase",
                    "runs": 4,
                    "completed": 3,
                    "failed": 1,
                    "other_terminal": 0,
                    "in_progress": 0,
                    "waiting": 0,
                    "success_rate": 0.75,
                    "commits": 5,
                    "distinct_changespecs": 2,
                    "unattributed_runs": 1,
                    "total_runtime_seconds": 1_200.0,
                    "last_run_ts": 7_000.0,
                },
                {
                    "project": "core",
                    "runs": 2,
                    "completed": 0,
                    "failed": 0,
                    "other_terminal": 1,
                    "in_progress": 1,
                    "waiting": 0,
                    "success_rate": 0.0,
                    "commits": 2,
                    "distinct_changespecs": 1,
                    "unattributed_runs": 0,
                    "total_runtime_seconds": 300.0,
                    "last_run_ts": 6_000.0,
                },
            ],
            "changespecs": [
                {
                    "project": "sase",
                    "name": "stats-view",
                    "status": "Ready",
                    "has_pr": True,
                    "runs": 2,
                    "distinct_agents": 2,
                    "commits": 3,
                    "total_runtime_seconds": 700.0,
                    "first_run_ts": 1_000.0,
                    "last_run_ts": 7_000.0,
                },
                {
                    "project": "core",
                    "name": "wire-work",
                    "status": "unknown",
                    "has_pr": False,
                    "runs": 2,
                    "distinct_agents": 1,
                    "commits": 2,
                    "total_runtime_seconds": 300.0,
                    "first_run_ts": 2_000.0,
                    "last_run_ts": 6_000.0,
                },
            ],
            "unattributed_runs": 1,
            "truncated_changespec_rows": 1,
            "malformed_spec_files_skipped": 2,
        },
        "runners": {
            "start_ts": 0.0,
            "end_ts": 7_200.0,
            "peak_runners": 3,
            "peak_seconds": 600.0,
            "average_runners": 1.25,
            "busy_seconds": 6_000.0,
            "busy_share": 6_000 / 7_200,
            "runner_seconds": 9_000.0,
            "distribution": [
                {"runners": 0, "seconds": 1_200.0, "share": 1_200 / 7_200},
                {"runners": 1, "seconds": 3_600.0, "share": 3_600 / 7_200},
                {"runners": 2, "seconds": 1_800.0, "share": 1_800 / 7_200},
                {"runners": 3, "seconds": 600.0, "share": 600 / 7_200},
            ],
            "trend": [
                {
                    "start_ts": 0.0,
                    "end_ts": 3_600.0,
                    "average_runners": 1.0,
                    "peak_runners": 2,
                    "busy_seconds": 3_000.0,
                    "runner_seconds": 3_600.0,
                },
                {
                    "start_ts": 3_600.0,
                    "end_ts": 7_200.0,
                    "average_runners": 1.5,
                    "peak_runners": 3,
                    "busy_seconds": 3_000.0,
                    "runner_seconds": 5_400.0,
                },
            ],
            "malformed_rows_skipped": 1,
            "invalid_intervals_skipped": 2,
        },
    }


def activity_payload() -> dict[str, object]:
    return {
        "skills": [
            {"name": "review", "count": 8, "distinct_agents": 3},
            {"name": "plan", "count": 4, "distinct_agents": 2},
        ],
        "memories": [
            {"name": "sase.md", "count": 5, "distinct_agents": 2},
        ],
        "plans": {
            "proposed": 3,
            "proposing_agents": 2,
            "tiers": [
                {"name": "epic", "count": 2},
                {"name": "tale", "count": 1},
            ],
            "approved": 2,
            "rejected": 1,
            "feedback": 0,
            "pending": 0,
            "phases_per_epic": [
                {"value": 2, "count": 1},
                {"value": 4, "count": 1},
            ],
            "mean_phases_per_epic": 3.0,
        },
        "questions": {
            "sessions": 2,
            "asking_agents": 2,
            "questions": 3,
            "questions_per_session": [
                {"value": 1, "count": 1},
                {"value": 2, "count": 1},
            ],
            "mean_questions_per_session": 1.5,
        },
        "coverage_start_ts": 1_000.0,
    }
