"""Core-owned ``%auto`` autonomy record adapter (``%auto`` E1)."""

from __future__ import annotations

from sase.autonomy.record import (
    COVERAGE_LINE,
    LEGACY_AUTONOMY_KEYS,
    apply_record_meta_patch,
    auto_applies,
    autonomy_inherit_record,
    decision_sentence,
    evaluate,
    legacy_projection,
    live_record,
    mutate_record,
    profiles_catalog,
    read_decision_log,
    read_record,
    record_meta_patch,
    record_only,
    refresh_record_from_legacy,
    resolve_selection,
    RETUNE_DROP_KEYS,
    RETUNE_TRIGGER_KEYS,
    retune_meta_record,
    selection_to_prompt_prefix,
    summarize_record,
    with_legacy_projection,
)

__all__ = [
    "COVERAGE_LINE",
    "LEGACY_AUTONOMY_KEYS",
    "apply_record_meta_patch",
    "auto_applies",
    "autonomy_inherit_record",
    "decision_sentence",
    "evaluate",
    "legacy_projection",
    "live_record",
    "mutate_record",
    "profiles_catalog",
    "read_decision_log",
    "read_record",
    "record_meta_patch",
    "record_only",
    "refresh_record_from_legacy",
    "resolve_selection",
    "RETUNE_DROP_KEYS",
    "RETUNE_TRIGGER_KEYS",
    "retune_meta_record",
    "selection_to_prompt_prefix",
    "summarize_record",
    "with_legacy_projection",
]
