"""Emit a bash ``complete -F`` script from a ``CompletionSpec``."""

from __future__ import annotations

import re
from collections.abc import Iterator

from sase.completion.kinds import RUN_PROMPT_SLOT, ValueKind
from sase.completion.model import CommandSpec, CompletionSpec

_SAFE_TOKEN = re.compile(r"[-_./A-Za-z0-9]+")

# Hand-written walker. Kinded slots call ``__sase_candidates``, which caches
# the fast path's output in a shell associative array keyed by kind so
# retyping the same word never re-forks ``sase``. ``complete -o default``
# covers path/dir and unknown value slots.
_BASH_PREAMBLE = """\
declare -gA __sase_candidates_cache
declare -gA __sase_candidates_stamp

# Resolves `sase` from PATH and skips ephemeral workspace venvs
# (`…/sase_<N>/.venv/bin/sase`), which vanish when the workspace is reaped.
__sase_run() {
  local -a dirs
  local dir cmd
  IFS=: read -r -a dirs <<< "${PATH}"
  for dir in "${dirs[@]}"; do
    cmd="${dir}/sase"
    if [[ -x ${cmd} && ${cmd} != */sase_[0-9]*/.venv/bin/sase ]]; then
      command "${cmd}" "$@"
      return
    fi
  done
  command sase "$@"
}

# Fetches candidates for kind $1 through the pre-argparse fast path,
# caching the full set (never the prefix -- that is what lets one cached
# fetch serve a whole word) for SASE_COMPLETION_CACHE_TTL seconds, then
# filters by the current word $2 with a prefix $3 via compgen. Bash cannot
# show descriptions, so only the value column survives.
__sase_candidates() {
  local kind=$1 cur=$2 prefix=$3
  local ttl=${SASE_COMPLETION_CACHE_TTL:-60}
  # `${arr[k]+x}` tests key presence rather than value, so a fetch at
  # SECONDS==0 is never mistaken for the unpopulated default.
  if [[ -z ${__sase_candidates_stamp[${kind}]+x} ]] ||
     (( SECONDS - __sase_candidates_stamp[${kind}] >= ttl )); then
    __sase_candidates_cache[${kind}]=$(__sase_run completion candidates "${kind}" 2>/dev/null)
    __sase_candidates_stamp[${kind}]=${SECONDS}
  fi
  local -a values=()
  local line
  while IFS= read -r line; do
    [[ -n ${line} ]] && values+=("${line%%$'\\t'*}")
  done <<< "${__sase_candidates_cache[${kind}]}"
  COMPREPLY=($(compgen -P "${prefix}" -W "${values[*]}" -- "${cur}"))
}

# `sase run`'s PROMPT positional: native filenames plus stored xprompt
# names, since `sase run` accepts either a free-form prompt or a `#name`
# xprompt reference. `#`, `%`, and `@` completion inside the prompt text
# itself is deferred.
__sase_run_prompt() {
  local cur=$1 prefix=$2
  __sase_candidates xprompt "${cur}" "${prefix}"
  local -a files
  files=($(compgen -f -- "${cur}"))
  COMPREPLY+=("${files[@]}")
}

_sase() {
  local cur prev words cword
  local assign_prefix path i seen_dd w
  COMPREPLY=()
  _sase_reply=

  if declare -F _init_completion >/dev/null 2>&1; then
    _init_completion -n = || return
  else
    words=("${COMP_WORDS[@]}")
    cword=${COMP_CWORD:-0}
    cur="${words[cword]-}"
    if (( cword > 0 )); then
      prev="${words[cword-1]-}"
    else
      prev=
    fi
  fi

  assign_prefix=
  if [[ ${cur} == --*=* ]]; then
    assign_prefix="${cur%%=*}="
    prev="${cur%%=*}"
    cur="${cur#*=}"
  fi

  path=/
  i=1
  seen_dd=0
  while (( i < cword )); do
    w="${words[i]-}"
    i=$((i + 1))
    if (( seen_dd )); then
      continue
    fi
    if [[ ${w} == -- ]]; then
      seen_dd=1
      continue
    fi
    if [[ ${w} == --*=* ]]; then
      continue
    fi
    if [[ ${w} == -* ]]; then
      _sase_optval "${path}" "${w}"
      if [[ -n ${_sase_reply} && i -lt cword ]]; then
        i=$((i + 1))
      fi
      continue
    fi
    _sase_child "${path}" "${w}"
    if [[ -n ${_sase_reply} ]]; then
      path=${_sase_reply}
    fi
  done

  if (( ! seen_dd )) && [[ -n ${prev} && ${prev} == -* && ${prev} != -- ]]; then
    _sase_optval "${path}" "${prev}"
    if [[ -n ${_sase_reply} ]]; then
      _sase_complete_value "${_sase_reply}" "${cur}" "${assign_prefix}"
      return
    fi
  fi

  if (( ! seen_dd )) && [[ ${cur} == -* ]]; then
    _sase_opts "${path}"
    COMPREPLY=($(compgen -W "${_sase_reply}" -- "${cur}"))
    return
  fi

  _sase_subs "${path}"
  if [[ -n ${_sase_reply} ]]; then
    COMPREPLY=($(compgen -W "${_sase_reply}" -- "${cur}"))
    return
  fi

  _sase_pos "${path}"
  if [[ -n ${_sase_reply} ]]; then
    _sase_complete_value "${_sase_reply}" "${cur}" "${assign_prefix}"
  fi
}

_sase_complete_value() {
  local spec=$1
  local value_cur=$2
  local prefix=$3
  case ${spec} in
    choices:*)
      COMPREPLY=($(compgen -P "${prefix}" -W "${spec#choices:}" -- "${value_cur}"))
      ;;
    kind:path|kind:dir|value)
      ;;
    kind:*)
      __sase_candidates "${spec#kind:}" "${value_cur}" "${prefix}"
      ;;
    run_prompt)
      __sase_run_prompt "${value_cur}" "${prefix}"
      ;;
  esac
}
"""


def emit_bash(spec: CompletionSpec) -> str:
    """Return a bash ``complete -F`` script for *spec*."""
    header = (
        f"# Generated by sase completion bash ({spec.prog} {spec.version}). "
        "Do not edit."
    )
    parts = [
        header,
        "",
        _BASH_PREAMBLE.strip(),
        "",
        _emit_tables(spec),
        "",
        f"complete -o default -F _sase {spec.prog}",
    ]
    return "\n".join(parts) + "\n"


def _emit_tables(spec: CompletionSpec) -> str:
    subs: list[tuple[str, str]] = []
    opts: list[tuple[str, str]] = []
    pos: list[tuple[str, str]] = []
    children: list[tuple[str, str]] = []
    optvals: list[tuple[str, str]] = []
    for command in _walk(spec.root):
        key = _path_key(command.path)
        offered = tuple(child.name for child in command.subcommands)
        if offered:
            subs.append((key, " ".join(offered)))
        flags = tuple(
            flag
            for option in command.options
            if not option.hidden
            for flag in option.strings
        )
        if flags:
            opts.append((key, " ".join(flags)))
        positional = _first_positional_spec(command)
        if positional:
            pos.append((key, positional))
        for child in command.subcommands:
            dest = _path_key(child.path)
            patterns = [f"{key}|{word}" for word in (child.name, *child.aliases)]
            children.append(("|".join(_sq(pattern) for pattern in patterns), dest))
        for option in command.options:
            if option.hidden or not option.takes_value:
                continue
            value = _value_spec(option.choices, option.kind)
            patterns = [f"{key}|{flag}" for flag in option.strings]
            optvals.append(("|".join(_sq(pattern) for pattern in patterns), value))
    return "\n\n".join(
        [
            _case_function("_sase_subs", '"$1"', subs),
            _case_function("_sase_opts", '"$1"', opts),
            _case_function("_sase_pos", '"$1"', pos),
            _case_function("_sase_child", '"$1|$2"', children, pattern_raw=True),
            _case_function("_sase_optval", '"$1|$2"', optvals, pattern_raw=True),
        ]
    )


def _case_function(
    name: str,
    subject: str,
    arms: list[tuple[str, str]],
    *,
    pattern_raw: bool = False,
) -> str:
    lines = [f"{name}() {{", "  _sase_reply=", f"  case {subject} in"]
    for pattern, value in arms:
        rendered = pattern if pattern_raw else _sq(pattern)
        lines.append(f"    {rendered}) _sase_reply={_sq(value)} ;;")
    lines.append("  esac")
    lines.append("}")
    return "\n".join(lines)


def _walk(command: CommandSpec) -> Iterator[CommandSpec]:
    yield command
    for child in command.subcommands:
        yield from _walk(child)


def _path_key(path: tuple[str, ...]) -> str:
    return "/" + "/".join(path) if path else "/"


def _first_positional_spec(command: CommandSpec) -> str:
    for positional in command.positionals:
        if positional.is_remainder:
            continue
        if (command.path, positional.dest) == RUN_PROMPT_SLOT:
            return "run_prompt"
        return _value_spec(positional.choices, positional.kind)
    return ""


def _value_spec(choices: tuple[str, ...] | None, kind: ValueKind | None) -> str:
    if choices is not None:
        return "choices:" + " ".join(choices)
    if kind is not None:
        return f"kind:{kind}"
    return "value"


def _sq(text: str) -> str:
    if _SAFE_TOKEN.fullmatch(text):
        return text
    return "'" + text.replace("'", "'\\''") + "'"


__all__ = ["emit_bash"]
