"""Emit a native compsys ``_arguments`` script from a ``CompletionSpec``."""

from __future__ import annotations

import re
from collections.abc import Iterator

from sase.completion.emit_zsh_preamble import zsh_preamble
from sase.completion.kinds import ValueKind
from sase.completion.model import (
    CommandSpec,
    CompletionSpec,
    OptionSpec,
    PositionalSpec,
)

_SAFE_TOKEN = re.compile(r"[-_./A-Za-z0-9]+")
_SAFE_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def emit_zsh(spec: CompletionSpec) -> str:
    """Return a ``#compdef`` compsys script for *spec*."""
    functions = [_emit_function(command) for command in _walk(spec.root)]
    header = (
        f"#compdef {spec.prog}\n"
        f"# Generated by sase completion zsh ({spec.prog} {spec.version}). "
        "Do not edit."
    )
    root_fn = _function_name(spec.root.path)
    parts = [header, "", zsh_preamble(), "", *functions, "", f'{root_fn} "$@"']
    return "\n".join(parts) + "\n"


def _walk(command: CommandSpec) -> Iterator[CommandSpec]:
    yield command
    for child in command.subcommands:
        yield from _walk(child)


def _function_name(path: tuple[str, ...]) -> str:
    if not path:
        return "_sase_root"
    return "_sase_" + "_".join(_encode_part(part) for part in path)


def _encode_part(part: str) -> str:
    encoded = part.replace("+", "plus").replace("-", "_")
    cleaned = "".join(
        char if char.isalnum() or char == "_" else "_" for char in encoded
    )
    return cleaned or "cmd"


def _emit_function(command: CommandSpec) -> str:
    name = _function_name(command.path)
    body = "\n".join(f"  {line}" for line in _function_body(command))
    return f"{name}() {{\n{body}\n}}"


def _function_body(command: CommandSpec) -> list[str]:
    if command.subcommands:
        return _emit_dispatch_body(command)
    return _emit_leaf_body(command)


def _emit_leaf_body(command: CommandSpec) -> list[str]:
    lines = [
        "local context state state_line",
        "typeset -A opt_args",
    ]
    specs = _argument_specs(command)
    lines.extend(_arguments_call(specs, assign_ret=False))
    return lines


def _emit_dispatch_body(command: CommandSpec) -> list[str]:
    lines = [
        "local context state state_line",
        "typeset -A opt_args",
        "integer ret=1",
    ]
    specs = [
        *_option_specs(command),
        "'1: :->cmds'",
        "'*::arg:->args'",
    ]
    lines.extend(_arguments_call(specs, assign_ret=True))
    lines.append("case $state in")
    lines.extend(_cmds_branch(command))
    lines.extend(_args_branch(command))
    lines.append("esac")
    lines.append("return ret")
    return lines


def _argument_specs(command: CommandSpec) -> list[str]:
    specs = _option_specs(command)
    specs.extend(_positional_specs(command))
    return specs


def _option_specs(command: CommandSpec) -> list[str]:
    return [
        _option_spec(command, option) for option in command.options if not option.hidden
    ]


def _arguments_call(specs: list[str], *, assign_ret: bool) -> list[str]:
    suffix = " && ret=0" if assign_ret else ""
    if not specs:
        return [f"_arguments -C -s -S{suffix}"]
    lines = ["_arguments -C -s -S \\"]
    last = len(specs) - 1
    for index, spec in enumerate(specs):
        end = suffix if index == last else " \\"
        lines.append(f"  {spec}{end}")
    return lines


def _cmds_branch(command: CommandSpec) -> list[str]:
    entries = [
        _describe_entry(child.name, child.summary) for child in command.subcommands
    ]
    label = _describe_label(command)
    lines = [
        "  (cmds)",
        "    local -a commands",
        "    commands=(",
    ]
    lines.extend(f"      {entry}" for entry in entries)
    lines.append("    )")
    lines.append(f"    _describe -t commands {label} commands && ret=0")
    alias_names = [alias for child in command.subcommands for alias in child.aliases]
    if alias_names:
        quoted = " ".join(_sq(alias) for alias in alias_names)
        lines.append("    if [[ -n $PREFIX ]]; then")
        lines.append(f"      local -a _sase_aliases=({quoted})")
        lines.append("      compadd -Q -- ${(M)_sase_aliases:#$PREFIX*} && ret=0")
        lines.append("    fi")
    lines.append("    ;;")
    return lines


def _args_branch(command: CommandSpec) -> list[str]:
    lines = ["  (args)", "    case $words[1] in"]
    for child in command.subcommands:
        pattern = "|".join((child.name, *child.aliases))
        target = _function_name(child.path)
        lines.append(f"      ({pattern}) {target} && ret=0 ;;")
    lines.append("    esac")
    lines.append("    ;;")
    return lines


def _describe_label(command: CommandSpec) -> str:
    words = ("sase", *command.path, "commands")
    return _sq(" ".join(words))


def _describe_entry(name: str, summary: str) -> str:
    escaped_name = _escape_describe_name(name)
    if not summary:
        return _sq(escaped_name)
    return _sq(f"{escaped_name}:{_escape_description(summary)}")


def _option_spec(command: CommandSpec, option: OptionSpec) -> str:
    body = _bracket_desc(option.summary) + _value_suffix(
        takes_value=option.takes_value,
        metavar=option.dest,
        choices=option.choices,
        kind=option.kind,
    )
    forms = option.strings
    if option.repeatable:
        if len(forms) == 1:
            return _sq(f"*{forms[0]}{body}")
        return f"'*'{_brace(forms)}{_quoted_body(body)}"
    exclusion = _exclusion_list(command, option)
    excl = f"({exclusion})" if exclusion else ""
    if len(forms) == 1:
        return _sq(f"{excl}{forms[0]}{body}")
    return f"{_sq(excl)}{_brace(forms)}{_quoted_body(body)}"


def _exclusion_list(command: CommandSpec, option: OptionSpec) -> str:
    strings = list(option.strings)
    seen = set(strings)
    mutex_dests: set[str] = set()
    for group in command.mutex_groups:
        if option.dest in group:
            mutex_dests.update(group)
    mutex_dests.discard(option.dest)
    by_dest = {item.dest: item for item in command.options if not item.hidden}
    extras: list[str] = []
    for dest in mutex_dests:
        sibling = by_dest.get(dest)
        if sibling is None:
            continue
        for flag in sibling.strings:
            if flag not in seen:
                extras.append(flag)
                seen.add(flag)
    extras.sort(key=lambda flag: (flag.startswith("--"), flag.lower()))
    return " ".join(strings + extras)


def _positional_specs(command: CommandSpec) -> list[str]:
    specs: list[str] = []
    index = 1
    for positional in command.positionals:
        specs.append(_positional_spec(positional, index))
        if positional.nargs in {None, 1, "?"}:
            index += 1
    return specs


def _positional_spec(positional: PositionalSpec, index: int) -> str:
    if positional.is_remainder:
        return _sq("*::command:_normal")
    suffix = _value_suffix(
        takes_value=True,
        metavar=positional.metavar,
        choices=positional.choices,
        kind=positional.kind,
    )
    # _value_suffix starts with ":metavar:…"; the leading colon is the
    # message/action separator `_arguments` wants after the nargs prefix.
    message_action = suffix[1:] if suffix.startswith(":") else suffix
    prefix = _nargs_prefix(positional.nargs, index)
    return _sq(f"{prefix}{message_action}")


def _nargs_prefix(nargs: str | int | None, index: int) -> str:
    if nargs in {"*", "..."}:
        return "*::"
    if nargs == "+":
        return "*:"
    if nargs == "?":
        return f"{index}::"
    return f"{index}:"


def _value_suffix(
    *,
    takes_value: bool,
    metavar: str,
    choices: tuple[str, ...] | None,
    kind: ValueKind | None,
) -> str:
    if not takes_value:
        return ""
    name = _escape_description(metavar or "value")
    if choices is not None:
        joined = " ".join(_choice_word(choice) for choice in choices)
        return f":{name}:({joined})"
    if kind is ValueKind.PATH:
        return f":{name}:_files"
    if kind is ValueKind.DIR:
        return f":{name}:_files -/"
    if kind is not None:
        return f":{name}:->{kind}"
    return f":{name}:"


def _choice_word(choice: str) -> str:
    if _SAFE_TOKEN.fullmatch(choice):
        return choice
    return (
        choice.replace("\\", "\\\\")
        .replace(":", r"\:")
        .replace("(", r"\(")
        .replace(")", r"\)")
        .replace("[", r"\[")
        .replace("]", r"\]")
        .replace(" ", r"\ ")
    )


def _brace(forms: tuple[str, ...]) -> str:
    return "{" + ",".join(forms) + "}"


def _bracket_desc(summary: str) -> str:
    if not summary:
        return ""
    return f"[{_escape_description(summary)}]"


def _escape_describe_name(name: str) -> str:
    return name.replace("\\", "\\\\").replace(":", r"\:")


def _escape_description(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace("[", r"\[")
        .replace("]", r"\]")
        .replace(":", r"\:")
    )


def _quoted_body(body: str) -> str:
    if not body:
        return ""
    return _sq(body)


def _sq(text: str) -> str:
    if _SAFE_IDENT.fullmatch(text):
        return text
    return "'" + text.replace("'", r"'\''") + "'"


__all__ = ["emit_zsh"]
