"""Emit fish ``complete -c`` directives from a ``CompletionSpec``."""

from __future__ import annotations

from collections.abc import Iterator

from sase.completion.kinds import ValueKind
from sase.completion.model import (
    CommandSpec,
    CompletionSpec,
    OptionSpec,
    PositionalSpec,
)

_FISH_PREAMBLE = """\
# Resolves `sase` from PATH and skips ephemeral workspace venvs
# (`…/sase_<N>/.venv/bin/sase`), which vanish when the workspace is reaped.
function __sase_run
    for dir in $PATH
        set -l cmd $dir/sase
        if test -x $cmd
            if not string match -qr '/sase_[0-9]+/\\.venv/bin/sase$' $cmd
                command $cmd $argv
                return
            end
        end
    end
    command sase $argv
end

# Fetches candidates for kind $argv[1] through the pre-argparse fast path.
# `(...)` command substitutions fork, so state set here never survives to
# the next keystroke -- unlike zsh and bash, fish relies entirely on the
# fast path's own disk cache (candidates/cache.py) to absorb repeats, kept
# to a short TTL. The value/description output is fish's native format for
# a `-a` completion, so it is printed through unmodified.
function __sase_candidates
    __sase_run completion candidates $argv[1] 2>/dev/null
end

function __sase_cmd
    set -l current (__sase_path)
    test "$current" = "$argv[1]"
end

function __sase_path
    set -l tokens (commandline -opc)
    set -l path /
    set -l i 2
    set -l n (count $tokens)
    while test $i -le $n
        set -l w $tokens[$i]
        set i (math $i + 1)
        if test "$w" = --
            echo -n //remainder
            return
        end
        if string match -q -- '--*=*' $w
            continue
        end
        if string match -q -- '-*' $w
            if __sase_opt_takes_value "$path" "$w"
                if test $i -le $n
                    set i (math $i + 1)
                end
            end
            continue
        end
        set -l child (__sase_child "$path" "$w")
        if test -n "$child"
            set path $child
        end
    end
    echo -n "$path"
end
"""


def emit_fish(spec: CompletionSpec) -> str:
    """Return a fish ``complete -c`` script for *spec*."""
    header = (
        f"# Generated by sase completion fish ({spec.prog} {spec.version}). "
        "Do not edit."
    )
    parts = [
        header,
        "",
        _FISH_PREAMBLE.strip(),
        "",
        _emit_child_fn(spec),
        "",
        _emit_opt_takes_value_fn(spec),
        "",
        f"complete -c {spec.prog} -e",
        f"complete -c {spec.prog} -f",
        f"complete -c {spec.prog} -n '__sase_cmd //remainder' -F",
        *_emit_completes(spec),
    ]
    return "\n".join(parts) + "\n"


def _emit_child_fn(spec: CompletionSpec) -> str:
    arms: list[str] = []
    for command in _walk(spec.root):
        parent = _path_key(command.path)
        for child in command.subcommands:
            dest = _path_key(child.path)
            patterns = " ".join(
                _sq(f"{parent}|{word}") for word in (child.name, *child.aliases)
            )
            arms.append(f"        case {patterns}")
            arms.append(f"            echo -n {_sq(dest)}")
    body = "\n".join(arms) if arms else "        case '*'\n            true"
    return (
        f'function __sase_child\n    switch "$argv[1]|$argv[2]"\n{body}\n    end\nend'
    )


def _emit_opt_takes_value_fn(spec: CompletionSpec) -> str:
    patterns: list[str] = []
    for command in _walk(spec.root):
        key = _path_key(command.path)
        for option in command.options:
            if option.hidden or not option.takes_value:
                continue
            for flag in option.strings:
                patterns.append(_sq(f"{key}|{flag}"))
    case_line = " ".join(patterns) if patterns else "'*never*'"
    return (
        "function __sase_opt_takes_value\n"
        '    switch "$argv[1]|$argv[2]"\n'
        f"        case {case_line}\n"
        "            return 0\n"
        "        case '*'\n"
        "            return 1\n"
        "    end\n"
        "end"
    )


def _emit_completes(spec: CompletionSpec) -> list[str]:
    lines: list[str] = []
    for command in _walk(spec.root):
        parent = _path_key(command.path)
        for child in command.subcommands:
            lines.append(_command_complete(spec.prog, parent, child))
        for option in command.options:
            if option.hidden:
                continue
            lines.append(_option_complete(spec.prog, parent, option))
        for positional in command.positionals:
            if positional.is_remainder:
                continue
            emitted = _positional_complete(spec.prog, parent, positional)
            if emitted:
                lines.append(emitted)
    return lines


def _command_complete(prog: str, parent: str, child: CommandSpec) -> str:
    parts = [
        f"complete -c {prog}",
        f"-n '__sase_cmd {parent}'",
        f"-a {_sq(child.name)}",
    ]
    if child.summary:
        parts.append(f"-d {_sq(child.summary)}")
    return " ".join(parts)


def _option_complete(prog: str, parent: str, option: OptionSpec) -> str:
    parts = [f"complete -c {prog}", f"-n '__sase_cmd {parent}'"]
    parts.extend(_flag_args(option))
    if option.takes_value:
        parts.append(_value_args(option.choices, option.kind))
    if option.summary:
        parts.append(f"-d {_sq(option.summary)}")
    return " ".join(parts)


def _positional_complete(prog: str, parent: str, positional: PositionalSpec) -> str:
    args = _value_args(positional.choices, positional.kind)
    if not args:
        return ""
    parts = [f"complete -c {prog}", f"-n '__sase_cmd {parent}'", args]
    if positional.summary:
        parts.append(f"-d {_sq(positional.summary)}")
    return " ".join(parts)


def _flag_args(option: OptionSpec) -> list[str]:
    parts: list[str] = []
    for flag in option.strings:
        if flag.startswith("--"):
            parts.append(f"-l {_sq(flag[2:])}")
        elif flag.startswith("-") and len(flag) == 2:
            parts.append(f"-s {_sq(flag[1:])}")
        elif flag.startswith("-"):
            parts.append(f"-o {_sq(flag[1:])}")
    return parts


def _value_args(choices: tuple[str, ...] | None, kind: ValueKind | None) -> str:
    if choices is not None:
        return f"-xa {_sq(' '.join(choices))}"
    if kind is ValueKind.PATH:
        return "-rF"
    if kind is ValueKind.DIR:
        return "-ra '(__fish_complete_directories)'"
    if kind is not None:
        return f"-xa '(__sase_candidates {kind})'"
    return "-rF"


def _walk(command: CommandSpec) -> Iterator[CommandSpec]:
    yield command
    for child in command.subcommands:
        yield from _walk(child)


def _path_key(path: tuple[str, ...]) -> str:
    return "/" + "/".join(path) if path else "/"


def _sq(text: str) -> str:
    return "'" + text.replace("'", "'\\''") + "'"


__all__ = ["emit_fish"]
