"""Render portable shell-completion loader scripts."""

from __future__ import annotations

from sase.completion.install_targets import SUPPORTED_SHELLS


def emit_loader(shell: str, *, owner: str | None = None) -> str:
    """Return a small loader that sources runtime-cached grammar for *shell*."""
    if shell not in SUPPORTED_SHELLS:
        raise ValueError(f"unsupported shell: {shell}")
    if owner is not None and owner not in {"local", "chezmoi"}:
        raise ValueError(f"unsupported completion owner: {owner}")
    if shell == "bash":
        return _bash_loader(owner=owner)
    if shell == "fish":
        return _fish_loader(owner=owner)
    return _zsh_loader(owner=owner)


def _bash_loader(*, owner: str | None) -> str:
    owner_args = _owner_args_bash(owner)
    return f"""\
# Generated by sase completion loader bash. Do not edit.

__sase_loader_run() {{
  local -a dirs
  local dir cmd
  IFS=: read -r -a dirs <<< "${{PATH}}"
  for dir in "${{dirs[@]}}"; do
    cmd="${{dir}}/sase"
    if [[ -x "${{cmd}}" && "${{cmd}}" != */sase_[0-9]*/.venv/bin/sase ]]; then
      command "${{cmd}}" "$@"
      return $?
    fi
  done
  command sase "$@"
}}

__sase_loader_source() {{
  [[ -n ${{__SASE_COMPLETION_LOADER_ACTIVE:-}} ]] && return 1
  local __SASE_COMPLETION_LOADER_ACTIVE=1
  local loader="${{BASH_SOURCE[0]:-${{0}}}}"
  local grammar
  grammar="$(__sase_loader_run completion ensure bash --loader-path "${{loader}}" {owner_args}2>/dev/null)" || return 1
  [[ -n "${{grammar}}" && -r "${{grammar}}" ]] || return 1
  # shellcheck source=/dev/null
  source "${{grammar}}"
}}

if __sase_loader_source; then
  if [[ ${{COMP_WORDS[0]-}} == sase ]] && declare -F _sase >/dev/null 2>&1; then
    _sase
  fi
fi
unset -f __sase_loader_source __sase_loader_run 2>/dev/null || true
"""


def _fish_loader(*, owner: str | None) -> str:
    owner_args = _owner_args_fish(owner)
    return f"""\
# Generated by sase completion loader fish. Do not edit.

function __sase_loader_run
    for dir in $PATH
        set -l cmd "$dir/sase"
        if test -x "$cmd"
            if not string match -qr '/sase_[0-9]+/\\.venv/bin/sase$' -- "$cmd"
                command "$cmd" $argv
                return $status
            end
        end
    end
    command sase $argv
end

if not set -q __SASE_COMPLETION_LOADER_ACTIVE; and not set -q __SASE_COMPLETION_LOADER_SOURCED
    set -g __SASE_COMPLETION_LOADER_ACTIVE 1
    set -l loader (status filename)
    set -l grammar (__sase_loader_run completion ensure fish --loader-path "$loader" {owner_args}2>/dev/null)
    if test -n "$grammar"; and test -r "$grammar"
        if source "$grammar"
            set -gx __SASE_COMPLETION_LOADER_SOURCED 1
        end
    end
    set -e __SASE_COMPLETION_LOADER_ACTIVE
end

functions -e __sase_loader_run
"""


def _zsh_loader(*, owner: str | None) -> str:
    owner_args = _owner_args_zsh(owner)
    return f"""\
#compdef sase
# Generated by sase completion loader zsh. Do not edit.

__sase_loader_run() {{
  emulate -L zsh
  local -a found
  local cmd
  found=( ${{(f)"$(whence -p -a sase 2>/dev/null)"}} )
  for cmd in $found; do
    if [[ ! "$cmd" =~ '/sase_[0-9]+/\\.venv/bin/sase$' ]]; then
      command "$cmd" "$@"
      return $?
    fi
  done
  command sase "$@"
}}

if [[ -z ${{__SASE_COMPLETION_LOADER_ACTIVE:-}} ]]; then
  local __SASE_COMPLETION_LOADER_ACTIVE=1
  local loader=${{funcfiletrace[1]%%:*}}
  [[ -n $loader ]] || loader=${{(%):-%N}}
  local grammar
  grammar="$(__sase_loader_run completion ensure zsh --loader-path "$loader" {owner_args}2>/dev/null)" || return 1
  if [[ -n "$grammar" && -r "$grammar" ]]; then
    # Source the grammar path. zsh loads an adjacent newer .zwc automatically;
    # sourcing the bytecode file itself is parsed as a script and fails.
    source "$grammar"
    local loader_rc=$?
    unfunction __sase_loader_run 2>/dev/null || true
    _sase() {{ _sase_root "$@"; }}
    return $loader_rc
  fi
fi
unfunction __sase_loader_run 2>/dev/null || true
"""


def _owner_args_bash(owner: str | None) -> str:
    return "" if owner is None else f"--owner {_sh(owner)} "


def _owner_args_fish(owner: str | None) -> str:
    return "" if owner is None else f"--owner {_fish_sq(owner)} "


def _owner_args_zsh(owner: str | None) -> str:
    return "" if owner is None else f"--owner {_sh(owner)} "


def _sh(text: str) -> str:
    return "'" + text.replace("'", "'\\''") + "'"


def _fish_sq(text: str) -> str:
    return "'" + text.replace("'", "'\\''") + "'"


__all__ = ["emit_loader"]
