"""Compatibility re-exports for shared Artifacts tab constants."""

from ...artifact_tabs import (
    ARTIFACTS_ACCENTS,
    ARTIFACTS_PANE_IDS,
    ARTIFACTS_SUBTAB_ORDER,
    FIXED_ARTIFACTS_PANE_IDS,
    FIXED_ARTIFACTS_SUBTAB_ORDER,
    FILES_PANE_IDS,
    FILES_SUBTAB_ORDER,
    ArtifactsPaneKey,
    ArtifactsTabDescriptor,
    DEFAULT_ARTIFACTS_SUBTAB,
    DEFAULT_FILES_SUBTAB,
    DocumentProviderProjectRoot,
    EXTERNAL_ACCENT,
    ArtifactsSubTab,
    FilesSubTab,
    artifacts_pane_key,
    artifacts_subtab_order,
    descriptor_for_artifacts_subtab,
    document_provider_roots,
    normalize_artifacts_subtab,
    reset_artifacts_subtabs_cache,
    resolve_artifacts_subtabs,
)

__all__ = [
    "ARTIFACTS_ACCENTS",
    "ARTIFACTS_PANE_IDS",
    "ARTIFACTS_SUBTAB_ORDER",
    "FIXED_ARTIFACTS_PANE_IDS",
    "FIXED_ARTIFACTS_SUBTAB_ORDER",
    "FILES_PANE_IDS",
    "FILES_SUBTAB_ORDER",
    "ArtifactsPaneKey",
    "ArtifactsSubTab",
    "ArtifactsTabDescriptor",
    "DEFAULT_ARTIFACTS_SUBTAB",
    "DEFAULT_FILES_SUBTAB",
    "DocumentProviderProjectRoot",
    "EXTERNAL_ACCENT",
    "FilesSubTab",
    "artifacts_pane_key",
    "artifacts_subtab_order",
    "descriptor_for_artifacts_subtab",
    "document_provider_roots",
    "normalize_artifacts_subtab",
    "reset_artifacts_subtabs_cache",
    "resolve_artifacts_subtabs",
]
