"""Local SASE daemon client helpers."""

from sase.daemon.client import (
    LOCAL_DAEMON_MAX_PAYLOAD_BYTES,
    LOCAL_DAEMON_SCHEMA_VERSION,
    LocalDaemonClient,
    LocalDaemonError,
    LocalDaemonRpcError,
    LocalDaemonTransport,
    LocalDaemonTransportError,
    LocalDaemonUnavailableError,
    default_socket_path,
    daemon_disabled,
    diff,
    health,
    read,
    rebuild,
    verify,
)
from sase.daemon.read_facade import (
    DaemonReadResult,
    is_fallbackable_daemon_error,
    read_or_fallback,
)
from sase.daemon.read_models import (
    PROJECTION_READ_SCHEMA_VERSION,
    BeadDetailRead,
    BeadListRead,
    GenericDaemonRead,
    NotificationDetailRead,
    NotificationListRead,
    ProjectionPage,
    ProjectionPayloadBound,
    ProjectionSnapshot,
    bead_detail_from_dict,
    bead_list_from_dict,
    generic_read_from_dict,
    notification_detail_from_dict,
    notification_list_from_dict,
)

__all__ = [
    "LOCAL_DAEMON_MAX_PAYLOAD_BYTES",
    "LOCAL_DAEMON_SCHEMA_VERSION",
    "LocalDaemonClient",
    "LocalDaemonError",
    "LocalDaemonRpcError",
    "LocalDaemonTransport",
    "LocalDaemonTransportError",
    "LocalDaemonUnavailableError",
    "DaemonReadResult",
    "PROJECTION_READ_SCHEMA_VERSION",
    "BeadDetailRead",
    "BeadListRead",
    "GenericDaemonRead",
    "NotificationDetailRead",
    "NotificationListRead",
    "ProjectionPage",
    "ProjectionPayloadBound",
    "ProjectionSnapshot",
    "bead_detail_from_dict",
    "bead_list_from_dict",
    "default_socket_path",
    "daemon_disabled",
    "diff",
    "generic_read_from_dict",
    "health",
    "is_fallbackable_daemon_error",
    "notification_detail_from_dict",
    "notification_list_from_dict",
    "read",
    "read_or_fallback",
    "rebuild",
    "verify",
]
