"""Constants for the local SASE daemon RPC protocol."""

from __future__ import annotations

LOCAL_DAEMON_MIN_SUPPORTED_SCHEMA_VERSION = 1
LOCAL_DAEMON_MAX_SUPPORTED_SCHEMA_VERSION = 1
LOCAL_DAEMON_SCHEMA_VERSION = LOCAL_DAEMON_MAX_SUPPORTED_SCHEMA_VERSION
LOCAL_DAEMON_CLIENT_METADATA_SCHEMA_VERSION = 1
LOCAL_DAEMON_EXPECTED_PROJECTION_READ_SCHEMA_VERSION = 1
LOCAL_DAEMON_EXPECTED_PROJECTION_WRITE_SCHEMA_VERSION = 1
LOCAL_DAEMON_MAX_PAYLOAD_BYTES = 1_048_576
LOCAL_DAEMON_DEFAULT_PAGE_LIMIT = 100
