"""Durable proc models, ids, logs, paths, and store facade."""

from .ids import ProcRefError, new_proc_id, resolve_proc_ref, short_proc_id
from .logs import (
    append_proc_log_text,
    delete_proc_logs,
    open_proc_log,
    proc_log_path,
    read_proc_log_tail,
)
from .models import (
    ACTIVE_PROC_STATUSES,
    COMMAND_PROC_KIND,
    DETACHED_PROC_KIND,
    PROC_KINDS,
    PROC_WIRE_SCHEMA_VERSION,
    TERMINAL_PROC_STATUSES,
    TUI_PROC_KIND,
    UNSET,
    Proc,
    ProcAppendOutcome,
    ProcPruneOutcome,
    ProcStoreSnapshot,
    ProcStoreStats,
    ProcUpdate,
    ProcUpdateOutcome,
)
from .paths import proc_logs_dir, proc_store_path, procs_dir
from .runner import (
    ProcControlError,
    ProcSubmitError,
    kill_proc,
    reconcile_running_procs,
    submit_detached_proc,
    submit_proc,
    wait_for_proc,
)
from .store import (
    ProcStoreLockTimeoutError,
    append_proc,
    filter_procs,
    get_proc,
    prune_procs,
    read_procs,
    update_proc,
)

__all__ = [
    "ACTIVE_PROC_STATUSES",
    "COMMAND_PROC_KIND",
    "DETACHED_PROC_KIND",
    "PROC_KINDS",
    "PROC_WIRE_SCHEMA_VERSION",
    "TERMINAL_PROC_STATUSES",
    "TUI_PROC_KIND",
    "UNSET",
    "Proc",
    "ProcAppendOutcome",
    "ProcControlError",
    "ProcPruneOutcome",
    "ProcRefError",
    "ProcStoreLockTimeoutError",
    "ProcStoreSnapshot",
    "ProcStoreStats",
    "ProcSubmitError",
    "ProcUpdate",
    "ProcUpdateOutcome",
    "append_proc",
    "append_proc_log_text",
    "delete_proc_logs",
    "filter_procs",
    "get_proc",
    "kill_proc",
    "new_proc_id",
    "open_proc_log",
    "proc_log_path",
    "proc_logs_dir",
    "proc_store_path",
    "procs_dir",
    "prune_procs",
    "read_proc_log_tail",
    "read_procs",
    "reconcile_running_procs",
    "resolve_proc_ref",
    "short_proc_id",
    "submit_detached_proc",
    "submit_proc",
    "update_proc",
    "wait_for_proc",
]
