"""Presentation-neutral engine for ``sase agent wait``."""

from sase.agent.wait_watch._classify import classify_wait_target, classify_wait_targets
from sase.agent.wait_watch._resolve import (
    load_wait_caller_from_env,
    record_is_live,
    resolve_all_wait_targets,
    resolve_wait_targets,
    wait_scan_options,
)
from sase.agent.wait_watch._types import (
    WAIT_EXIT_BLOCKED,
    WAIT_EXIT_FAILED,
    WAIT_EXIT_INTERRUPTED,
    WAIT_EXIT_SUCCESS,
    WAIT_EXIT_TIMEOUT,
    WAIT_EXIT_USAGE,
    WaitCaller,
    WaitMemberState,
    WaitSettlement,
    WaitSettlementOutcome,
    WaitState,
    WaitTarget,
    WaitTargetKind,
    WaitTargetResolutionError,
    WaitTargetState,
    WaitTick,
    WaitWatchConfig,
    is_blocked_state,
    is_terminal_state,
)
from sase.agent.wait_watch._watch import (
    adaptive_poll_interval,
    settle_wait_tick,
    watch_wait_targets,
)

__all__ = [
    "WAIT_EXIT_BLOCKED",
    "WAIT_EXIT_FAILED",
    "WAIT_EXIT_INTERRUPTED",
    "WAIT_EXIT_SUCCESS",
    "WAIT_EXIT_TIMEOUT",
    "WAIT_EXIT_USAGE",
    "WaitCaller",
    "WaitMemberState",
    "WaitSettlement",
    "WaitSettlementOutcome",
    "WaitState",
    "WaitTarget",
    "WaitTargetKind",
    "WaitTargetResolutionError",
    "WaitTargetState",
    "WaitTick",
    "WaitWatchConfig",
    "adaptive_poll_interval",
    "classify_wait_target",
    "classify_wait_targets",
    "is_blocked_state",
    "is_terminal_state",
    "load_wait_caller_from_env",
    "record_is_live",
    "resolve_all_wait_targets",
    "resolve_wait_targets",
    "settle_wait_tick",
    "wait_scan_options",
    "watch_wait_targets",
]
