"""Image preview helpers for the ACE TUI."""

from .capability import ImageRenderContext, has_truecolor, image_render_context
from .cell import (
    CELL_IMAGE_BACKGROUND,
    MAX_CELL_IMAGE_FILE_BYTES,
    MAX_CELL_IMAGE_PIXELS,
    UPPER_HALF_BLOCK,
    CellImageRenderable,
    clear_cell_image_cache,
)
from .images import SUPPORTED_IMAGE_EXTENSIONS, is_supported_image_path
from .renderable import ImageFallbackRenderable, image_preview
from .sizing import image_preview_size_for_viewport
from .videos import SUPPORTED_VIDEO_EXTENSIONS, is_supported_video_path
from ._viewer_launch import (
    artifact_file_tmux_pane_exists,
    close_artifact_file_tmux_pane,
    decorate_artifact_file_tmux_panes,
    is_tmux_session,
    restore_artifact_file_tmux_pane_decoration,
    select_tmux_pane,
    TmuxPaneDecorationResult,
    TmuxPaneDecorationState,
    toggle_artifact_file_tmux_pane_zoom,
    view_registered_artifact_file,
    view_registered_artifact_file_in_tmux_pane,
    view_registered_artifact_files,
    view_registered_artifact_files_in_tmux_pane,
    view_artifact_file,
    view_artifact_file_in_tmux_pane,
    view_artifact_files,
    view_artifact_files_in_tmux_pane,
    view_image_file,
)
from ._viewer_loop import (
    ArtifactVideoPlaybackConfig,
    artifact_image_area,
    artifact_text_viewer_command,
    artifact_video_player_command,
    kitten_icat_command,
    load_artifact_video_playback_config,
    page_index_after_key,
    print_text_prompt,
    run_artifact_page_loop,
    run_artifact_sequence_loop,
    run_artifact_text_viewer,
)
from ._viewer_render import (
    artifact_markdown_pdf_profile_for_image_area,
    artifact_file_view_mode,
    convert_pdf_to_png_pages,
    render_artifact_file_pages,
    validate_artifact_file_viewer_dependencies,
)
from ._viewer_types import (
    ArtifactFileImageArea,
    ArtifactRenderResult,
    ArtifactFileViewSpec,
    ArtifactFileViewerResult,
    ArtifactFileViewerWarning,
    ImageViewerResult,
)

__all__ = [
    "CELL_IMAGE_BACKGROUND",
    "ImageFallbackRenderable",
    "ImageRenderContext",
    "ArtifactFileImageArea",
    "ArtifactRenderResult",
    "ArtifactFileViewSpec",
    "ArtifactFileViewerResult",
    "ArtifactFileViewerWarning",
    "ArtifactVideoPlaybackConfig",
    "ImageViewerResult",
    "artifact_image_area",
    "artifact_markdown_pdf_profile_for_image_area",
    "artifact_text_viewer_command",
    "artifact_file_tmux_pane_exists",
    "artifact_video_player_command",
    "MAX_CELL_IMAGE_FILE_BYTES",
    "MAX_CELL_IMAGE_PIXELS",
    "SUPPORTED_IMAGE_EXTENSIONS",
    "SUPPORTED_VIDEO_EXTENSIONS",
    "UPPER_HALF_BLOCK",
    "CellImageRenderable",
    "artifact_file_view_mode",
    "close_artifact_file_tmux_pane",
    "clear_cell_image_cache",
    "convert_pdf_to_png_pages",
    "decorate_artifact_file_tmux_panes",
    "has_truecolor",
    "image_preview",
    "image_preview_size_for_viewport",
    "image_render_context",
    "is_supported_image_path",
    "is_supported_video_path",
    "is_tmux_session",
    "kitten_icat_command",
    "load_artifact_video_playback_config",
    "page_index_after_key",
    "print_text_prompt",
    "render_artifact_file_pages",
    "restore_artifact_file_tmux_pane_decoration",
    "run_artifact_sequence_loop",
    "run_artifact_page_loop",
    "run_artifact_text_viewer",
    "select_tmux_pane",
    "toggle_artifact_file_tmux_pane_zoom",
    "TmuxPaneDecorationResult",
    "TmuxPaneDecorationState",
    "validate_artifact_file_viewer_dependencies",
    "view_registered_artifact_file",
    "view_registered_artifact_files",
    "view_registered_artifact_file_in_tmux_pane",
    "view_registered_artifact_files_in_tmux_pane",
    "view_artifact_file",
    "view_artifact_files",
    "view_artifact_file_in_tmux_pane",
    "view_artifact_files_in_tmux_pane",
    "view_image_file",
]
