"""Static copy targets for ACE artifact tabs."""

from __future__ import annotations

from ._copy_target_types import CopyTarget, build_copy_target


ARTIFACT_COPY_TARGETS: tuple[CopyTarget, ...] = (
    build_copy_target(
        "artifacts_stitches",
        "sha",
        "SHA",
        "Copy commit SHA",
        "Identity",
        "commit SHAs",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "reference",
        "@ref",
        "Copy artifact reference",
        "Identity",
        "artifact references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "link",
        "link",
        "Copy Markdown link",
        "Location",
        "Markdown links",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "message",
        "message",
        "Copy commit message",
        "Content",
        "commit messages",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "repo_sha",
        "repo@SHA",
        "Copy repo@SHA",
        "Identity",
        "repository commit references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "plan",
        "plan ref",
        "Copy linked plan reference",
        "Location",
        "linked plan references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "json",
        "JSON",
        "Copy metadata JSON",
        "Data",
        "metadata JSON records",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "handoff",
        "agent + @ref",
        "Reference in new agent prompt",
        "Actions",
        "references in a new agent prompt",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_stitches",
        "snapshot",
        "snap",
        "Copy Artifacts snapshot",
        "Actions",
        "Artifacts snapshots",
    ),
    build_copy_target(
        "artifacts_plans",
        "bead_id",
        "bead id",
        "Copy owning bead id",
        "Identity",
        "owning bead ids",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "reference",
        "@ref",
        "Copy artifact reference",
        "Identity",
        "artifact references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "link",
        "link",
        "Copy Markdown link",
        "Location",
        "Markdown links",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "design",
        "design",
        "Copy design reference",
        "Location",
        "design references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "path",
        "path",
        "Copy plan path",
        "Location",
        "plan paths",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "title",
        "title",
        "Copy plan title",
        "Identity",
        "plan titles",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "body",
        "body",
        "Copy plan body",
        "Content",
        "plan bodies",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "json",
        "JSON",
        "Copy metadata JSON",
        "Data",
        "metadata JSON records",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "handoff",
        "agent + @ref",
        "Reference in new agent prompt",
        "Actions",
        "references in a new agent prompt",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_plans",
        "snapshot",
        "snap",
        "Copy Artifacts snapshot",
        "Actions",
        "Artifacts snapshots",
    ),
    build_copy_target(
        "artifacts_documents",
        "reference",
        "@ref",
        "Copy artifact reference",
        "Identity",
        "artifact references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_documents",
        "link",
        "link",
        "Copy Markdown link",
        "Location",
        "Markdown links",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_documents",
        "path",
        "path",
        "Copy document path",
        "Location",
        "document paths",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_documents",
        "title",
        "title",
        "Copy document title",
        "Identity",
        "document titles",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_documents",
        "body",
        "body",
        "Copy document body",
        "Content",
        "document bodies",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_documents",
        "json",
        "JSON",
        "Copy metadata JSON",
        "Data",
        "metadata JSON records",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_documents",
        "handoff",
        "agent + @ref",
        "Reference in new agent prompt",
        "Actions",
        "references in a new agent prompt",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_documents",
        "snapshot",
        "snap",
        "Copy Artifacts snapshot",
        "Actions",
        "Artifacts snapshots",
    ),
    build_copy_target(
        "artifacts_beads",
        "id",
        "id",
        "Copy bead id",
        "Identity",
        "bead ids",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "reference",
        "@ref",
        "Copy artifact reference",
        "Identity",
        "artifact references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "link",
        "link",
        "Copy Markdown link",
        "Location",
        "Markdown links",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "title",
        "title",
        "Copy bead title",
        "Identity",
        "bead titles",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "body",
        "body",
        "Copy bead body",
        "Content",
        "bead bodies",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "design",
        "design",
        "Copy design reference",
        "Location",
        "design references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "json",
        "JSON",
        "Copy metadata JSON",
        "Data",
        "metadata JSON records",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "handoff",
        "agent + @ref",
        "Reference in new agent prompt",
        "Actions",
        "references in a new agent prompt",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_beads",
        "snapshot",
        "snap",
        "Copy Artifacts snapshot",
        "Actions",
        "Artifacts snapshots",
    ),
    build_copy_target(
        "artifacts_beads",
        "bug",
        "bug",
        "Copy linked issue reference",
        "Identity",
        "linked issue references",
    ),
    build_copy_target(
        "artifacts_other",
        "contents",
        "contents",
        "Copy artifact-file contents",
        "Content",
        "artifact-file contents",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "reference",
        "@ref",
        "Copy artifact reference",
        "Identity",
        "artifact references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "link",
        "link",
        "Copy Markdown link",
        "Location",
        "Markdown links",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "path",
        "path",
        "Copy stored path",
        "Location",
        "stored paths",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "source",
        "source",
        "Copy source path",
        "Location",
        "source paths",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "label",
        "label",
        "Copy artifact-file label",
        "Identity",
        "artifact-file labels",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "json",
        "JSON",
        "Copy metadata JSON",
        "Data",
        "metadata JSON records",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "handoff",
        "agent + @ref",
        "Reference in new agent prompt",
        "Actions",
        "references in a new agent prompt",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_other",
        "snapshot",
        "snap",
        "Copy Artifacts snapshot",
        "Actions",
        "Artifacts snapshots",
    ),
    build_copy_target(
        "artifacts_agents",
        "reference",
        "@ref",
        "Copy agent reference",
        "Identity",
        "agent references",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_agents",
        "name",
        "name",
        "Copy agent name",
        "Identity",
        "agent names",
    ),
    build_copy_target(
        "artifacts_agents",
        "link",
        "link",
        "Copy Markdown link",
        "Location",
        "Markdown links",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_agents",
        "path",
        "path",
        "Copy artifacts directory path",
        "Location",
        "artifacts directory paths",
    ),
    build_copy_target(
        "artifacts_agents",
        "chat",
        "chat",
        "Copy chat path",
        "Location",
        "chat paths",
    ),
    build_copy_target(
        "artifacts_agents",
        "prompt",
        "prompt",
        "Copy prompt",
        "Content",
        "prompts",
    ),
    build_copy_target(
        "artifacts_agents",
        "json",
        "JSON",
        "Copy metadata JSON",
        "Data",
        "metadata JSON records",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_agents",
        "handoff",
        "agent + @ref",
        "Reference in new agent prompt",
        "Actions",
        "references in a new agent prompt",
        accepts_marks=True,
    ),
    build_copy_target(
        "artifacts_agents",
        "snapshot",
        "snap",
        "Copy Artifacts snapshot",
        "Actions",
        "Artifacts snapshots",
    ),
)


__all__ = [
    "ARTIFACT_COPY_TARGETS",
]
