"""Proc-producer sites for ACE workflow and UI helpers."""

from __future__ import annotations

from sase.ace.tui._proc_producer_site import _ProcProducerSite, _site


WORKFLOW_PRODUCERS: tuple[_ProcProducerSite, ...] = (
    _site(
        "xprompt.commit",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_save_xprompt_git.py",
        "_submit_xprompt_commit_task",
        "duck_submit_durable",
        "GIT_POST_WRITE",
        "durable",
        "_submit_xprompt_commit_task",
        "sase stitch create",
        identifiers=("git_root", "rel_path"),
        result_kind="git.commit",
        concurrency_keys=("{noun}-commit:{git_root}:{rel_path}",),
    ),
    _site(
        "xprompt.post_write",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_save_xprompt_git.py",
        "_submit_post_write_action",
        "duck_submit_durable",
        "GIT_POST_WRITE",
        "durable",
        "_submit_post_write_action",
        "sase stitch create",
        identifiers=("rel_path",),
        result_kind="git.commit",
    ),
    _site(
        "config.commit",
        "src/sase/ace/tui/modals/config_commit.py",
        "submit_config_commit_task",
        "duck_submit_durable",
        "GIT_POST_WRITE",
        "durable",
        "submit_config_commit_task",
        "sase stitch create",
        identifiers=("git_root", "rel_path"),
        result_kind="git.commit",
        concurrency_keys=("config-commit:{git_root}:{rel_path}",),
    ),
    _site(
        "prompt.stash",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_stash.py",
        "_submit_prompt_stash_persist_task",
        "ui_worker",
        "prompt-stash",
        "ui_only",
        "_submit_prompt_stash_persist_task",
        "",
        identifiers=("entry_id",),
        result_kind="prompt.stash",
        restart_recovery="not a durable proc; session-local stash persist",
    ),
    _site(
        "commits.fetch",
        "src/sase/ace/tui/widgets/artifacts/commits_pane.py",
        "fetch_commits",
        "ui_worker",
        "commit-fetch",
        "ui_only",
        "CommitsPane.fetch_commits",
        "",
        identifiers=("scope",),
        result_kind="commit.fetch",
        restart_recovery="not durable; pane fetch is session-local",
    ),
    _site(
        "ace.ref_sync",
        "src/sase/ace/tui/widgets/_artifact_ref_sync.py",
        "_start_artifact_ref_sync",
        "session_worker",
        "ref-sync",
        "ui_only",
        "ArtifactRefSyncMixin._start_artifact_ref_sync",
        "",
        identifiers=("project", "kind"),
        result_kind="ref.sync",
        concurrency_keys=("ace:ref-sync:{project}:{kind}",),
        optimistic_ui="pinned sync row + spinner",
        restart_recovery="not durable; session-local refresh",
    ),
)
