"""Proc-producer sites for ACE domain actions."""

from __future__ import annotations

from sase.ace.tui._proc_producer_site import _ProcProducerSite, _site


ACTION_PRODUCERS: tuple[_ProcProducerSite, ...] = (
    _site(
        "patch.durable",
        "src/sase/ace/tui/actions/patch_durable.py",
        "submit_patch_operation",
        "direct_submit_durable",
        "dynamic",
        "durable",
        "submit_patch_operation",
        "sase patch",
        identifiers=("project_file", "name", "verb"),
        result_kind="patch.*",
        concurrency_keys=("ace:patch:{project}:{name}",),
        optimistic_ui="start toast; hook reset; optional mail on accept",
    ),
    _site(
        "axe.bgcmd",
        "src/sase/ace/tui/actions/axe_bgcmd.py",
        "_start_bgcmd",
        "direct_submit_durable",
        "AXE_BGCMD",
        "durable",
        "AxeBgCmdMixin",
        "sase run",
        identifiers=("slot", "project_file"),
        result_kind="axe.bgcmd",
        concurrency_keys=("axe-slot:{slot}",),
        optimistic_ui="mark slot pending",
    ),
    _site(
        "monitor.stop",
        "src/sase/ace/tui/actions/agents/_monitor_stop_flow.py",
        "_do_stop_monitor",
        "direct_submit_durable",
        "MONITOR_STOP",
        "durable",
        "MonitorStopActionFlowMixin._do_stop_monitor",
        "sase monitor stop",
        identifiers=("monitor_id",),
        result_kind="monitor.stop",
        concurrency_keys=("monitor:{id}",),
    ),
    _site(
        "agent.launch",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_launch",
        "direct_submit_durable",
        "launch",
        "durable",
        "submit_agent_launch",
        "sase run",
        identifiers=("workflow", "project_file"),
        result_kind="run.launch",
        concurrency_keys=("ace:launch:{workflow}",),
        optimistic_ui="launch-result delta; agent refresh",
    ),
    _site(
        "agent.cleanup",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_cleanup",
        "direct_submit_durable",
        "dynamic",
        "durable",
        "submit_agent_cleanup",
        "sase agent persist-cleanup",
        identifiers=("proc_type", "identity"),
        result_kind="agent.cleanup",
        concurrency_keys=("ace:cleanup:{proc_type}:{identity}",),
        optimistic_ui="agents refresh",
    ),
    _site(
        "agent.directive",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_directive",
        "direct_submit_durable",
        "agent-directive",
        "durable",
        "submit_agent_directive",
        "sase agent persist-directive",
        identifiers=("artifacts_dir",),
        result_kind="agent.persist-directive",
        concurrency_keys=("ace:agent-directive:{artifacts_dir}",),
        optimistic_ui="optimistic fields; guarded rollback",
    ),
    _site(
        "agent.revert.preview",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_revert_preview",
        "session_worker",
        "revert_preview",
        "ui_only",
        "AgentRevertMixin._submit_revert_preview",
        "",
        identifiers=("agent_name",),
        result_kind="agent.revert-preview",
        restart_recovery="not durable; preview is session-local",
    ),
    _site(
        "agent.revert.execute",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_revert",
        "direct_submit_durable",
        "revert_agent",
        "durable",
        "submit_agent_revert",
        "sase agent revert",
        identifiers=("agent_name",),
        result_kind="agent.revert",
        concurrency_keys=("ace:agent-revert:execute:{key}",),
    ),
    _site(
        "agent.revert.bulk_preview",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_bulk_revert_preview",
        "session_worker",
        "revert_preview",
        "ui_only",
        "AgentRevertMixin._submit_bulk_revert_preview",
        "",
        identifiers=("agent_names",),
        result_kind="agent.revert-preview",
        restart_recovery="not durable; preview is session-local",
    ),
    _site(
        "bead.mutate",
        "src/sase/ace/tui/actions/_artifacts_beads_common.py",
        "_submit_beads_task",
        "session_worker",
        "bead-*",
        "ui_only",
        "ArtifactsBeadsCommonMixin._submit_beads_task",
        "",
        identifiers=("bead_id", "operation"),
        result_kind="bead.status",
        concurrency_keys=("beads:{operation}:{project}:{bead_id}",),
        optimistic_ui="pane refresh",
        restart_recovery="not durable; session-local bead mutation",
    ),
    _site(
        "bead.issue",
        "src/sase/ace/tui/actions/_artifacts_beads_issue_mutations.py",
        "_submit_bead_issue_mutation",
        "session_worker",
        "bead-issue-*",
        "ui_only",
        "ArtifactsBeadsIssueMutationsMixin._submit_bead_issue_mutation",
        "",
        identifiers=("issue_id", "operation"),
        result_kind="bead.issue",
        restart_recovery="not durable; session-local issue mutation",
    ),
    _site(
        "glossary.write",
        "src/sase/ace/tui/modals/glossary_panel_actions.py",
        "_submit_glossary_write",
        "session_worker",
        "glossary-*",
        "ui_only",
        "GlossaryPanelActionsMixin._submit_glossary_write",
        "",
        identifiers=("project_key", "kind"),
        result_kind="glossary.mutation",
        concurrency_keys=("glossary-write:{project_key}",),
        optimistic_ui="reselect term; toast; config commit offer",
        restart_recovery="not durable; session-local glossary write",
    ),
    _site(
        "snippet.write",
        "src/sase/ace/tui/modals/snippets_panel_actions.py",
        "_submit_snippet_write",
        "session_worker",
        "snippet-*",
        "ui_only",
        "SnippetsPanelActionsMixin._submit_snippet_write",
        "",
        identifiers=("project_key", "kind", "destination"),
        result_kind="snippet.mutation",
        concurrency_keys=("snippet-write:{project_key}:{destination}",),
        optimistic_ui="reselect trigger; toast; session overlay; post-write offer",
        restart_recovery="not durable; session-local snippet write",
    ),
    _site(
        "memory.write",
        "src/sase/ace/tui/modals/memory_panel_actions.py",
        "_submit_memory_write",
        "session_worker",
        "memory-*",
        "ui_only",
        "MemoryPanelActionsMixin._submit_memory_write",
        "",
        identifiers=("scope_key", "kind"),
        result_kind="memory.mutation",
        concurrency_keys=("memory-write:{scope_key}",),
        optimistic_ui="reselect note; toast; unpublished mark; publish offer",
        restart_recovery="not durable; session-local memory write",
    ),
    _site(
        "memory.publish",
        "src/sase/ace/tui/modals/memory_panel_publish_actions.py",
        "_submit_memory_publish",
        "session_worker",
        "memory-publish",
        "ui_only",
        "MemoryPanelPublishActionsMixin._submit_memory_publish",
        "sase memory init",
        identifiers=("scope_key",),
        result_kind="memory.publish",
        concurrency_keys=("memory-write:{scope_key}",),
        optimistic_ui="clear unpublished badge; toast",
        restart_recovery="not durable; session-local memory publish",
    ),
    _site(
        "bead.issue_open",
        "src/sase/ace/tui/actions/_artifacts_beads_issue_actions.py",
        "_submit_beads_issue_open",
        "ui_worker",
        "browser-open",
        "ui_only",
        "ArtifactsBeadsIssueActionsMixin._submit_beads_issue_open",
        "",
        identifiers=("issue_id",),
        result_kind="bead.issue-open",
        restart_recovery="not durable; browser open is session-local",
    ),
    _site(
        "notify.state",
        "src/sase/ace/tui/modals/notification_modal_action_support.py",
        "_submit_notification_state_task",
        "duck_submit_durable",
        "NOTIFY_APPLY_STATE",
        "durable",
        "NotificationActionSupportMixin._submit_notification_state_task",
        "sase notify apply-state",
        identifiers=("notification_id", "action"),
        result_kind="notify.apply-state",
        concurrency_keys=("notification-state",),
    ),
    _site(
        "notify.gate",
        "src/sase/ace/tui/actions/agents/_notification_gate_execution.py",
        "submit_gate_execution_task",
        "duck_submit_durable",
        "GATE_ANSWER",
        "durable",
        "submit_gate_execution_task",
        "sase gate answer",
        identifiers=("request_id",),
        result_kind="gate.answer",
        concurrency_keys=("notification-gate:{id}",),
    ),
    _site(
        "notify.gate_action",
        "src/sase/ace/tui/actions/agents/_notification_gate_actions.py",
        "run_command",
        "duck_submit_durable",
        "GATE_ACT",
        "durable",
        "NotificationGateActionRunner.run_command",
        "sase gate act",
        identifiers=("notification_id", "operation_id"),
        result_kind="gate.act",
        concurrency_keys=("gate-action:{id}:{operation}",),
    ),
    _site(
        "notify.question",
        "src/sase/ace/tui/actions/agents/_notification_question_modal.py",
        "_submit_question_response_task",
        "session_worker",
        "question",
        "ui_only",
        "_submit_question_response_task",
        "",
        identifiers=("request_id",),
        result_kind="question.response",
        restart_recovery="not durable; session-local notification response",
    ),
    _site(
        "notify.plan_gate",
        "src/sase/ace/tui/actions/agents/_notification_plan_gate.py",
        "submit_neutral_plan_response",
        "session_worker",
        "plan-gate",
        "ui_only",
        "submit_neutral_plan_response",
        "",
        identifiers=("notification_id",),
        result_kind="plan.gate",
        restart_recovery="not durable; session-local plan response",
    ),
    _site(
        "notify.launch_approval",
        "src/sase/ace/tui/actions/agents/_notification_launch_approval.py",
        "_submit_launch_approval_task",
        "duck_submit_durable",
        "LAUNCH_APPROVAL",
        "durable",
        "_submit_launch_approval_task",
        "sase launch approve",
        identifiers=("request_id",),
        result_kind="launch.approval",
        concurrency_keys=("launch-approval:{id}",),
    ),
    _site(
        "notify.legacy_epic",
        "src/sase/ace/tui/actions/agents/_notification_modals.py",
        "_submit_legacy_epic_launch_task",
        "session_worker",
        "launch",
        "ui_only",
        "_submit_legacy_epic_launch_task",
        "",
        identifiers=("notification_id",),
        result_kind="run.launch",
        concurrency_keys=("legacy-epic-launch:{notification_id}",),
        restart_recovery="not durable; session-local launch preparation",
    ),
    _site(
        "agents.sync",
        "src/sase/ace/tui/actions/agents_sync.py",
        "action_sync_agents",
        "session_worker",
        "agents-sync",
        "ui_only",
        "AgentsSyncActionsMixin.action_sync_agents",
        "",
        identifiers=(),
        result_kind="agent.sync",
        concurrency_keys=("agents-sync",),
        restart_recovery="not durable; session-local agents sync",
    ),
    _site(
        "agents.cached",
        "src/sase/ace/tui/actions/agents_sync.py",
        "action_integrate_cached_agents",
        "session_worker",
        "agents-cached-integration",
        "ui_only",
        "AgentsSyncActionsMixin.action_integrate_cached_agents",
        "",
        identifiers=(),
        result_kind="agent.sync",
        concurrency_keys=("agents-sync",),
        restart_recovery="not durable; session-local agents sync",
    ),
)
