"""Proc-producer sites for ACE maintenance and update flows."""

from __future__ import annotations

from sase.ace.tui._proc_producer_site import ProcProducerSite, site


UPDATE_PRODUCERS: tuple[ProcProducerSite, ...] = (
    site(
        "plugin.update",
        "src/sase/ace/tui/modals/plugins_browser_update.py",
        "_submit_update_task",
        "duck_submit_durable",
        "PLUGIN_UPDATE",
        "durable",
        "PluginsBrowserUpdateMixin._submit_update_task",
        "sase plugin update",
        identifiers=("plugin",),
        result_kind="plugin.update",
        concurrency_keys=("plugin-update:{name}",),
    ),
    site(
        "plugin.install",
        "src/sase/ace/tui/modals/plugins_browser_install.py",
        "_submit_install_task",
        "duck_submit_durable",
        "PLUGIN_INSTALL",
        "durable",
        "PluginsBrowserInstallMixin._submit_install_task",
        "sase plugin install",
        identifiers=("plugin",),
        result_kind="plugin.install",
        concurrency_keys=("plugin-install:{name}",),
    ),
    site(
        "plugin.install_many",
        "src/sase/ace/tui/modals/plugins_browser_install.py",
        "_submit_install_many_task",
        "session_worker",
        "plugin-install",
        "ui_only",
        "PluginsBrowserInstallMixin._submit_install_many_task",
        "",
        identifiers=("plugins",),
        result_kind="plugin.install",
        restart_recovery="not durable; session-local plugin install batch",
    ),
    site(
        "plugin.uninstall",
        "src/sase/ace/tui/modals/plugins_browser_uninstall.py",
        "_submit_uninstall_task",
        "duck_submit_durable",
        "PLUGIN_UNINSTALL",
        "durable",
        "PluginsBrowserUninstallMixin._submit_uninstall_task",
        "sase plugin uninstall",
        identifiers=("plugin",),
        result_kind="plugin.uninstall",
        concurrency_keys=("plugin-uninstall:{name}",),
    ),
    site(
        "plugin.mode_switch",
        "src/sase/ace/tui/modals/plugins_browser_mode_switch.py",
        "_submit_mode_switch_task",
        "session_worker",
        "mode-switch",
        "ui_only",
        "PluginsBrowserModeSwitchMixin._submit_mode_switch_task",
        "",
        identifiers=("target_mode",),
        result_kind="plugin.mode-switch",
        restart_recovery="not durable; session-local update workflow",
    ),
    site(
        "plugin.sase_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_sase_update_proc",
        "session_worker",
        "sase-update",
        "ui_only",
        "SaseUpdateProcMixin._submit_sase_update_proc",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    site(
        "plugin.dev_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_dev_update_proc",
        "session_worker",
        "dev-update",
        "ui_only",
        "SaseUpdateProcMixin._submit_dev_update_proc",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    site(
        "plugin.combined_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_combined_update_proc",
        "session_worker",
        "sase-update",
        "ui_only",
        "SaseUpdateProcMixin._submit_combined_update_proc",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    site(
        "plugin.agent_cli_update",
        "src/sase/ace/tui/modals/plugins_browser_agent_clis_actions.py",
        "_submit_agent_cli_update_task",
        "session_worker",
        "agent-cli-update",
        "ui_only",
        "PluginsBrowserAgentClisActionsMixin._submit_agent_cli_update_task",
        "",
        identifiers=(),
        result_kind="agent-cli.update",
        concurrency_keys=("agent-cli-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    site(
        "update.preview",
        "src/sase/ace/tui/actions/update_run.py",
        "_submit_update_preview_proc",
        "session_worker",
        "update-preview",
        "ui_only",
        "UpdateRunActionsMixin._submit_update_preview_proc",
        "",
        identifiers=(),
        result_kind="sase.update.preview",
        concurrency_keys=("update-preview",),
        restart_recovery="not durable; session-local update workflow",
    ),
    site(
        "update.scoped",
        "src/sase/ace/tui/actions/update_run.py",
        "_submit_scoped_update_task",
        "session_worker",
        "comprehensive-update",
        "ui_only",
        "UpdateRunActionsMixin._submit_scoped_update_task",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=(
            "comprehensive-update",
            "sase-update",
            "agent-cli-update",
        ),
        restart_recovery="not durable; session-local update workflow",
    ),
)
