"""Catalog of ACE proc-producer sites and related infrastructure."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Classification = Literal["durable", "ui_only", "adapter", "infrastructure"]
CallKind = Literal[
    "direct_submit_durable",
    "session_worker",
    "duck_submit_durable",
]


@dataclass(frozen=True, slots=True)
class _ProcProducerSite:
    """One inventoried ACE submit site or related infrastructure entry."""

    site_id: str
    source_path: str
    function: str
    kind: CallKind | Literal["definition", "test_double", "ui_worker"]
    proc_type: str
    classification: Classification
    owning_action: str
    domain_command: str
    identifiers: tuple[str, ...]
    result_kind: str
    fingerprint_inputs: tuple[str, ...]
    concurrency_keys: tuple[str, ...]
    optimistic_ui: str
    restart_recovery: str


def _site(
    site_id: str,
    source_path: str,
    function: str,
    kind: CallKind | Literal["definition", "test_double", "ui_worker"],
    proc_type: str,
    classification: Classification,
    owning_action: str,
    domain_command: str,
    *,
    identifiers: tuple[str, ...] = (),
    result_kind: str = "success_message",
    fingerprint_inputs: tuple[str, ...] = (),
    concurrency_keys: tuple[str, ...] = (),
    optimistic_ui: str = "none",
    restart_recovery: str = "replay from durable result envelope",
) -> _ProcProducerSite:
    return _ProcProducerSite(
        site_id=site_id,
        source_path=source_path,
        function=function,
        kind=kind,
        proc_type=proc_type,
        classification=classification,
        owning_action=owning_action,
        domain_command=domain_command,
        identifiers=identifiers,
        result_kind=result_kind,
        fingerprint_inputs=fingerprint_inputs or identifiers,
        concurrency_keys=concurrency_keys,
        optimistic_ui=optimistic_ui,
        restart_recovery=restart_recovery,
    )


PRODUCTION_PRODUCERS: tuple[_ProcProducerSite, ...] = (
    _site(
        "patch.durable",
        "src/sase/ace/tui/actions/patch_durable.py",
        "submit_patch_operation",
        "direct_submit_durable",
        "dynamic",
        "durable",
        "submit_patch_operation",
        "sase patch",
        identifiers=("project_file", "name", "verb"),
        result_kind="patch.*",
        concurrency_keys=("ace:patch:{project}:{name}",),
        optimistic_ui="start toast; hook reset; optional mail on accept",
    ),
    _site(
        "axe.bgcmd",
        "src/sase/ace/tui/actions/axe_bgcmd.py",
        "_start_bgcmd",
        "direct_submit_durable",
        "AXE_BGCMD",
        "durable",
        "AxeBgCmdMixin",
        "sase run",
        identifiers=("slot", "project_file"),
        result_kind="axe.bgcmd",
        concurrency_keys=("axe-slot:{slot}",),
        optimistic_ui="mark slot pending",
    ),
    _site(
        "monitor.stop",
        "src/sase/ace/tui/actions/agents/_monitor_stop_flow.py",
        "_do_stop_monitor",
        "direct_submit_durable",
        "MONITOR_STOP",
        "durable",
        "MonitorStopActionFlowMixin._do_stop_monitor",
        "sase monitor stop",
        identifiers=("monitor_id",),
        result_kind="monitor.stop",
        concurrency_keys=("monitor:{id}",),
    ),
    _site(
        "agent.launch",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_launch",
        "direct_submit_durable",
        "launch",
        "durable",
        "submit_agent_launch",
        "sase run",
        identifiers=("workflow", "project_file"),
        result_kind="run.launch",
        concurrency_keys=("ace:launch:{workflow}",),
        optimistic_ui="launch-result delta; agent refresh",
    ),
    _site(
        "agent.cleanup",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_cleanup",
        "direct_submit_durable",
        "dynamic",
        "durable",
        "submit_agent_cleanup",
        "sase agent persist-cleanup",
        identifiers=("proc_type", "identity"),
        result_kind="agent.cleanup",
        concurrency_keys=("ace:cleanup:{proc_type}:{identity}",),
        optimistic_ui="agents refresh",
    ),
    _site(
        "agent.directive",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_directive",
        "direct_submit_durable",
        "agent-directive",
        "durable",
        "submit_agent_directive",
        "sase agent persist-directive",
        identifiers=("artifacts_dir",),
        result_kind="agent.persist-directive",
        concurrency_keys=("ace:agent-directive:{artifacts_dir}",),
        optimistic_ui="optimistic fields; guarded rollback",
    ),
    _site(
        "agent.revert.preview",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_revert_preview",
        "session_worker",
        "revert_preview",
        "ui_only",
        "AgentRevertMixin._submit_revert_preview",
        "",
        identifiers=("agent_name",),
        result_kind="agent.revert-preview",
        restart_recovery="not durable; preview is session-local",
    ),
    _site(
        "agent.revert.execute",
        "src/sase/ace/tui/actions/agent_durable.py",
        "submit_agent_revert",
        "direct_submit_durable",
        "revert_agent",
        "durable",
        "submit_agent_revert",
        "sase agent revert",
        identifiers=("agent_name",),
        result_kind="agent.revert",
        concurrency_keys=("ace:agent-revert:execute:{key}",),
    ),
    _site(
        "agent.revert.bulk_preview",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_bulk_revert_preview",
        "session_worker",
        "revert_preview",
        "ui_only",
        "AgentRevertMixin._submit_bulk_revert_preview",
        "",
        identifiers=("agent_names",),
        result_kind="agent.revert-preview",
        restart_recovery="not durable; preview is session-local",
    ),
    _site(
        "bead.mutate",
        "src/sase/ace/tui/actions/_artifacts_beads_common.py",
        "_submit_beads_task",
        "session_worker",
        "bead-*",
        "ui_only",
        "ArtifactsBeadsCommonMixin._submit_beads_task",
        "",
        identifiers=("bead_id", "operation"),
        result_kind="bead.status",
        concurrency_keys=("beads:{operation}:{project}:{bead_id}",),
        optimistic_ui="pane refresh",
        restart_recovery="not durable; session-local bead mutation",
    ),
    _site(
        "bead.issue",
        "src/sase/ace/tui/actions/_artifacts_beads_issue_mutations.py",
        "_submit_bead_issue_mutation",
        "session_worker",
        "bead-issue-*",
        "ui_only",
        "ArtifactsBeadsIssueMutationsMixin._submit_bead_issue_mutation",
        "",
        identifiers=("issue_id", "operation"),
        result_kind="bead.issue",
        restart_recovery="not durable; session-local issue mutation",
    ),
    _site(
        "bead.issue_open",
        "src/sase/ace/tui/actions/_artifacts_beads_issue_actions.py",
        "_submit_beads_issue_open",
        "ui_worker",
        "browser-open",
        "ui_only",
        "ArtifactsBeadsIssueActionsMixin._submit_beads_issue_open",
        "",
        identifiers=("issue_id",),
        result_kind="bead.issue-open",
        restart_recovery="not durable; browser open is session-local",
    ),
    _site(
        "notify.state",
        "src/sase/ace/tui/modals/notification_modal_action_support.py",
        "_submit_notification_state_task",
        "duck_submit_durable",
        "NOTIFY_APPLY_STATE",
        "durable",
        "NotificationActionSupportMixin._submit_notification_state_task",
        "sase notify apply-state",
        identifiers=("notification_id", "action"),
        result_kind="notify.apply-state",
        concurrency_keys=("notification-state",),
    ),
    _site(
        "notify.gate",
        "src/sase/ace/tui/actions/agents/_notification_gate_execution.py",
        "submit_gate_execution_task",
        "duck_submit_durable",
        "GATE_ANSWER",
        "durable",
        "submit_gate_execution_task",
        "sase gate answer",
        identifiers=("request_id",),
        result_kind="gate.answer",
        concurrency_keys=("notification-gate:{id}",),
    ),
    _site(
        "notify.gate_action",
        "src/sase/ace/tui/actions/agents/_notification_gate_actions.py",
        "run_command",
        "duck_submit_durable",
        "GATE_ACT",
        "durable",
        "NotificationGateActionRunner.run_command",
        "sase gate act",
        identifiers=("notification_id", "operation_id"),
        result_kind="gate.act",
        concurrency_keys=("gate-action:{id}:{operation}",),
    ),
    _site(
        "notify.question",
        "src/sase/ace/tui/actions/agents/_notification_question_modal.py",
        "_submit_question_response_task",
        "session_worker",
        "question",
        "ui_only",
        "_submit_question_response_task",
        "",
        identifiers=("request_id",),
        result_kind="question.response",
        restart_recovery="not durable; session-local notification response",
    ),
    _site(
        "notify.plan_gate",
        "src/sase/ace/tui/actions/agents/_notification_plan_gate.py",
        "submit_neutral_plan_response",
        "session_worker",
        "plan-gate",
        "ui_only",
        "submit_neutral_plan_response",
        "",
        identifiers=("notification_id",),
        result_kind="plan.gate",
        restart_recovery="not durable; session-local plan response",
    ),
    _site(
        "notify.launch_approval",
        "src/sase/ace/tui/actions/agents/_notification_launch_approval.py",
        "_submit_launch_approval_task",
        "duck_submit_durable",
        "LAUNCH_APPROVAL",
        "durable",
        "_submit_launch_approval_task",
        "sase launch approve",
        identifiers=("request_id",),
        result_kind="launch.approval",
        concurrency_keys=("launch-approval:{id}",),
    ),
    _site(
        "notify.legacy_epic",
        "src/sase/ace/tui/actions/agents/_notification_modals.py",
        "_submit_legacy_epic_launch_task",
        "session_worker",
        "launch",
        "ui_only",
        "_submit_legacy_epic_launch_task",
        "",
        identifiers=("notification_id",),
        result_kind="run.launch",
        concurrency_keys=("legacy-epic-launch:{notification_id}",),
        restart_recovery="not durable; session-local launch preparation",
    ),
    _site(
        "agents.sync",
        "src/sase/ace/tui/actions/agents_sync.py",
        "action_sync_agents",
        "session_worker",
        "agents-sync",
        "ui_only",
        "AgentsSyncActionsMixin.action_sync_agents",
        "",
        identifiers=(),
        result_kind="agent.sync",
        concurrency_keys=("agents-sync",),
        restart_recovery="not durable; session-local agents sync",
    ),
    _site(
        "agents.cached",
        "src/sase/ace/tui/actions/agents_sync.py",
        "action_integrate_cached_agents",
        "session_worker",
        "agents-cached-integration",
        "ui_only",
        "AgentsSyncActionsMixin.action_integrate_cached_agents",
        "",
        identifiers=(),
        result_kind="agent.sync",
        concurrency_keys=("agents-sync",),
        restart_recovery="not durable; session-local agents sync",
    ),
    _site(
        "plugin.update",
        "src/sase/ace/tui/modals/plugins_browser_update.py",
        "_submit_update_task",
        "duck_submit_durable",
        "PLUGIN_UPDATE",
        "durable",
        "PluginsBrowserUpdateMixin._submit_update_task",
        "sase plugin update",
        identifiers=("plugin",),
        result_kind="plugin.update",
        concurrency_keys=("plugin-update:{name}",),
    ),
    _site(
        "plugin.install",
        "src/sase/ace/tui/modals/plugins_browser_install.py",
        "_submit_install_task",
        "duck_submit_durable",
        "PLUGIN_INSTALL",
        "durable",
        "PluginsBrowserInstallMixin._submit_install_task",
        "sase plugin install",
        identifiers=("plugin",),
        result_kind="plugin.install",
        concurrency_keys=("plugin-install:{name}",),
    ),
    _site(
        "plugin.install_many",
        "src/sase/ace/tui/modals/plugins_browser_install.py",
        "_submit_install_many_task",
        "session_worker",
        "plugin-install",
        "ui_only",
        "PluginsBrowserInstallMixin._submit_install_many_task",
        "",
        identifiers=("plugins",),
        result_kind="plugin.install",
        restart_recovery="not durable; session-local plugin install batch",
    ),
    _site(
        "plugin.uninstall",
        "src/sase/ace/tui/modals/plugins_browser_uninstall.py",
        "_submit_uninstall_task",
        "duck_submit_durable",
        "PLUGIN_UNINSTALL",
        "durable",
        "PluginsBrowserUninstallMixin._submit_uninstall_task",
        "sase plugin uninstall",
        identifiers=("plugin",),
        result_kind="plugin.uninstall",
        concurrency_keys=("plugin-uninstall:{name}",),
    ),
    _site(
        "plugin.mode_switch",
        "src/sase/ace/tui/modals/plugins_browser_mode_switch.py",
        "_submit_mode_switch_task",
        "session_worker",
        "mode-switch",
        "ui_only",
        "PluginsBrowserModeSwitchMixin._submit_mode_switch_task",
        "",
        identifiers=("target_mode",),
        result_kind="plugin.mode-switch",
        restart_recovery="not durable; session-local update workflow",
    ),
    _site(
        "plugin.sase_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_sase_update_proc",
        "session_worker",
        "sase-update",
        "ui_only",
        "SaseUpdateProcMixin._submit_sase_update_proc",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    _site(
        "plugin.dev_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_dev_update_proc",
        "session_worker",
        "dev-update",
        "ui_only",
        "SaseUpdateProcMixin._submit_dev_update_proc",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    _site(
        "plugin.combined_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_combined_update_proc",
        "session_worker",
        "sase-update",
        "ui_only",
        "SaseUpdateProcMixin._submit_combined_update_proc",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    _site(
        "plugin.agent_cli_update",
        "src/sase/ace/tui/modals/plugins_browser_agent_clis_actions.py",
        "_submit_agent_cli_update_task",
        "session_worker",
        "agent-cli-update",
        "ui_only",
        "PluginsBrowserAgentClisActionsMixin._submit_agent_cli_update_task",
        "",
        identifiers=(),
        result_kind="agent-cli.update",
        concurrency_keys=("agent-cli-update",),
        restart_recovery="not durable; session-local update workflow",
    ),
    _site(
        "plugin.comprehensive",
        "src/sase/ace/tui/modals/plugins_browser_comprehensive_update.py",
        "_submit_comprehensive_update_task",
        "session_worker",
        "comprehensive-update",
        "ui_only",
        "PluginsBrowserComprehensiveUpdateMixin._submit_comprehensive_update_task",
        "",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=(
            "comprehensive-update",
            "sase-update",
            "agent-cli-update",
            "agents-sync",
        ),
        restart_recovery="not durable; session-local update workflow",
    ),
    _site(
        "xprompt.commit",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_save_xprompt_git.py",
        "_submit_xprompt_commit_task",
        "duck_submit_durable",
        "GIT_POST_WRITE",
        "durable",
        "_submit_xprompt_commit_task",
        "sase stitch create",
        identifiers=("git_root", "rel_path"),
        result_kind="git.commit",
        concurrency_keys=("{noun}-commit:{git_root}:{rel_path}",),
    ),
    _site(
        "xprompt.post_write",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_save_xprompt_git.py",
        "_submit_post_write_action",
        "duck_submit_durable",
        "GIT_POST_WRITE",
        "durable",
        "_submit_post_write_action",
        "sase stitch create",
        identifiers=("rel_path",),
        result_kind="git.commit",
    ),
    _site(
        "config.commit",
        "src/sase/ace/tui/modals/config_commit.py",
        "submit_config_commit_task",
        "duck_submit_durable",
        "GIT_POST_WRITE",
        "durable",
        "submit_config_commit_task",
        "sase stitch create",
        identifiers=("git_root", "rel_path"),
        result_kind="git.commit",
        concurrency_keys=("config-commit:{git_root}:{rel_path}",),
    ),
    _site(
        "prompt.stash",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_stash.py",
        "_submit_prompt_stash_persist_task",
        "ui_worker",
        "prompt-stash",
        "ui_only",
        "_submit_prompt_stash_persist_task",
        "",
        identifiers=("entry_id",),
        result_kind="prompt.stash",
        restart_recovery="not a durable proc; session-local stash persist",
    ),
    _site(
        "commits.fetch",
        "src/sase/ace/tui/widgets/artifacts/commits_pane.py",
        "fetch_commits",
        "ui_worker",
        "commit-fetch",
        "ui_only",
        "CommitsPane.fetch_commits",
        "",
        identifiers=("scope",),
        result_kind="commit.fetch",
        restart_recovery="not durable; pane fetch is session-local",
    ),
)


INFRASTRUCTURE: tuple[_ProcProducerSite, ...] = (
    _site(
        "infra.submit_durable",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_submit_durable_proc",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="submit only; observer decodes typed result envelope",
    ),
    _site(
        "infra.submit_session",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_submit_session_worker",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="session-local worker; not durable",
    ),
    _site(
        "infra.proc_observer",
        "src/sase/ace/tui/proc_observer.py",
        "ProcObserver",
        "definition",
        "",
        "infrastructure",
        "ProcObserver",
        "",
        restart_recovery="read-only durable proc projection",
    ),
    _site(
        "infra.observer_completion",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_apply_proc_observer_snapshot",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="live-session callback from observer envelope",
    ),
)


__all__ = [
    "CallKind",
    "INFRASTRUCTURE",
    "PRODUCTION_PRODUCERS",
]
