"""Catalog of ACE proc-producer sites and related infrastructure."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Classification = Literal["durable", "ui_only", "adapter", "infrastructure"]
CallKind = Literal[
    "direct_submit_proc",
    "direct_submit_tracked",
    "duck_submit",
    "adapter_forward",
]


@dataclass(frozen=True, slots=True)
class _ProcProducerSite:
    """One inventoried ACE submit site or related infrastructure entry."""

    site_id: str
    source_path: str
    function: str
    kind: CallKind | Literal["definition", "test_double"]
    proc_type: str
    classification: Classification
    owning_action: str
    domain_command: str
    identifiers: tuple[str, ...]
    result_kind: str
    fingerprint_inputs: tuple[str, ...]
    concurrency_keys: tuple[str, ...]
    optimistic_ui: str
    restart_recovery: str


@dataclass(frozen=True, slots=True)
class FoundProducerCall:
    """One production submit call discovered by the AST scanner."""

    source_path: str
    function: str
    kind: CallKind
    proc_type: str
    index: int

    @property
    def site_key(self) -> tuple[str, str, str, str, int]:
        return (
            self.source_path,
            self.function,
            self.kind,
            self.proc_type,
            self.index,
        )


def _site(
    site_id: str,
    source_path: str,
    function: str,
    kind: CallKind | Literal["definition", "test_double"],
    proc_type: str,
    classification: Classification,
    owning_action: str,
    domain_command: str,
    *,
    identifiers: tuple[str, ...] = (),
    result_kind: str = "success_message",
    fingerprint_inputs: tuple[str, ...] = (),
    concurrency_keys: tuple[str, ...] = (),
    optimistic_ui: str = "none",
    restart_recovery: str = "replay from durable result envelope",
) -> _ProcProducerSite:
    return _ProcProducerSite(
        site_id=site_id,
        source_path=source_path,
        function=function,
        kind=kind,
        proc_type=proc_type,
        classification=classification,
        owning_action=owning_action,
        domain_command=domain_command,
        identifiers=identifiers,
        result_kind=result_kind,
        fingerprint_inputs=fingerprint_inputs or identifiers,
        concurrency_keys=concurrency_keys,
        optimistic_ui=optimistic_ui,
        restart_recovery=restart_recovery,
    )


PRODUCTION_PRODUCERS: tuple[_ProcProducerSite, ...] = (
    _site(
        "adapter.forward",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_submit_proc",
        "adapter_forward",
        "passthrough",
        "adapter",
        "ProcActionsMixin._submit_proc",
        "",
        restart_recovery="not a domain producer",
    ),
    _site(
        "patch.revert",
        "src/sase/ace/tui/actions/status.py",
        "_apply_status_change",
        "direct_submit_proc",
        "revert",
        "durable",
        "StatusActionsMixin._apply_status_change",
        "sase patch revert",
        identifiers=("project_file", "name"),
        result_kind="patch.revert",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast",
    ),
    _site(
        "patch.submit",
        "src/sase/ace/tui/actions/status.py",
        "_apply_status_change",
        "direct_submit_proc",
        "submit",
        "durable",
        "StatusActionsMixin._apply_status_change",
        "sase patch submit",
        identifiers=("project_file", "name"),
        result_kind="patch.submit",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast",
    ),
    _site(
        "patch.archive",
        "src/sase/ace/tui/actions/status.py",
        "_apply_status_change",
        "direct_submit_proc",
        "archive",
        "durable",
        "StatusActionsMixin._apply_status_change",
        "sase patch archive",
        identifiers=("project_file", "name"),
        result_kind="patch.archive",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast",
    ),
    _site(
        "patch.restore",
        "src/sase/ace/tui/actions/status.py",
        "_apply_status_change",
        "direct_submit_proc",
        "restore",
        "durable",
        "StatusActionsMixin._apply_status_change",
        "sase patch restore",
        identifiers=("project_file", "name", "status"),
        result_kind="patch.restore",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast",
    ),
    _site(
        "patch.status",
        "src/sase/ace/tui/actions/status.py",
        "_apply_status_change",
        "direct_submit_proc",
        "status",
        "durable",
        "StatusActionsMixin._apply_status_change",
        "sase patch status",
        identifiers=("project_file", "name", "status"),
        result_kind="patch.status",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast",
    ),
    _site(
        "patch.sync",
        "src/sase/ace/tui/actions/sync.py",
        "action_sync",
        "direct_submit_proc",
        "sync",
        "durable",
        "SyncActionsMixin.action_sync",
        "sase patch sync",
        identifiers=("project_file", "name"),
        result_kind="patch.sync",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast; reset dollar hooks",
    ),
    _site(
        "patch.reword",
        "src/sase/ace/tui/actions/base.py",
        "action_reword",
        "direct_submit_proc",
        "reword",
        "durable",
        "BaseActionsMixin.action_reword",
        "sase patch reword",
        identifiers=("project_file", "name"),
        result_kind="patch.reword",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast; reset dollar hooks",
    ),
    _site(
        "patch.tag",
        "src/sase/ace/tui/actions/base.py",
        "on_dismiss",
        "direct_submit_proc",
        "add_tag",
        "durable",
        "BaseActionsMixin.action_add_tag",
        "sase patch tag",
        identifiers=("project_file", "name", "tag"),
        result_kind="patch.tag",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast; reset dollar hooks",
    ),
    _site(
        "patch.mail",
        "src/sase/ace/tui/actions/base.py",
        "action_mail",
        "direct_submit_proc",
        "mail",
        "durable",
        "BaseActionsMixin.action_mail",
        "sase patch mail",
        identifiers=("project_file", "name"),
        result_kind="patch.mail",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="workspace claimed before submit; start toast",
    ),
    _site(
        "patch.accept",
        "src/sase/ace/tui/actions/proposal_rebase.py",
        "_run_accept_workflow",
        "direct_submit_proc",
        "accept",
        "durable",
        "ProposalRebaseMixin",
        "sase patch accept",
        identifiers=("project_file", "name"),
        result_kind="patch.accept",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast; optional mail on success",
    ),
    _site(
        "patch.rebase",
        "src/sase/ace/tui/actions/proposal_rebase.py",
        "_run_rebase_workflow",
        "direct_submit_proc",
        "rebase",
        "durable",
        "ProposalRebaseMixin._run_rebase_workflow",
        "sase patch rebase",
        identifiers=("project_file", "name", "parent"),
        result_kind="patch.rebase",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast",
    ),
    _site(
        "patch.rewind",
        "src/sase/ace/tui/actions/hints/_rewind.py",
        "_run_rewind_workflow",
        "direct_submit_proc",
        "rewind",
        "durable",
        "RewindMixin._run_rewind_workflow",
        "sase patch rewind",
        identifiers=("project_file", "name", "entry"),
        result_kind="patch.rewind",
        concurrency_keys=("patch:{name}",),
        optimistic_ui="start toast",
    ),
    _site(
        "axe.bgcmd",
        "src/sase/ace/tui/actions/axe_bgcmd.py",
        "_start_bgcmd",
        "direct_submit_proc",
        "bgcmd-launch",
        "durable",
        "AxeBgCmdMixin",
        "sase run",
        identifiers=("slot", "project_file"),
        result_kind="axe.bgcmd",
        concurrency_keys=("axe-slot:{slot}",),
        optimistic_ui="mark slot pending",
    ),
    _site(
        "monitor.stop",
        "src/sase/ace/tui/actions/agents/_monitor_stop_flow.py",
        "_do_stop_monitor",
        "direct_submit_proc",
        "monitor-stop",
        "durable",
        "MonitorStopActionFlowMixin._do_stop_monitor",
        "sase monitor stop",
        identifiers=("monitor_id",),
        result_kind="monitor.stop",
        concurrency_keys=("monitor:{id}",),
    ),
    _site(
        "agent.launch",
        "src/sase/ace/tui/actions/agent_workflow/_launch_procs.py",
        "_submit_launch_proc",
        "direct_submit_tracked",
        "launch",
        "durable",
        "LaunchProcMixin._submit_launch_proc",
        "sase run",
        identifiers=("workflow", "project_file"),
        result_kind="run.launch",
        concurrency_keys=("launch:{workflow}",),
        optimistic_ui="launch-result delta; agent refresh",
    ),
    _site(
        "agent.cleanup",
        "src/sase/ace/tui/actions/agents/_cleanup_procs.py",
        "_submit_cleanup_proc",
        "direct_submit_tracked",
        "dynamic",
        "durable",
        "CleanupProcMixin._submit_cleanup_proc",
        "sase agent kill",
        identifiers=("proc_type", "agent_name"),
        result_kind="agent.cleanup",
        concurrency_keys=("{proc_type}:{uuid}",),
        optimistic_ui="agents refresh",
    ),
    _site(
        "agent.rename",
        "src/sase/ace/tui/actions/rename.py",
        "handle_name_result",
        "direct_submit_tracked",
        "agent-directive",
        "durable",
        "RenameMixin._set_agent_name",
        "sase agent persist-directive",
        identifiers=("artifacts_dir", "new_name"),
        result_kind="agent.persist-directive",
        concurrency_keys=("agent-directive-persist:{artifacts_dir}",),
        optimistic_ui="optimistic name + refilter; rollback on fail",
    ),
    _site(
        "agent.approve",
        "src/sase/ace/tui/actions/agents/_approve.py",
        "_apply_auto_approve_choice",
        "direct_submit_tracked",
        "agent-directive",
        "durable",
        "AgentApproveMixin._apply_auto_approve_choice",
        "sase agent persist-directive",
        identifiers=("artifacts_dir", "mode"),
        result_kind="agent.persist-directive",
        concurrency_keys=("agent-directive-persist:{artifacts_dir}",),
        optimistic_ui="optimistic approve fields; rollback on fail",
    ),
    _site(
        "agent.tribe",
        "src/sase/ace/tui/actions/agents/_tribe_assignment.py",
        "_apply_agent_tribe_change",
        "direct_submit_tracked",
        "agent-directive",
        "durable",
        "AgentTribeAssignmentMixin._apply_agent_tribe_change",
        "sase agent persist-directive",
        identifiers=("identity", "tribe"),
        result_kind="agent.persist-directive",
        concurrency_keys=("agent-directive-persist:tribes",),
        optimistic_ui="optimistic tribe fields; rollback on fail",
    ),
    _site(
        "agent.wait.set",
        "src/sase/ace/tui/actions/agents/_wait_actions.py",
        "_apply_wait",
        "direct_submit_tracked",
        "agent-directive",
        "durable",
        "AgentWaitActionsMixin._apply_wait",
        "sase agent persist-directive",
        identifiers=("artifacts_dir", "wait_names"),
        result_kind="agent.persist-directive",
        concurrency_keys=("agent-directive-persist:{artifacts_dir}",),
        optimistic_ui="optimistic wait fields",
    ),
    _site(
        "agent.wait.clear",
        "src/sase/ace/tui/actions/agents/_wait_actions.py",
        "_apply_wait",
        "direct_submit_tracked",
        "agent-directive",
        "durable",
        "AgentWaitActionsMixin._apply_wait",
        "sase agent persist-directive",
        identifiers=("artifacts_dir",),
        result_kind="agent.persist-directive",
        concurrency_keys=("agent-directive-persist:{artifacts_dir}",),
        optimistic_ui="optimistic clear wait",
    ),
    _site(
        "agent.wait.runner",
        "src/sase/ace/tui/actions/agents/_wait_actions.py",
        "_apply_live_runner_wait",
        "direct_submit_tracked",
        "agent-directive",
        "durable",
        "AgentWaitActionsMixin._apply_live_runner_wait",
        "sase agent persist-directive",
        identifiers=("artifacts_dir",),
        result_kind="agent.persist-directive",
        concurrency_keys=("agent-directive-persist:{artifacts_dir}",),
        optimistic_ui="optimistic runner wait",
    ),
    _site(
        "agent.revert.preview",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_revert_preview",
        "direct_submit_tracked",
        "revert_preview",
        "ui_only",
        "AgentRevertMixin._submit_revert_preview",
        "sase agent revert",
        identifiers=("agent_name",),
        result_kind="agent.revert-preview",
        restart_recovery="not durable; preview is session-local",
    ),
    _site(
        "agent.revert.execute",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_revert_execute",
        "direct_submit_tracked",
        "revert_agent",
        "durable",
        "AgentRevertMixin._submit_revert_execute",
        "sase agent revert",
        identifiers=("agent_name",),
        result_kind="agent.revert",
    ),
    _site(
        "agent.revert.bulk_preview",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_bulk_revert_preview",
        "direct_submit_tracked",
        "revert_preview",
        "ui_only",
        "AgentRevertMixin._submit_bulk_revert_preview",
        "sase agent revert",
        identifiers=("agent_names",),
        result_kind="agent.revert-preview",
        restart_recovery="not durable; preview is session-local",
    ),
    _site(
        "agent.revert.bulk_execute",
        "src/sase/ace/tui/actions/agents/_revert.py",
        "_submit_bulk_revert_execute",
        "direct_submit_tracked",
        "revert_agent",
        "durable",
        "AgentRevertMixin._submit_bulk_revert_execute",
        "sase agent revert",
        identifiers=("agent_names",),
        result_kind="agent.revert",
    ),
    _site(
        "bead.mutate",
        "src/sase/ace/tui/actions/_artifacts_beads_common.py",
        "_submit_beads_task",
        "direct_submit_tracked",
        "bead-*",
        "durable",
        "ArtifactsBeadsCommonMixin._submit_beads_task",
        "sase bead apply-status",
        identifiers=("bead_id", "operation"),
        result_kind="bead.status",
        concurrency_keys=("beads:{operation}:{project}:{bead_id}",),
        optimistic_ui="pane refresh",
    ),
    _site(
        "bead.issue",
        "src/sase/ace/tui/actions/_artifacts_beads_issue_mutations.py",
        "_submit_bead_issue_mutation",
        "direct_submit_tracked",
        "bead-issue-*",
        "durable",
        "ArtifactsBeadsIssueMutationsMixin._submit_bead_issue_mutation",
        "sase bead apply-status",
        identifiers=("issue_id", "operation"),
        result_kind="bead.issue",
        concurrency_keys=("beads:issue:{operation}:{project}:{issue_id}",),
    ),
    _site(
        "bead.issue_open",
        "src/sase/ace/tui/actions/_artifacts_beads_issue_actions.py",
        "_submit_beads_issue_open",
        "direct_submit_tracked",
        "bead-issue-open",
        "ui_only",
        "ArtifactsBeadsIssueActionsMixin._submit_beads_issue_open",
        "",
        identifiers=("issue_id",),
        result_kind="bead.issue-open",
        restart_recovery="not durable; browser open is session-local",
    ),
    _site(
        "notify.state",
        "src/sase/ace/tui/modals/notification_modal_action_support.py",
        "_submit_notification_state_task",
        "duck_submit",
        "notification",
        "durable",
        "NotificationActionSupportMixin._submit_notification_state_task",
        "sase notify apply-state",
        identifiers=("notification_id", "action"),
        result_kind="notify.apply-state",
        concurrency_keys=("notification-state",),
    ),
    _site(
        "notify.gate",
        "src/sase/ace/tui/actions/agents/_notification_gate_execution.py",
        "submit_gate_execution_task",
        "duck_submit",
        "notification-gate",
        "durable",
        "submit_gate_execution_task",
        "sase gate answer",
        identifiers=("request_id",),
        result_kind="gate.answer",
        concurrency_keys=("notification-gate:{id}",),
    ),
    _site(
        "notify.gate_action",
        "src/sase/ace/tui/actions/agents/_notification_gate_actions.py",
        "run_command",
        "duck_submit",
        "gate-action",
        "durable",
        "NotificationGateActionRunner.run_command",
        "sase gate act",
        identifiers=("notification_id", "operation_id"),
        result_kind="gate.act",
        concurrency_keys=("gate-action:{id}:{operation}",),
    ),
    _site(
        "notify.question",
        "src/sase/ace/tui/actions/agents/_notification_question_modal.py",
        "_submit_question_response_task",
        "duck_submit",
        "question",
        "durable",
        "_submit_question_response_task",
        "sase gate answer",
        identifiers=("request_id",),
        result_kind="question.response",
        concurrency_keys=("question-response:{id}",),
    ),
    _site(
        "notify.plan_gate",
        "src/sase/ace/tui/actions/agents/_notification_plan_gate.py",
        "submit_neutral_plan_response",
        "duck_submit",
        "plan-gate",
        "durable",
        "submit_neutral_plan_response",
        "sase gate answer",
        identifiers=("notification_id",),
        result_kind="plan.gate",
        concurrency_keys=("plan-gate:{id}",),
    ),
    _site(
        "notify.launch_approval",
        "src/sase/ace/tui/actions/agents/_notification_launch_approval.py",
        "_submit_launch_approval_task",
        "duck_submit",
        "launch",
        "durable",
        "_submit_launch_approval_task",
        "sase launch approve",
        identifiers=("request_id",),
        result_kind="launch.approval",
        concurrency_keys=("launch-approval:{id}",),
    ),
    _site(
        "notify.legacy_epic",
        "src/sase/ace/tui/actions/agents/_notification_modals.py",
        "_submit_legacy_epic_launch_task",
        "duck_submit",
        "launch",
        "durable",
        "_submit_legacy_epic_launch_task",
        "sase run",
        identifiers=("notification_id",),
        result_kind="run.launch",
        concurrency_keys=("legacy-epic-launch:{id}",),
    ),
    _site(
        "agents.sync",
        "src/sase/ace/tui/actions/agents_sync.py",
        "action_sync_agents",
        "duck_submit",
        "agents-sync",
        "durable",
        "AgentsSyncActionsMixin.action_sync_agents",
        "sase agent sync",
        identifiers=(),
        result_kind="agent.sync",
        concurrency_keys=("agents-sync",),
    ),
    _site(
        "agents.cached",
        "src/sase/ace/tui/actions/agents_sync.py",
        "action_integrate_cached_agents",
        "duck_submit",
        "agents-cached-integration",
        "durable",
        "AgentsSyncActionsMixin.action_integrate_cached_agents",
        "sase agent sync",
        identifiers=(),
        result_kind="agent.sync",
        concurrency_keys=("agents-sync",),
    ),
    _site(
        "plugin.update",
        "src/sase/ace/tui/modals/plugins_browser_update.py",
        "_submit_update_task",
        "duck_submit",
        "plugin-update",
        "durable",
        "PluginsBrowserUpdateMixin._submit_update_task",
        "sase plugin update",
        identifiers=("plugin",),
        result_kind="plugin.update",
        concurrency_keys=("plugin-update:{name}",),
    ),
    _site(
        "plugin.install",
        "src/sase/ace/tui/modals/plugins_browser_install.py",
        "_submit_install_task",
        "duck_submit",
        "plugin-install",
        "durable",
        "PluginsBrowserInstallMixin._submit_install_task",
        "sase plugin install",
        identifiers=("plugin",),
        result_kind="plugin.install",
        concurrency_keys=("plugin-install:{name}",),
    ),
    _site(
        "plugin.install_many",
        "src/sase/ace/tui/modals/plugins_browser_install.py",
        "_submit_install_many_task",
        "duck_submit",
        "plugin-install",
        "durable",
        "PluginsBrowserInstallMixin._submit_install_many_task",
        "sase plugin install",
        identifiers=("plugins",),
        result_kind="plugin.install",
        concurrency_keys=("plugin-install-many:{names}",),
    ),
    _site(
        "plugin.uninstall",
        "src/sase/ace/tui/modals/plugins_browser_uninstall.py",
        "_submit_uninstall_task",
        "duck_submit",
        "plugin-uninstall",
        "durable",
        "PluginsBrowserUninstallMixin._submit_uninstall_task",
        "sase plugin uninstall",
        identifiers=("plugin",),
        result_kind="plugin.uninstall",
        concurrency_keys=("plugin-uninstall:{name}",),
    ),
    _site(
        "plugin.mode_switch",
        "src/sase/ace/tui/modals/plugins_browser_mode_switch.py",
        "_submit_mode_switch_task",
        "duck_submit",
        "mode-switch",
        "durable",
        "PluginsBrowserModeSwitchMixin._submit_mode_switch_task",
        "sase plugin update",
        identifiers=("target_mode",),
        result_kind="plugin.mode-switch",
        concurrency_keys=("mode-switch",),
    ),
    _site(
        "plugin.sase_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_sase_update_proc",
        "duck_submit",
        "sase-update",
        "durable",
        "SaseUpdateProcMixin._submit_sase_update_proc",
        "sase update",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
    ),
    _site(
        "plugin.dev_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_dev_update_proc",
        "duck_submit",
        "dev-update",
        "durable",
        "SaseUpdateProcMixin._submit_dev_update_proc",
        "sase update",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
    ),
    _site(
        "plugin.combined_update",
        "src/sase/ace/tui/modals/plugins_browser_sase_update_procs.py",
        "_submit_combined_update_proc",
        "duck_submit",
        "sase-update",
        "durable",
        "SaseUpdateProcMixin._submit_combined_update_proc",
        "sase update",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update",),
    ),
    _site(
        "plugin.agent_cli_update",
        "src/sase/ace/tui/modals/plugins_browser_agent_clis_actions.py",
        "_submit_agent_cli_update_task",
        "duck_submit",
        "agent-cli-update",
        "durable",
        "PluginsBrowserAgentClisActionsMixin._submit_agent_cli_update_task",
        "sase agent-cli update",
        identifiers=(),
        result_kind="agent-cli.update",
        concurrency_keys=("agent-cli-update",),
    ),
    _site(
        "plugin.comprehensive",
        "src/sase/ace/tui/modals/plugins_browser_comprehensive_update.py",
        "_submit_comprehensive_update_task",
        "duck_submit",
        "comprehensive-update",
        "durable",
        "PluginsBrowserComprehensiveUpdateMixin._submit_comprehensive_update_task",
        "sase update",
        identifiers=(),
        result_kind="sase.update",
        concurrency_keys=("sase-update", "agent-cli-update", "agents-sync"),
    ),
    _site(
        "xprompt.commit",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_save_xprompt_git.py",
        "_submit_xprompt_commit_task",
        "duck_submit",
        "dynamic",
        "durable",
        "_submit_xprompt_commit_task",
        "sase stitch create",
        identifiers=("git_root", "rel_path"),
        result_kind="git.commit",
        concurrency_keys=("{noun}-commit:{git_root}:{rel_path}",),
    ),
    _site(
        "xprompt.post_write",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_save_xprompt_git.py",
        "_submit_post_write_action",
        "duck_submit",
        "dynamic",
        "durable",
        "_submit_post_write_action",
        "sase stitch create",
        identifiers=("rel_path",),
        result_kind="git.commit",
    ),
    _site(
        "config.commit",
        "src/sase/ace/tui/modals/config_commit.py",
        "submit_config_commit_task",
        "duck_submit",
        "config-commit",
        "durable",
        "submit_config_commit_task",
        "sase stitch create",
        identifiers=("git_root", "rel_path"),
        result_kind="git.commit",
        concurrency_keys=("config-commit:{git_root}:{rel_path}",),
    ),
    _site(
        "prompt.stash",
        "src/sase/ace/tui/actions/agent_workflow/_prompt_bar_stash.py",
        "_submit_prompt_stash_persist_task",
        "duck_submit",
        "prompt-stash",
        "ui_only",
        "_submit_prompt_stash_persist_task",
        "",
        identifiers=("entry_id",),
        result_kind="prompt.stash",
        restart_recovery="not a durable proc; session-local stash persist",
    ),
    _site(
        "commits.fetch",
        "src/sase/ace/tui/widgets/artifacts/commits_pane.py",
        "fetch_commits",
        "duck_submit",
        "commit-fetch",
        "ui_only",
        "CommitsPane.fetch_commits",
        "",
        identifiers=("scope",),
        result_kind="commit.fetch",
        restart_recovery="not durable; pane fetch is session-local",
    ),
)


INFRASTRUCTURE: tuple[_ProcProducerSite, ...] = (
    _site(
        "infra.submit_proc",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_submit_proc",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="legacy callable adapter",
    ),
    _site(
        "infra.submit_tracked",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_submit_tracked_proc",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="legacy callable adapter",
    ),
    _site(
        "infra.submit_durable",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_submit_durable_proc",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="decode typed result envelope from disk",
    ),
    _site(
        "infra.proc_queue",
        "src/sase/ace/tui/proc_queue.py",
        "ProcQueue",
        "definition",
        "",
        "infrastructure",
        "ProcQueue",
        "",
        restart_recovery="in-memory presentation only",
    ),
    _site(
        "infra.proc_mirror",
        "src/sase/ace/tui/proc_mirror.py",
        "ProcMirror",
        "definition",
        "",
        "infrastructure",
        "ProcMirror",
        "",
        restart_recovery="mirrors TUI rows; does not own execution",
    ),
    _site(
        "infra.worker_complete",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_on_proc_worker_completed",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="live-session callback only",
    ),
    _site(
        "infra.worker_error",
        "src/sase/ace/tui/actions/proc_actions.py",
        "_on_proc_worker_error",
        "definition",
        "",
        "infrastructure",
        "ProcActionsMixin",
        "",
        restart_recovery="live-session callback only",
    ),
)


__all__ = [
    "CallKind",
    "FoundProducerCall",
    "INFRASTRUCTURE",
    "PRODUCTION_PRODUCERS",
]
