"""SDD (Spec-Driven Development) subpackage.

Groups SDD file operations and bead initialization.
"""

from sase.sdd.beads import (
    init_beads,
    ensure_beads_initialized,
)
from sase.sdd.files import (
    dry_expand_embedded_workflows,
    ensure_bare_git_sdd_initialized,
    ensure_sdd_initialized,
    expected_sdd_directory_map,
    expected_sdd_directory_readmes,
    expected_sdd_generated_paths,
    get_primary_workspace_dir,
    commit_sdd_files,
    commit_sdd_store_files,
    expand_prompt_for_spec,
    set_prompt_qa,
    update_prompt_with_qa,
    update_spec_with_qa,
    write_sdd_readme,
    write_sdd_files,
)
from sase.sdd.store import (
    SddInitOutcome,
    SddCompanion,
    SddStore,
    SddStoreRecord,
    SddMaterializationError,
    create_and_materialize_sdd_store,
    delete_sdd_store_record,
    ensure_workspace_sdd_clone,
    ensure_sdd_kind_clone,
    materialized_sdd_clone,
    materialize_sdd_store,
    normalize_sdd_store_record,
    read_sdd_store_record,
    resolve_sdd_dir,
    resolve_sdd_kind_dir,
    resolve_sdd_store,
    write_sdd_store_record,
)

__all__ = [
    "dry_expand_embedded_workflows",
    "ensure_bare_git_sdd_initialized",
    "ensure_sdd_initialized",
    "expected_sdd_directory_map",
    "expected_sdd_directory_readmes",
    "expected_sdd_generated_paths",
    "get_primary_workspace_dir",
    "init_beads",
    "commit_sdd_files",
    "commit_sdd_store_files",
    "ensure_beads_initialized",
    "expand_prompt_for_spec",
    "set_prompt_qa",
    "update_prompt_with_qa",
    "update_spec_with_qa",
    "write_sdd_readme",
    "write_sdd_files",
    "SddInitOutcome",
    "SddCompanion",
    "SddStore",
    "SddStoreRecord",
    "SddMaterializationError",
    "create_and_materialize_sdd_store",
    "delete_sdd_store_record",
    "ensure_workspace_sdd_clone",
    "ensure_sdd_kind_clone",
    "materialized_sdd_clone",
    "materialize_sdd_store",
    "normalize_sdd_store_record",
    "read_sdd_store_record",
    "resolve_sdd_dir",
    "resolve_sdd_kind_dir",
    "resolve_sdd_store",
    "write_sdd_store_record",
]
