"""Shared loading and Rich presentation for authored SASE plans.

This compatibility module preserves the public plan-display API while the
implementation is divided into focused model, loading, and rendering modules.
"""

from __future__ import annotations

from ._plan_display_loading import (
    load_plan_display,
    plan_file_metadata_from_content,
    unavailable_plan_metadata,
)
from ._plan_display_models import (
    AuthoredPlanTier,
    PlanDisplay,
    PlanDisplayPhase,
    PlanDisplayTier,
    PlanFileMetadata,
    PlanPhaseAvailability,
)
from ._plan_display_rendering import (
    BEAD_PAGE_ROW_LABEL,
    COLOR_PLAN_EMPTY,
    COLOR_PLAN_PATH,
    COLOR_PLAN_PATH_BASENAME,
    COLOR_PLAN_PRIMARY,
    COLOR_PLAN_REASON,
    COLOR_PLAN_SUBHEADER,
    COLOR_PLAN_SUMMARY,
    PLAN_FIELD_LABEL_WIDTH,
    PLAN_MISSING_SUFFIX_STYLE,
    PLAN_PHASE_ID_STYLE,
    PLAN_PHASE_MODEL_STYLE,
    PLAN_PROVENANCE_AGENT_STYLE,
    PLAN_PROVENANCE_COMMIT_STYLE,
    PLAN_PROVENANCE_ENTRY_LIMIT,
    PLAN_SECTION_LABEL,
    PLAN_SECTION_MAX_WIDTH,
    PLAN_SIZE_ROW_LABEL,
    bead_page_url_text,
    plan_field_rows,
    plan_lane_details,
    plan_lane_header,
    plan_logical_text,
    plan_phase_logical_text,
    plan_phase_metadata,
    plan_provenance_rows,
    render_plan_document,
    render_plan_lines,
)

__all__ = [
    "AuthoredPlanTier",
    "BEAD_PAGE_ROW_LABEL",
    "COLOR_PLAN_EMPTY",
    "COLOR_PLAN_PATH",
    "COLOR_PLAN_PATH_BASENAME",
    "COLOR_PLAN_PRIMARY",
    "COLOR_PLAN_REASON",
    "COLOR_PLAN_SUBHEADER",
    "COLOR_PLAN_SUMMARY",
    "PLAN_FIELD_LABEL_WIDTH",
    "PLAN_MISSING_SUFFIX_STYLE",
    "PLAN_PHASE_ID_STYLE",
    "PLAN_PHASE_MODEL_STYLE",
    "PLAN_PROVENANCE_AGENT_STYLE",
    "PLAN_PROVENANCE_COMMIT_STYLE",
    "PLAN_PROVENANCE_ENTRY_LIMIT",
    "PLAN_SECTION_LABEL",
    "PLAN_SECTION_MAX_WIDTH",
    "PLAN_SIZE_ROW_LABEL",
    "PlanDisplay",
    "PlanDisplayPhase",
    "PlanDisplayTier",
    "PlanFileMetadata",
    "PlanPhaseAvailability",
    "bead_page_url_text",
    "load_plan_display",
    "plan_field_rows",
    "plan_file_metadata_from_content",
    "plan_lane_details",
    "plan_lane_header",
    "plan_logical_text",
    "plan_phase_logical_text",
    "plan_phase_metadata",
    "plan_provenance_rows",
    "render_plan_document",
    "render_plan_lines",
    "unavailable_plan_metadata",
]
