"""Configuration loading and domain-specific config modules.

Re-exports the public API from ``config.core`` so that existing
``from sase.config import X`` imports continue to work, plus the Config Center
backend (inventory, edit planning/execution, and write-target resolution) that
the TUI panel and any future CLI/web frontend call through.
"""

from sase.config.core import (
    CHEZMOI_HOME,
    CONFIG_DIR,
    ConfigLayer,
    DEFAULT_MAX_RUNNING_AGENTS,
    discover_machine_names,
    get_configured_max_running_agents,
    get_machine_name,
    get_max_running_agents,
    get_use_chezmoi,
    load_config_layers,
    load_merged_config,
    load_xprompts_by_source,
    load_yaml_file_with_metadata,
    require_machine_name,
)
from sase.config.runner_limit_override import (
    EffectiveRunnerLimitSnapshot,
    RunnerLimitOverrideStateError,
    TemporaryRunnerLimitOverride,
    clear_runner_limit_override,
    get_active_runner_limit_override,
    set_runner_limit_override,
    set_runner_limit_override_until,
)
from sase.config.edit import (
    AppliedResult,
    ConfigEditError,
    ConfigEditOp,
    ConfigEffectivePreview,
    ConfigWritePlan,
    EditPlanResult,
    apply_config_edit,
    plan_config_edit,
    set_key,
    unset_key,
)
from sase.config.inventory import (
    ConfigBackendError,
    ConfigConstraints,
    ConfigContribution,
    ConfigDiagnostic,
    ConfigField,
    ConfigFieldModel,
    ConfigFieldState,
    ConfigInventory,
    ConfigSource,
    build_config_inventory,
    config_field_model,
    config_schema_path,
    discover_layer_inputs,
    inventory_with_new_overlay,
    load_config_schema,
    overlay_layer_input,
)
from sase.config.targets import (
    apply_chezmoi,
    chezmoi_source_path,
    default_target_layer,
    overlay_config_path,
    resolve_write_path,
)


__all__ = [
    "CHEZMOI_HOME",
    "CONFIG_DIR",
    "AppliedResult",
    "ConfigBackendError",
    "ConfigConstraints",
    "ConfigContribution",
    "ConfigDiagnostic",
    "ConfigEditError",
    "ConfigEditOp",
    "ConfigEffectivePreview",
    "ConfigField",
    "ConfigFieldModel",
    "ConfigFieldState",
    "ConfigInventory",
    "ConfigLayer",
    "ConfigSource",
    "ConfigWritePlan",
    "DEFAULT_MAX_RUNNING_AGENTS",
    "EffectiveRunnerLimitSnapshot",
    "EditPlanResult",
    "RunnerLimitOverrideStateError",
    "TemporaryRunnerLimitOverride",
    "apply_chezmoi",
    "apply_config_edit",
    "build_config_inventory",
    "clear_runner_limit_override",
    "chezmoi_source_path",
    "config_field_model",
    "config_schema_path",
    "default_target_layer",
    "discover_layer_inputs",
    "discover_machine_names",
    "get_active_runner_limit_override",
    "get_configured_max_running_agents",
    "get_machine_name",
    "get_max_running_agents",
    "get_use_chezmoi",
    "inventory_with_new_overlay",
    "load_config_layers",
    "load_config_schema",
    "load_merged_config",
    "load_xprompts_by_source",
    "load_yaml_file_with_metadata",
    "overlay_config_path",
    "overlay_layer_input",
    "plan_config_edit",
    "resolve_write_path",
    "require_machine_name",
    "set_key",
    "set_runner_limit_override",
    "set_runner_limit_override_until",
    "unset_key",
]
