"""Constants for the unified artifact graph wire records."""

from __future__ import annotations

ARTIFACT_WIRE_SCHEMA_VERSION = 1

ARTIFACT_ROOT_ID = "/"

ARTIFACT_KIND_ROOT = "root"
ARTIFACT_KIND_FILE = "file"
ARTIFACT_KIND_DIRECTORY = "directory"
ARTIFACT_KIND_PROJECT = "project"
ARTIFACT_KIND_CHANGESPEC = "changespec"
ARTIFACT_KIND_COMMIT = "commit"
ARTIFACT_KIND_BEAD = "bead"
ARTIFACT_KIND_AGENT = "agent"
ARTIFACT_KIND_THOUGHT = "thought"
ARTIFACT_KIND_UNKNOWN = "unknown"

ARTIFACT_FILE_TYPE_METADATA_KEY = "artifact_type"
ARTIFACT_FILE_TYPE_PLAN = "plan"
ARTIFACT_FILE_TYPE_DIFF = "diff"
ARTIFACT_FILE_TYPE_CHAT = "chat"
ARTIFACT_FILE_TYPE_PROJECT = "project"
ARTIFACT_FILE_TYPE_PROMPT = "prompt"
ARTIFACT_FILE_TYPE_MISC = "misc"
ARTIFACT_FILE_TYPES = (
    ARTIFACT_FILE_TYPE_PLAN,
    ARTIFACT_FILE_TYPE_DIFF,
    ARTIFACT_FILE_TYPE_CHAT,
    ARTIFACT_FILE_TYPE_PROJECT,
    ARTIFACT_FILE_TYPE_PROMPT,
    ARTIFACT_FILE_TYPE_MISC,
)

ARTIFACT_LINK_PARENT = "parent"
ARTIFACT_LINK_CREATED = "created"
ARTIFACT_LINK_WORKER = "worker"
ARTIFACT_LINK_RELATED = "related"

ARTIFACT_PROVENANCE_MANUAL = "manual"
ARTIFACT_PROVENANCE_DERIVED = "derived"

ARTIFACT_TOMBSTONE_NODE = "node"
ARTIFACT_TOMBSTONE_LINK = "link"

ARTIFACT_STALE_CLEANUP_NONE = "none"
ARTIFACT_STALE_CLEANUP_MARK = "mark"

ARTIFACT_SOURCE_PROJECT_FILE = "project_file"
ARTIFACT_SOURCE_CHANGESPEC = "changespec"
ARTIFACT_SOURCE_COMMIT = "commit"
ARTIFACT_SOURCE_DIRECTORY = "directory"
ARTIFACT_SOURCE_BEAD_STORE = "bead_store"
ARTIFACT_SOURCE_AGENT_ARTIFACT = "agent_artifact"
ARTIFACT_SOURCE_AGENT_CREATED_FILE = "agent_created_file"
ARTIFACT_SOURCE_AGENT_THOUGHT = "agent_thought"

__all__ = [
    "ARTIFACT_FILE_TYPES",
    "ARTIFACT_FILE_TYPE_CHAT",
    "ARTIFACT_FILE_TYPE_DIFF",
    "ARTIFACT_FILE_TYPE_METADATA_KEY",
    "ARTIFACT_FILE_TYPE_MISC",
    "ARTIFACT_FILE_TYPE_PLAN",
    "ARTIFACT_FILE_TYPE_PROJECT",
    "ARTIFACT_FILE_TYPE_PROMPT",
    "ARTIFACT_KIND_AGENT",
    "ARTIFACT_KIND_BEAD",
    "ARTIFACT_KIND_CHANGESPEC",
    "ARTIFACT_KIND_COMMIT",
    "ARTIFACT_KIND_DIRECTORY",
    "ARTIFACT_KIND_FILE",
    "ARTIFACT_KIND_PROJECT",
    "ARTIFACT_KIND_ROOT",
    "ARTIFACT_KIND_THOUGHT",
    "ARTIFACT_KIND_UNKNOWN",
    "ARTIFACT_LINK_CREATED",
    "ARTIFACT_LINK_PARENT",
    "ARTIFACT_LINK_RELATED",
    "ARTIFACT_LINK_WORKER",
    "ARTIFACT_PROVENANCE_DERIVED",
    "ARTIFACT_PROVENANCE_MANUAL",
    "ARTIFACT_ROOT_ID",
    "ARTIFACT_SOURCE_AGENT_ARTIFACT",
    "ARTIFACT_SOURCE_AGENT_CREATED_FILE",
    "ARTIFACT_SOURCE_AGENT_THOUGHT",
    "ARTIFACT_SOURCE_BEAD_STORE",
    "ARTIFACT_SOURCE_CHANGESPEC",
    "ARTIFACT_SOURCE_COMMIT",
    "ARTIFACT_SOURCE_DIRECTORY",
    "ARTIFACT_SOURCE_PROJECT_FILE",
    "ARTIFACT_STALE_CLEANUP_MARK",
    "ARTIFACT_STALE_CLEANUP_NONE",
    "ARTIFACT_TOMBSTONE_LINK",
    "ARTIFACT_TOMBSTONE_NODE",
    "ARTIFACT_WIRE_SCHEMA_VERSION",
]
