"""Binding metadata for configurable ace TUI keymaps."""

# Binding metadata: (action_name, description, priority)
# Order matches the original hardcoded BINDINGS in app.py.
_BINDING_META: list[tuple[str, str, bool]] = [
    ("next_patch", "Next", False),
    ("prev_patch", "Previous", False),
    ("quit", "Quit", False),
    ("change_status", "Status", False),
    ("run_workflow", "Run", False),
    ("mail", "Mail", False),
    ("show_diff", "Diff", False),
    ("reword", "Reword", False),
    ("add_tag", "Add Tag", False),
    ("view_files", "View", False),
    ("jump_to_entry", "Jump to Entry", False),
    ("jump_to_entry_fast", "Fast Jump", False),
    ("jump_to_entry_forward", "Forward Jump", False),
    ("jump_to_all_entries", "Jump All", False),
    ("hooks_or_collapse", "Parent / Collapse or Jump Panel/Fold", False),
    (
        "hooks_or_collapse_all",
        "Collapse Selected Workflow/Family / Scoped Agent Nodes/Clans/Groups / Hint Panel Fold / Compact Tools / All",
        False,
    ),
    ("edit_hooks", "Edit Hooks", False),
    ("mark_pr_origin", "Mark PR Origin", False),
    ("start_fold_mode", "Fold", False),
    ("zoom_panel", "Zoom Detail", False),
    ("isolate_panels", "Only/Restore Panels", False),
    ("collapse_panel_folds", "Collapse/Restore Panel Folds", False),
    ("plans_approve", "Approve Plan", False),
    ("accept_proposal", "Accept", False),
    ("rebase", "Rebase", False),
    ("start_rewind", "Rewind", False),
    ("open_tmux", "Tmux", False),
    ("start_tmux_mode", "Tmux Mode", False),
    ("checkout", "Checkout", False),
    ("start_checkout_mode", "Checkout Mode", False),
    ("refresh", "Refresh", False),
    ("artifacts_copy_reference", "Copy Reference", False),
    ("sync", "Sync", False),
    ("search_forward", "Search Forward", False),
    ("edit_query", "Edit Query", False),
    ("search_reverse", "Reverse Search Order", False),
    ("open_saved_query_picker", "Saved Queries", False),
    ("start_saved_query_mode", "Saved Query Slots", False),
    ("edit_spec", "Edit Spec", False),
    ("add_axe_item", "Add AXE Item", False),
    ("toggle_axe_description", "Toggle AXE Description", False),
    ("scroll_detail_down", "Scroll Down", False),
    ("scroll_detail_up", "Scroll Up", False),
    ("scroll_prompt_down", "Scroll Prompt Down", False),
    ("scroll_prompt_up", "Scroll Prompt Up", False),
    ("next_agent_metadata_section", "Next Metadata Section", False),
    ("prev_agent_metadata_section", "Previous Metadata Section", False),
    ("next_tab", "Next Tab", True),
    ("prev_tab", "Prev Tab", True),
    ("cycle_artifacts_subtab", "Next Artifact", False),
    ("cycle_artifacts_subtab_reverse", "Previous Artifact", False),
    ("cycle_artifacts_split", "Wider Artifact List", False),
    ("cycle_artifacts_split_reverse", "Narrower Artifact List", False),
    ("files_next_version", "Next File Version", False),
    ("files_prev_version", "Previous File Version", False),
    ("pick_artifacts_project", "Project Scope", False),
    ("stitches_next", "Next Commit", False),
    ("stitches_prev", "Previous Commit", False),
    ("stitches_view_selected", "View Commit", False),
    ("stitches_filters", "Commit Filters", False),
    ("stitches_toggle_sdd", "Toggle Commit Sidecars", False),
    ("stitches_cycle_merges", "Cycle Merge Visibility", False),
    ("stitches_toggle_all_projects", "Toggle All Projects", False),
    ("stitches_fetch", "Fetch Stitches", False),
    ("plans_next", "Next Plan", False),
    ("plans_prev", "Previous Plan", False),
    ("plans_view_selected", "View Plan", False),
    ("plans_filters", "Plan Filters", False),
    ("plans_reject", "Reject Plan", False),
    ("plans_open_bead", "Go to Linked Bead", False),
    ("beads_next", "Next Bead", False),
    ("beads_prev", "Previous Bead", False),
    ("beads_view_selected", "View Bead", False),
    ("beads_filters", "Bead Filters", False),
    ("beads_expand", "Expand Epic", False),
    ("beads_collapse", "Collapse Epic", False),
    ("beads_cycle_status", "Cycle Bead Status", False),
    ("beads_edit", "Edit Bead", False),
    ("beads_add_note", "Add Bead Note", False),
    ("beads_create", "Create Task Bead", False),
    ("beads_close", "Close / Reopen Bead", False),
    ("beads_snooze", "Snooze Bead", False),
    ("beads_launch_work", "Launch Bead Work", False),
    ("beads_open_bug", "Open Linked Issue", False),
    ("start_bead_issue_mode", "Bead Issue Mode", False),
    ("beads_open_plan", "Go to Linked Plan", False),
    ("files_next", "Next Artifact File", False),
    ("files_prev", "Previous Artifact File", False),
    ("files_view_selected", "View Artifact File", False),
    ("files_open_viewer", "Open in Rich Viewer", False),
    ("files_open_external", "Open Externally", False),
    ("files_open_agent", "Open Producing Agent", False),
    ("files_filters", "Artifact File Filters", False),
    ("files_cycle_kind", "Cycle Kind Filter", False),
    ("files_copy_path", "Copy Stored Path", False),
    ("patches_filters", "Patch Filters", False),
    ("open_agent_cleanup_panel", "Agent Cleanup", False),
    ("stop_axe_and_quit", "Quit / Restart", False),
    ("start_custom_agent", "Run Agent", False),
    ("start_agent_home", "Run Agent (Home)", False),
    ("start_agent_from_patch", "Run Agent (Last VCS XPrompt)", False),
    ("start_last_vcs_xprompt_in_editor", "Edit Last VCS XPrompt", False),
    ("restore_prompt_stash", "Restore Prompt Stash", False),
    ("start_bang_mode", "Bang Mode", False),
    ("toggle_mark", "Mark", False),
    ("rename_cl", "Rename", False),
    ("clear_marks", "Unmark All", False),
    ("bulk_change_status", "Bulk Status", False),
    ("save_marked_agents", "Save Marked Agents", False),
    ("show_notifications", "Notifications", False),
    ("kill_agent", "Kill", False),
    ("expand_or_layout", "Expand / Enter Panel", False),
    ("expand_all_folds", "Tribe Folds / Expand All", False),
    ("toggle_layout", "Layout", False),
    ("toggle_thinking", "Tools", False),
    ("toggle_thinking_reverse", "Tools Rev", False),
    ("copy_tab_content", "Copy", False),
    ("scroll_to_top", "Top", False),
    ("scroll_to_bottom", "Bottom", False),
    ("open_config_center", "SASE Admin Center", False),
    ("show_help", "Help", False),
    ("prev_query", "Prev Query", False),
    ("next_query", "Next Query", False),
    ("start_ancestor_mode", "Ancestor", False),
    ("start_child_mode", "Child", False),
    ("start_sibling_mode", "Sibling", False),
    ("toggle_relation_panel", "Relations Panel", False),
    ("toggle_hide_reverted", "Toggle Reverted", False),
    ("patches_toggle_reverted", "Toggle Reverted", False),
    ("toggle_hide_submitted", "Toggle Submitted", False),
    ("start_leader_mode", "Leader", False),
    ("next_agent_file", "Next File", False),
    ("prev_agent_file", "Prev File", False),
    ("edit_panel", "Edit Panel", False),
    ("jump_to_agent_patch", "Go to Patch", False),
    ("open_artifact_files", "Artifact Files", False),
    ("toggle_attempt_view", "Toggle Attempt View", False),
    ("toggle_agent_unread", "Toggle Agent Unread", False),
    ("edit_agent_tribe", "Edit Agent Tribe", False),
    ("focus_next_agent_panel", "Next Panel", False),
    ("focus_prev_agent_panel", "Prev Panel", False),
    ("cycle_grouping_mode", "Cycle Grouping", False),
    ("cycle_grouping_mode_reverse", "Cycle Grouping Rev", False),
    ("show_agent_run_log", "Agent Run Log", False),
    ("open_command_palette", "Command Palette", False),
    ("dismiss_toasts", "Dismiss Toasts", False),
]

# Scoped bindings owned by the focused Admin Center Statistics pane. These
# are deliberately excluded from ``AppKeymaps`` so common keys such as ``t``
# and ``r`` never become globally active.
_STATISTICS_BINDING_META: tuple[tuple[str, str], ...] = (
    ("prev_view", "Previous View"),
    ("next_view", "Next View"),
    ("select_view", "Select View by Number"),
    ("jump_to_entry", "Jump"),
    ("cycle_range", "Time Range"),
    ("cycle_range_reverse", "Previous Time Range"),
    ("custom_range", "Custom Range"),
    ("cycle_group", "Group By"),
    ("cycle_project_filter", "Project Filter"),
    ("cycle_project_filter_reverse", "Previous Project Filter"),
    ("focus_xprompt", "Focus XPrompt"),
    ("clear_xprompt_focus", "Clear XPrompt Focus"),
    ("scroll_down", "Scroll Down"),
    ("scroll_up", "Scroll Up"),
    ("refresh", "Refresh"),
    ("help", "Help"),
)

# Scoped bindings owned by the focused Admin Center Projects pane. Each entry
# is (dataclass field, Textual action name, description); the field and
# action names diverge only for ``reload``, whose configured key drives
# ``action_reload_projects`` on the list sub-tab and a same-named field on the
# Repos/Workspaces inventory panes drives their own ``action_reload_inventory``.
_PROJECTS_BINDING_META: tuple[tuple[str, str, str], ...] = (
    ("next_option", "next_option", "Next"),
    ("prev_option", "prev_option", "Previous"),
    ("focus_filter", "focus_filter", "Filter"),
    ("cycle_subtab", "cycle_subtab", "Next Sub-tab"),
    ("cycle_subtab_reverse", "cycle_subtab_reverse", "Previous Sub-tab"),
    ("toggle_project_mark", "toggle_project_mark", "Mark"),
    ("clear_project_marks", "clear_project_marks", "Unmark All"),
    ("edit_project_spec", "edit_project_spec", "Edit"),
    ("edit_project_aliases", "edit_project_aliases", "Aliases"),
    ("enable_project", "enable_project", "Enable"),
    ("disable_project", "disable_project", "Disable"),
    ("delete_project", "delete_project", "Delete"),
    ("force_current_state_change", "force_current_state_change", "Force"),
    ("default_project_action", "default_project_action", "Default"),
    ("reload", "reload_projects", "Reload"),
    ("show_project_repos", "show_project_repos", "Project Repos"),
    ("show_project_workspaces", "show_project_workspaces", "Project Workspaces"),
    ("jump_to_entry", "jump_to_entry", "Jump"),
    ("set_current_project", "set_current_project", "Set Current"),
)

# Scoped bindings owned by the Repos/Workspaces Projects-tab inventory panes.
# ``reload`` maps to ``action_reload_inventory`` here, not
# ``action_reload_projects`` -- see ``_PROJECTS_BINDING_META`` above.
_PROJECTS_INVENTORY_BINDING_META: tuple[tuple[str, str, str], ...] = (
    ("next_option", "next_option", "Next"),
    ("prev_option", "prev_option", "Previous"),
    ("focus_filter", "focus_filter", "Filter"),
    ("pick_project", "pick_project", "Pick Project"),
    ("reload", "reload_inventory", "Reload"),
    ("jump_to_entry", "jump_to_entry", "Jump"),
    ("clear_project_filter", "clear_project_filter", "Clear Project"),
)

# Shared bindings owned by the branch renderer inside gate-review modals.
# ``next_input`` / ``previous_input`` live on the input panel, not the gate
# modal, so they are omitted here and bound by ``build_gate_input_panel_bindings``.
_GATE_BINDING_META: tuple[tuple[str, str], ...] = (
    ("next_control", "Next control"),
    ("previous_control", "Previous control"),
    ("toggle_option", "Toggle option"),
    ("submit_primary", "Submit primary"),
    ("submit_branch", "Submit"),
    ("open_inputs", "Open inputs"),
)

# Focus-ring bindings owned by ``GateInputPanel``.
_GATE_INPUT_PANEL_BINDING_META: tuple[tuple[str, str], ...] = (
    ("next_input", "Next input"),
    ("previous_input", "Previous input"),
)

# Scoped bindings owned by the Glossary panel. These are deliberately
# excluded from ``AppKeymaps`` so common keys such as ``j``/``k``/``p`` never
# become globally active.
_GLOSSARY_BINDING_META: tuple[tuple[str, str], ...] = (
    ("next_term", "Next Term"),
    ("prev_term", "Previous Term"),
    ("first_term", "First Term"),
    ("last_term", "Last Term"),
    ("scroll_definition_down", "Scroll Definition Down"),
    ("scroll_definition_up", "Scroll Definition Up"),
    ("filter_terms", "Filter"),
    ("toggle_definition_filter", "Toggle Definition Match"),
    ("next_relation", "Next Relation Chip"),
    ("prev_relation", "Previous Relation Chip"),
    ("follow_relation", "Follow Relation"),
    ("travel_back", "Travel Back"),
    ("next_project", "Next Project"),
    ("prev_project", "Previous Project"),
    ("add_term", "Add Term"),
    ("delete_term", "Delete Term"),
    ("open_source", "Open in Editor"),
    ("open_viewer", "Open in Viewer"),
    ("copy_definition", "Copy Definition"),
    ("copy_source_path", "Copy Source Path"),
    ("refresh", "Refresh"),
    ("help", "Help"),
)

# Maps mode name -> the app-level action that activates it.
_MODE_PREFIX_ACTIONS: dict[str, str] = {
    "fold_mode": "start_fold_mode",
    "copy_mode": "copy_tab_content",
    "leader_mode": "start_leader_mode",
    "bang_mode": "start_bang_mode",
    "bead_issue_mode": "start_bead_issue_mode",
}
