"""Python lifecycle glue for the local SASE daemon."""

from __future__ import annotations

import signal

from sase.integrations._daemon_lifecycle_facade_actions import (
    repair_stale_lock_facade as _repair_stale_lock,
    run_daemon_backup_facade as _run_daemon_backup,
    run_daemon_checkpoint_facade as _run_daemon_checkpoint,
    run_daemon_diff_facade as _run_daemon_diff,
    run_daemon_list_backups_facade as _run_daemon_list_backups,
    run_daemon_rebuild_facade as _run_daemon_rebuild,
    run_daemon_restore_facade as _run_daemon_restore,
    run_daemon_start_facade as _run_daemon_start,
    run_daemon_stop_facade as _run_daemon_stop,
    run_daemon_verify_facade as _run_daemon_verify,
    wait_for_background_start_facade as _wait_for_background_start,
)
from sase.integrations._daemon_lifecycle_facade_cli import (
    handle_daemon_backup,
    handle_daemon_checkpoint,
    handle_daemon_diff,
    handle_daemon_doctor,
    handle_daemon_list_backups,
    handle_daemon_rebuild,
    handle_daemon_restore,
    handle_daemon_rollout,
    handle_daemon_scheduler,
    handle_daemon_start,
    handle_daemon_status,
    handle_daemon_stop,
    handle_daemon_verify,
)
from sase.integrations._daemon_lifecycle_facade_config import (
    host_identity_from_env_facade as _host_identity_from_env,
    load_daemon_config_facade as _load_daemon_config,
    prepare_daemon_launch_facade as _prepare_daemon_launch,
    resolve_gateway_command_facade as _resolve_gateway_command,
    runtime_paths_from_args_facade as _runtime_paths_from_args,
)
from sase.integrations._daemon_lifecycle_facade_inspection import (
    doctor_payload_facade as _doctor_payload,
    executable_matches_metadata_facade as _executable_matches_metadata,
    inspect_daemon_facade as _inspect_daemon,
    inspection_to_dict_facade as _inspection_to_dict,
    print_status_facade as _print_status,
    process_is_live_facade as _process_is_live,
    read_metadata_facade as _read_metadata,
    terminate_process_facade as _terminate_process,
    try_health_rpc_facade as _try_health_rpc,
)
from sase.integrations._daemon_lifecycle_public import (
    DEFAULT_STARTUP_TIMEOUT_SECONDS,
    DEFAULT_STOP_TIMEOUT_SECONDS,
    LOCK_FILENAME,
    LOCK_METADATA_FILENAME,
    LOCK_SCHEMA_VERSION,
    SOCKET_FILENAME,
    KillFn,
    PopenFactory,
    SleepFn,
    command_value as _command_value,
    DaemonInspection as _DaemonInspection,
    DaemonLaunch as _DaemonLaunch,
    DaemonLifecycleConfig as _DaemonLifecycleConfig,
    DaemonLifecycleError as _DaemonLifecycleError,
    DaemonRuntimePaths as _DaemonRuntimePaths,
    int_value as _int_value,
    optional_path as _optional_path,
    positive_float as _positive_float,
)

__all__ = [
    "DEFAULT_STARTUP_TIMEOUT_SECONDS",
    "DEFAULT_STOP_TIMEOUT_SECONDS",
    "LOCK_FILENAME",
    "LOCK_METADATA_FILENAME",
    "LOCK_SCHEMA_VERSION",
    "SOCKET_FILENAME",
    "KillFn",
    "PopenFactory",
    "SleepFn",
    "_DaemonInspection",
    "_DaemonLaunch",
    "_DaemonLifecycleConfig",
    "_DaemonLifecycleError",
    "_DaemonRuntimePaths",
    "_command_value",
    "_doctor_payload",
    "_executable_matches_metadata",
    "_host_identity_from_env",
    "_inspect_daemon",
    "_inspection_to_dict",
    "_int_value",
    "_load_daemon_config",
    "_optional_path",
    "_positive_float",
    "_prepare_daemon_launch",
    "_print_status",
    "_process_is_live",
    "_read_metadata",
    "_resolve_gateway_command",
    "_repair_stale_lock",
    "_run_daemon_backup",
    "_run_daemon_checkpoint",
    "_run_daemon_diff",
    "_run_daemon_list_backups",
    "_run_daemon_rebuild",
    "_run_daemon_restore",
    "_run_daemon_start",
    "_run_daemon_stop",
    "_run_daemon_verify",
    "_runtime_paths_from_args",
    "_terminate_process",
    "_try_health_rpc",
    "_wait_for_background_start",
    "handle_daemon_backup",
    "handle_daemon_checkpoint",
    "handle_daemon_diff",
    "handle_daemon_doctor",
    "handle_daemon_list_backups",
    "handle_daemon_rebuild",
    "handle_daemon_restore",
    "handle_daemon_rollout",
    "handle_daemon_scheduler",
    "handle_daemon_start",
    "handle_daemon_status",
    "handle_daemon_stop",
    "handle_daemon_verify",
    "signal",
]
