"""Navigation, tab, and artifact-pane app-command metadata.

Split out of ``_app_metadata.py`` to keep each module under the 500-line cap.
"""

from __future__ import annotations

from sase.ace.tui.commands._tabs import (
    AGENTS_AXE,
    AGENTS_ONLY,
    ALL_TABS,
    CL_ONLY,
)
from sase.ace.tui.commands.types import AppCommandMeta

NAV_COMMAND_META: tuple[AppCommandMeta, ...] = (
    # Navigation
    ("next_patch", "Next entry", "Navigation", ALL_TABS, ("down", "j")),
    ("prev_patch", "Previous entry", "Navigation", ALL_TABS, ("up", "k")),
    ("scroll_to_top", "Scroll to top", "Navigation", ALL_TABS, ("g",)),
    ("scroll_to_bottom", "Scroll to bottom", "Navigation", ALL_TABS, ("G",)),
    ("scroll_detail_down", "Scroll detail down", "Navigation", ALL_TABS, ()),
    ("scroll_detail_up", "Scroll detail up", "Navigation", ALL_TABS, ()),
    ("scroll_prompt_down", "Scroll prompt down", "Navigation", AGENTS_ONLY, ()),
    ("scroll_prompt_up", "Scroll prompt up", "Navigation", AGENTS_ONLY, ()),
    (
        "next_agent_metadata_section",
        "Next metadata section",
        "Navigation",
        AGENTS_ONLY,
        ("section", "heading", "ctrl+j"),
    ),
    (
        "prev_agent_metadata_section",
        "Previous metadata section",
        "Navigation",
        AGENTS_ONLY,
        ("section", "heading", "ctrl+k"),
    ),
    ("next_agent_file", "Next file / chop run", "Navigation", AGENTS_AXE, ()),
    ("prev_agent_file", "Previous file / chop run", "Navigation", AGENTS_AXE, ()),
    ("jump_to_entry", "Jump to entry", "Navigation", ALL_TABS, ("hint",)),
    (
        "jump_to_entry_fast",
        "Fast jump to entry",
        "Navigation",
        ALL_TABS,
        ("jump", "first", "back", "ctrl+o"),
    ),
    (
        "jump_to_entry_forward",
        "Jump forward through jump stack",
        "Navigation",
        ALL_TABS,
        ("jump", "forward", "ctrl+shift+o"),
    ),
    ("jump_to_all_entries", "Jump to any entry", "Navigation", ALL_TABS, ("hint",)),
    (
        "follow_artifact_link",
        "Follow artifact link",
        "Navigation",
        ALL_TABS,
        ("link", "links", "$"),
    ),
    # Tab switching
    ("next_tab", "Next tab", "Tabs", ALL_TABS, ()),
    ("prev_tab", "Previous tab", "Tabs", ALL_TABS, ()),
    (
        "cycle_artifacts_subtab",
        "Next Artifacts sub-tab",
        "Tabs",
        CL_ONLY,
        ("next artifact", "stitches", "commits", "beads", "files"),
    ),
    (
        "cycle_artifacts_subtab_reverse",
        "Previous Artifacts sub-tab",
        "Tabs",
        CL_ONLY,
        ("previous artifact",),
    ),
    (
        "cycle_artifacts_split",
        "Widen Artifacts list panel",
        "Display",
        CL_ONLY,
        ("split", "pane width", "wider list"),
    ),
    (
        "cycle_artifacts_split_reverse",
        "Narrow Artifacts list panel",
        "Display",
        CL_ONLY,
        ("split", "pane width", "narrower list"),
    ),
    (
        "cycle_artifacts_description",
        "Cycle Artifacts pane description",
        "Display",
        CL_ONLY,
        ("description", "brief", "off", "summary", "full"),
    ),
    ("files_next_version", "Files: next version", "Navigation", CL_ONLY, ()),
    ("files_prev_version", "Files: previous version", "Navigation", CL_ONLY, ()),
    (
        "pick_artifacts_project",
        "Pick Artifacts project scope (seeds current)",
        "Tabs",
        CL_ONLY,
        ("project scope", "filter project", "current project", "seeded"),
    ),
    (
        "artifacts_load_more",
        "Artifacts: load more rows",
        "Navigation",
        CL_ONLY,
        ("load more", "page size", "limit", "ctrl+j"),
    ),
    (
        "artifacts_unload",
        "Artifacts: unload a page of rows",
        "Navigation",
        CL_ONLY,
        ("unload", "page size", "limit", "ctrl+k"),
    ),
    # Stitches sub-tab
    (
        "stitches_next",
        "Stitches: next row",
        "Navigation",
        CL_ONLY,
        ("commit down", "stitches down"),
    ),
    (
        "stitches_prev",
        "Stitches: previous row",
        "Navigation",
        CL_ONLY,
        ("commit up", "stitches up"),
    ),
    ("stitches_view_selected", "Stitches: view selected", "Display", CL_ONLY, ()),
    ("stitches_filters", "Stitches: filter bar", "Display", CL_ONLY, ()),
    (
        "stitches_toggle_sdd",
        "Stitches: toggle sidecar history",
        "Display",
        CL_ONLY,
        (),
    ),
    (
        "stitches_cycle_merges",
        "Stitches: cycle merge visibility",
        "Display",
        CL_ONLY,
        (),
    ),
    (
        "stitches_toggle_all_projects",
        "Stitches: toggle all projects",
        "Display",
        CL_ONLY,
        (),
    ),
    (
        "stitches_fetch",
        "Stitches: fetch remote refs",
        "Proposals & Sync",
        CL_ONLY,
        (),
    ),
    # Plans sub-tab
    ("plans_next", "Plans: next row", "Navigation", CL_ONLY, ("plan down",)),
    ("plans_prev", "Plans: previous row", "Navigation", CL_ONLY, ("plan up",)),
    ("plans_view_selected", "Plans: view selected", "Display", CL_ONLY, ()),
    ("plans_filters", "Plans: filter bar", "Display", CL_ONLY, ()),
    (
        "plans_approve",
        "Plans: approve proposal",
        "Proposals & Sync",
        CL_ONLY,
        ("approve plan",),
    ),
    (
        "plans_reject",
        "Plans: reject proposal",
        "Proposals & Sync",
        CL_ONLY,
        ("reject plan",),
    ),
    # Beads sub-tab
    ("beads_next", "Beads: next row", "Navigation", CL_ONLY, ()),
    ("beads_prev", "Beads: previous row", "Navigation", CL_ONLY, ()),
    ("beads_view_selected", "Beads: view selected", "Display", CL_ONLY, ()),
    ("beads_filters", "Beads: filter bar", "Display", CL_ONLY, ()),
    ("beads_expand", "Beads: expand epic", "Folding", CL_ONLY, ()),
    ("beads_collapse", "Beads: collapse epic", "Folding", CL_ONLY, ()),
    ("beads_cycle_status", "Beads: cycle status", "Proposals & Sync", CL_ONLY, ()),
    ("beads_edit", "Beads: edit", "Proposals & Sync", CL_ONLY, ()),
    ("beads_add_note", "Beads: add note", "Proposals & Sync", CL_ONLY, ()),
    ("beads_create", "Beads: create task", "Proposals & Sync", CL_ONLY, ()),
    ("beads_close", "Beads: close or reopen", "Proposals & Sync", CL_ONLY, ()),
    ("beads_snooze", "Beads: snooze task", "Proposals & Sync", CL_ONLY, ()),
    ("beads_launch_work", "Beads: launch work", "Agents", CL_ONLY, ()),
    ("beads_open_bug", "Beads: open linked issue", "Display", CL_ONLY, ()),
    ("start_bead_issue_mode", "Beads: issue actions", "Bugs", CL_ONLY, ()),
    # Files sub-tab
    ("files_next", "Files: next row", "Navigation", CL_ONLY, ("file down",)),
    ("files_prev", "Files: previous row", "Navigation", CL_ONLY, ("file up",)),
    ("files_view_selected", "Files: view selected", "Display", CL_ONLY, ()),
    ("files_open_viewer", "Files: open in rich viewer", "Display", CL_ONLY, ()),
    ("files_open_external", "Files: open externally", "Display", CL_ONLY, ()),
    ("files_open_agent", "Files: open producing agent", "Agents", CL_ONLY, ()),
    ("files_filters", "Files: filter bar", "Display", CL_ONLY, ()),
    (
        "files_cycle_kind",
        "Files: cycle kind filter",
        "Proposals & Sync",
        CL_ONLY,
        (),
    ),
    ("files_copy_path", "Files: copy stored path", "Display", CL_ONLY, ()),
    # Agents sub-tab
    ("agents_next", "Agents: next row", "Navigation", CL_ONLY, ("agent down",)),
    ("agents_prev", "Agents: previous row", "Navigation", CL_ONLY, ("agent up",)),
    (
        "cycle_agents_subtab",
        "Agents: next Focus/Fleet mode",
        "Tabs",
        AGENTS_ONLY,
        ("fleet", "focus", "remote agents"),
    ),
    (
        "cycle_agents_subtab_reverse",
        "Agents: previous Focus/Fleet mode",
        "Tabs",
        AGENTS_ONLY,
        ("fleet", "focus", "remote agents"),
    ),
    (
        "toggle_agent_follow",
        "Agents: follow or unfollow remote row",
        "Agents",
        AGENTS_ONLY,
        ("follow", "unfollow", "remote"),
    ),
    (
        "view_agent_in_focus",
        "Agents: view followed remote row in Focus",
        "Agents",
        AGENTS_ONLY,
        ("focus", "followed", "remote"),
    ),
    (
        "connect_agent_machine",
        "Agents: show remote machine status",
        "Agents",
        AGENTS_ONLY,
        ("machine", "remote", "connection"),
    ),
)
