"""Modal dialogs for the ace TUI."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .add_xprompt_modal import AddXPromptModal as AddXPromptModal
    from .axe_add_modals import (
        validate_axe_new_entry_identity as validate_axe_new_entry_identity,
    )
    from .command_input_modal import CommandInputModal as CommandInputModal
    from .config_transaction import (
        ConfigTransactionConflict as ConfigTransactionConflict,
    )
    from .input_item_modal import InputItemModal as InputItemModal
    from .local_xprompt_name_modal import LocalXPromptNameModal as LocalXPromptNameModal
    from .memory_panel import MemoryPanel as MemoryPanel
    from .mini_xprompt_name_modal import (
        MiniXPromptNameModal as MiniXPromptNameModal,
    )
    from .mini_xprompt_name_modal import (
        MiniXPromptNameResult as MiniXPromptNameResult,
    )
    from .mini_xprompt_save_confirm_modal import (
        MiniXPromptSaveConfirmModal as MiniXPromptSaveConfirmModal,
    )
    from .mini_xprompt_save_confirm_modal import (
        MiniXPromptSaveConfirmState as MiniXPromptSaveConfirmState,
    )
    from .project_select_modal import ProjectSelectModal as ProjectSelectModal
    from .schema_object_form import SchemaFieldDiagnostic as SchemaFieldDiagnostic
    from .snippet_name_modal import SnippetNameModal as SnippetNameModal
    from .snippet_name_modal import SnippetNameResult as SnippetNameResult
    from .snippet_save_confirm_modal import (
        SnippetSaveConfirmModal as SnippetSaveConfirmModal,
    )
    from .snippet_save_confirm_modal import (
        SnippetSaveConfirmState as SnippetSaveConfirmState,
    )
    from .snippets_panel import SnippetsPanel as SnippetsPanel
    from .xprompt_item_modal import XPromptItemModal as XPromptItemModal

_LAZY_EXPORTS = {
    "AddPropertyModal": (".add_property_modal", "AddPropertyModal"),
    "AddXPromptModal": (".add_xprompt_modal", "AddXPromptModal"),
    "AddableProperty": (".add_property_modal", "AddableProperty"),
    "AgentCleanupAction": (".agent_cleanup_modal", "AgentCleanupAction"),
    "AgentCleanupClanKey": (".agent_cleanup_modal", "AgentCleanupClanKey"),
    "AgentCleanupClanModal": (".agent_cleanup_modal", "AgentCleanupClanModal"),
    "AgentCleanupClanResult": (".agent_cleanup_modal", "AgentCleanupClanResult"),
    "AgentCleanupCustomModal": (".agent_cleanup_modal", "AgentCleanupCustomModal"),
    "AgentCleanupCustomResult": (".agent_cleanup_modal", "AgentCleanupCustomResult"),
    "AgentCleanupModal": (".agent_cleanup_modal", "AgentCleanupModal"),
    "AgentCleanupPanelState": (".agent_cleanup_modal", "AgentCleanupPanelState"),
    "AgentCleanupResult": (".agent_cleanup_modal", "AgentCleanupResult"),
    "AgentCleanupTribeModal": (".agent_cleanup_modal", "AgentCleanupTribeModal"),
    "AgentCleanupTribeResult": (".agent_cleanup_modal", "AgentCleanupTribeResult"),
    "AgentNameModal": (".agent_name_modal", "AgentNameModal"),
    "AgentNeighborChoice": (".agent_neighbor_modal", "AgentNeighborChoice"),
    "AgentNeighborModal": (".agent_neighbor_modal", "AgentNeighborModal"),
    "AgentRunLogModal": (".agent_run_log_modal", "AgentRunLogModal"),
    "AgentTribeModal": (".agent_tribe_modal", "AgentTribeModal"),
    "AgentTribeModalResult": (".agent_tribe_modal", "AgentTribeModalResult"),
    "AgentWorkspaceTmuxChoice": (
        ".agent_workspace_tmux_modal",
        "AgentWorkspaceTmuxChoice",
    ),
    "AgentWorkspaceTmuxModal": (
        ".agent_workspace_tmux_modal",
        "AgentWorkspaceTmuxModal",
    ),
    "AliasEditPreviewModal": (".models_panel_edit", "AliasEditPreviewModal"),
    "ApproveOptionsEditPrompt": (
        ".approve_options_modal",
        "ApproveOptionsEditPrompt",
    ),
    "ApproveOptionsModal": (".approve_options_modal", "ApproveOptionsModal"),
    "ApproveOptionsResult": (".approve_options_modal", "ApproveOptionsResult"),
    "ArtifactFileSelectionModal": (
        ".artifact_files_modal",
        "ArtifactFileSelectionModal",
    ),
    "ArtifactFileSelectionResult": (
        ".artifact_files_modal",
        "ArtifactFileSelectionResult",
    ),
    "AutoApproveChoice": (".auto_approve_modal", "AutoApproveChoice"),
    "AutoApproveModal": (".auto_approve_modal", "AutoApproveModal"),
    "AxeAddChooserModal": (".axe_add_modals", "AxeAddChooserModal"),
    "AxeAddKind": (".axe_add_modals", "AxeAddKind"),
    "AxeEntryEditorModal": (".axe_entry_editor_modal", "AxeEntryEditorModal"),
    "AxeEntryEditorResult": (".axe_entry_editor_modal", "AxeEntryEditorResult"),
    "AxeEntryEditorSeed": (".axe_entry_editor_modal", "AxeEntryEditorSeed"),
    "AxeEntryIdentity": (".axe_entry_editor_modal", "AxeEntryIdentity"),
    "AxeEntryKind": (".axe_entry_editor_modal", "AxeEntryKind"),
    "AxeEntryMutationRequest": (
        ".axe_entry_editor_modal",
        "AxeEntryMutationRequest",
    ),
    "AxeLumberjackPickerModal": (".axe_add_modals", "AxeLumberjackPickerModal"),
    "AxeNewEntryDraft": (".axe_add_modals", "AxeNewEntryDraft"),
    "AxeNewEntryIdentityModal": (".axe_add_modals", "AxeNewEntryIdentityModal"),
    "AxeScriptChoice": (".axe_add_modals", "AxeScriptChoice"),
    "AxeScriptPickerModal": (".axe_add_modals", "AxeScriptPickerModal"),
    "AxeWritableScope": (".axe_entry_editor_modal", "AxeWritableScope"),
    "BackgroundProcEntry": (".runners_modal", "BackgroundProcEntry"),
    "BeadCloseModal": (".bead_close_modal", "BeadCloseModal"),
    "BeadCloseResult": (".bead_close_modal", "BeadCloseResult"),
    "BeadCreateModal": (".bead_create_modal", "BeadCreateModal"),
    "BeadCreateResult": (".bead_create_modal", "BeadCreateResult"),
    "BeadEditModal": (".bead_edit_modal", "BeadEditModal"),
    "BeadEditResult": (".bead_edit_modal", "BeadEditResult"),
    "BeadEditorModal": (".bead_editor_modal", "BeadEditorModal"),
    "BeadEditorResult": (".bead_editor_modal", "BeadEditorResult"),
    "BeadNoteModal": (".bead_note_modal", "BeadNoteModal"),
    "CommandHistoryModal": (".command_history_modal", "CommandHistoryModal"),
    "CommandInputModal": (".command_input_modal", "CommandInputModal"),
    "CommandPaletteModal": (".command_palette_modal", "CommandPaletteModal"),
    "CommitViewModal": (".commit_view_modal", "CommitViewModal"),
    "ConfigCenterModal": (".config_center_modal", "ConfigCenterModal"),
    "ConfigHubEntry": (".config_hub_session", "ConfigHubEntry"),
    "ConfigHubPane": (".config_hub_pane", "ConfigHubPane"),
    "ConfigHubSessionState": (".config_hub_session", "ConfigHubSessionState"),
    "ConfigTransactionApplyResult": (
        ".config_transaction",
        "ConfigTransactionApplyResult",
    ),
    "ConfigTransactionConflict": (".config_transaction", "ConfigTransactionConflict"),
    "ConfigTransactionMetadata": (".config_transaction", "ConfigTransactionMetadata"),
    "ConfigTransactionPreview": (
        ".config_transaction_preview",
        "ConfigTransactionPreview",
    ),
    "ConfigTransactionRequest": (".config_transaction", "ConfigTransactionRequest"),
    "ConfirmActionModal": (".confirm_action_modal", "ConfirmActionModal"),
    "ConfirmDeleteModal": (".confirm_delete_modal", "ConfirmDeleteModal"),
    "ConfirmDialog": (".confirm_dialog", "ConfirmDialog"),
    "ConfirmDismissAllModal": (".confirm_kill_modal", "ConfirmDismissAllModal"),
    "ConfirmKind": (".confirm_dialog", "ConfirmKind"),
    "ConfirmKillAllModal": (".confirm_kill_modal", "ConfirmKillAllModal"),
    "ConfirmKillModal": (".confirm_kill_modal", "ConfirmKillModal"),
    "ConfirmKillProcShellModal": (
        ".confirm_kill_modal",
        "ConfirmKillProcShellModal",
    ),
    "ConfirmRerunModal": (".confirm_rerun_modal", "ConfirmRerunModal"),
    "ConfirmRevertAgentModal": (
        ".confirm_revert_agent_modal",
        "ConfirmRevertAgentModal",
    ),
    "ConfirmStopMonitorModal": (".confirm_kill_modal", "ConfirmStopMonitorModal"),
    "CopyAsContext": (".copy_as_types", "CopyAsContext"),
    "CopyAsModal": (".copy_as_modal", "CopyAsModal"),
    "CopyAsRow": (".copy_as_types", "CopyAsRow"),
    "CustomApprovalEditPrompt": (
        ".approve_options_modal",
        "CustomApprovalEditPrompt",
    ),
    "CustomApprovalModal": (".approve_options_modal", "CustomApprovalModal"),
    "CustomApprovalResult": (".approve_options_modal", "CustomApprovalResult"),
    "CustomGateModal": (".custom_gate_modal", "CustomGateModal"),
    "CustomGateModalData": (".custom_gate_modal", "CustomGateModalData"),
    "CustomGateModalResult": (".custom_gate_modal", "CustomGateModalResult"),
    "CustomModelInputModal": (".custom_model_input_modal", "CustomModelInputModal"),
    "DisabledProviderLaunchDecision": (
        ".disabled_provider_launch_modal",
        "DisabledProviderLaunchDecision",
    ),
    "DisabledProviderLaunchModal": (
        ".disabled_provider_launch_modal",
        "DisabledProviderLaunchModal",
    ),
    "ProviderDrainPromptDecision": (
        ".provider_drain_prompt_modal",
        "ProviderDrainPromptDecision",
    ),
    "ProviderDrainPromptModal": (
        ".provider_drain_prompt_modal",
        "ProviderDrainPromptModal",
    ),
    "DismissedAgentSelectModal": (".revive_agent_modal", "DismissedAgentSelectModal"),
    "GateActionControls": (".gate_action_controls", "GateActionControls"),
    "GateActionOutputModal": (".gate_action_output_modal", "GateActionOutputModal"),
    "GateActionRunner": (".gate_action_runner", "GateActionRunner"),
    "GateActionsData": (".gate_action_controls", "GateActionsData"),
    "GateBranchControls": (".gate_branch_controls", "GateBranchControls"),
    "GateBranchData": (".gate_branch_controls", "GateBranchData"),
    "GateCommandOutcome": (".gate_action_runner", "GateCommandOutcome"),
    "GateDebugModal": (".gate_debug_modal", "GateDebugModal"),
    "GateEditOutcome": (".gate_action_runner", "GateEditOutcome"),
    "GateInputPanel": (".gate_input_panel", "GateInputPanel"),
    "GateInputPanelResult": (".gate_input_panel", "GateInputPanelResult"),
    "GateInputRequest": (".gate_input_panel_model", "GateInputRequest"),
    "GateRetryModal": (".gate_retry_modal", "GateRetryModal"),
    "HelpModal": (".help_modal", "HelpModal"),
    "HookHistoryAction": (".hook_history_modal", "HookHistoryAction"),
    "HookHistoryModal": (".hook_history_modal", "HookHistoryModal"),
    "HookHistoryResult": (".hook_history_modal", "HookHistoryResult"),
    "InputCollectionModal": (".input_collection_modal", "InputCollectionModal"),
    "InputItemModal": (".input_item_modal", "InputItemModal"),
    "InventoryProjectChoice": (".inventory_project_picker", "InventoryProjectChoice"),
    "InventoryProjectPicker": (".inventory_project_picker", "InventoryProjectPicker"),
    "InventoryProjectPickerResult": (
        ".inventory_project_picker",
        "InventoryProjectPickerResult",
    ),
    "IssueEditModal": (".issue_edit_modal", "IssueEditModal"),
    "IssueEditResult": (".issue_edit_modal", "IssueEditResult"),
    "JumpActionModal": (".jump_action_modal", "JumpActionModal"),
    "JumpAllModal": (".jump_all_modal", "JumpAllModal"),
    "JumpAllResult": (".jump_all_modal", "JumpAllResult"),
    "JumpChoice": (".jump_action_modal", "JumpChoice"),
    "LaunchApprovalModal": (".launch_approval_modal", "LaunchApprovalModal"),
    "LaunchApprovalResult": (".launch_approval_modal", "LaunchApprovalResult"),
    "LocalXPromptNameModal": (".local_xprompt_name_modal", "LocalXPromptNameModal"),
    "MemoryPanel": (".memory_panel", "MemoryPanel"),
    "MemoryPane": (".memory_pane", "MemoryPane"),
    "MemoryPaneSession": (".memory_pane", "MemoryPaneSession"),
    "MiniXPromptNameModal": (
        ".mini_xprompt_name_modal",
        "MiniXPromptNameModal",
    ),
    "MiniXPromptNameResult": (
        ".mini_xprompt_name_modal",
        "MiniXPromptNameResult",
    ),
    "MiniXPromptSaveConfirmModal": (
        ".mini_xprompt_save_confirm_modal",
        "MiniXPromptSaveConfirmModal",
    ),
    "MiniXPromptSaveConfirmState": (
        ".mini_xprompt_save_confirm_modal",
        "MiniXPromptSaveConfirmState",
    ),
    "MentorApplyResult": (".mentor_review_models", "MentorApplyResult"),
    "MentorInfo": (".mentor_review_models", "MentorInfo"),
    "MentorKillResult": (".mentor_review_models", "MentorKillResult"),
    "MentorProfileSelectModal": (
        ".mentor_profile_select_modal",
        "MentorProfileSelectModal",
    ),
    "MentorReviewData": (".mentor_review_models", "MentorReviewData"),
    "MentorReviewModal": (".mentor_review_modal", "MentorReviewModal"),
    "MentorRunResult": (".mentor_review_models", "MentorRunResult"),
    "ModelPickerModal": (".model_picker_modal", "ModelPickerModal"),
    "LaunchPane": (".models_panel", "LaunchPane"),
    "LaunchPaneDisplayMode": (".models_panel", "LaunchPaneDisplayMode"),
    "LaunchPaneHost": (".models_panel", "LaunchPaneHost"),
    "LaunchPaneSessionState": (".models_panel", "LaunchPaneSessionState"),
    "ModelsPanel": (".models_panel", "ModelsPanel"),
    "ModelsPanelResult": (".models_panel", "ModelsPanelResult"),
    "NotificationModal": (".notification_modal", "NotificationModal"),
    "ParentSelectModal": (".parent_select_modal", "ParentSelectModal"),
    "PlanApprovalModal": (".plan_approval_modal", "PlanApprovalModal"),
    "PlanApprovalResult": (".plan_approval_modal", "PlanApprovalResult"),
    "PluginActionConfirmModal": (
        ".plugin_action_confirm_modal",
        "PluginActionConfirmModal",
    ),
    "PluginActionConfirmResult": (
        ".plugin_action_confirm_modal",
        "PluginActionConfirmResult",
    ),
    "PluginActionVariant": (".plugin_action_confirm_modal", "PluginActionVariant"),
    "PostWriteActionsModal": (".post_write_actions_modal", "PostWriteActionsModal"),
    "PrOriginModal": (".pr_origin_modal", "PrOriginModal"),
    "ProcessSelectModal": (".process_select_modal", "ProcessSelectModal"),
    "ProcessSelection": (".process_select_modal", "ProcessSelection"),
    "ProjectAliasEditorModal": (
        ".project_alias_editor_modal",
        "ProjectAliasEditorModal",
    ),
    "ProjectSelectModal": (".project_select_modal", "ProjectSelectModal"),
    "ProjectSelectResult": (".project_selection_types", "ProjectSelectResult"),
    "PromptHistoryAction": (".prompt_history_modal", "PromptHistoryAction"),
    "PromptHistoryModal": (".prompt_history_modal", "PromptHistoryModal"),
    "PromptHistoryResult": (".prompt_history_modal", "PromptHistoryResult"),
    "PromptSubmitChoice": (".prompt_submit_choice_modal", "PromptSubmitChoice"),
    "PromptSubmitChoiceModal": (
        ".prompt_submit_choice_modal",
        "PromptSubmitChoiceModal",
    ),
    "PropertyPickerItem": (".property_picker_modal", "PropertyPickerItem"),
    "PropertyPickerModal": (".property_picker_modal", "PropertyPickerModal"),
    "PropertyPickerRecord": (".property_picker_modal", "PropertyPickerRecord"),
    "QueryEditModal": (".query_edit_modal", "QueryEditModal"),
    "QuitOption": (".quit_options_modal", "QuitOption"),
    "QuitOptionsModal": (".quit_options_modal", "QuitOptionsModal"),
    "RecursiveFileFinderModal": (
        ".recursive_finder_modal",
        "RecursiveFileFinderModal",
    ),
    "RenamePatchModal": (".rename_patch_modal", "RenamePatchModal"),
    "ReportModal": (".report_modal", "ReportModal"),
    "RunnerJumpTarget": (".runners_modal", "RunnerJumpTarget"),
    "RunnersModal": (".runners_modal", "RunnersModal"),
    "SavedAgentGroupRevivalModal": (
        ".saved_agent_group_revival_modal",
        "SavedAgentGroupRevivalModal",
    ),
    "SavedAgentGroupRevivalResult": (
        ".saved_agent_group_revival_modal",
        "SavedAgentGroupRevivalResult",
    ),
    "SavedQueryPickerModal": (".saved_query_picker", "SavedQueryPickerModal"),
    "SaveAgentGroupModal": (".save_agent_group_modal", "SaveAgentGroupModal"),
    "SaveAgentGroupResult": (".save_agent_group_modal", "SaveAgentGroupResult"),
    "SchemaFieldDiagnostic": (".schema_object_form", "SchemaFieldDiagnostic"),
    "SchemaFieldOperation": (".schema_object_form", "SchemaFieldOperation"),
    "SchemaFormModel": (".schema_object_form", "SchemaFormModel"),
    "SchemaObjectField": (".schema_object_form", "SchemaObjectField"),
    "SchemaObjectForm": (".schema_object_form", "SchemaObjectForm"),
    "SchemaObjectFormModel": (".schema_object_form", "SchemaObjectFormModel"),
    "SelectionItem": (".project_selection_types", "SelectionItem"),
    "SnoozeDurationModal": (".snooze_duration_modal", "SnoozeDurationModal"),
    "SnippetNameModal": (".snippet_name_modal", "SnippetNameModal"),
    "SnippetNameResult": (".snippet_name_modal", "SnippetNameResult"),
    "SnippetSaveConfirmModal": (
        ".snippet_save_confirm_modal",
        "SnippetSaveConfirmModal",
    ),
    "SnippetSaveConfirmState": (
        ".snippet_save_confirm_modal",
        "SnippetSaveConfirmState",
    ),
    "SnippetsPaneHost": (".snippets_panel", "SnippetsPaneHost"),
    "SnippetsPane": (".snippets_panel", "SnippetsPane"),
    "SnippetsPaneSessionState": (".snippets_panel", "SnippetsPaneSessionState"),
    "SnippetsPanel": (".snippets_panel", "SnippetsPanel"),
    "StashRestoreResult": (".stashed_prompts_modal", "StashRestoreResult"),
    "StashedPromptsModal": (".stashed_prompts_modal", "StashedPromptsModal"),
    "StatisticsHelpModal": (".statistics_help_modal", "StatisticsHelpModal"),
    "StatisticsXPromptPickerModal": (
        ".statistics_xprompt_picker_modal",
        "StatisticsXPromptPickerModal",
    ),
    "StatusModal": (".status_modal", "StatusModal"),
    "TabName": (".help_modal", "TabName"),
    "TagInputModal": (".tag_input_modal", "TagInputModal"),
    "TmuxAgentModal": (".tmux_agent_modal", "TmuxAgentModal"),
    "TransactionDiagnostic": (
        ".config_transaction_preview",
        "TransactionDiagnostic",
    ),
    "TransactionEffectivePreview": (
        ".config_transaction_preview",
        "TransactionEffectivePreview",
    ),
    "UnifiedSaveLocation": (".unified_xprompt_save_modal", "UnifiedSaveLocation"),
    "UnifiedXPromptSaveModal": (
        ".unified_xprompt_save_modal",
        "UnifiedXPromptSaveModal",
    ),
    "UnifiedXPromptSaveResult": (
        ".unified_xprompt_save_modal",
        "UnifiedXPromptSaveResult",
    ),
    "UpdatePanel": (".update_panel", "UpdatePanel"),
    "UpdatePanelResult": (".update_panel", "UpdatePanelResult"),
    "UpdatePinnedStashModal": (
        ".update_pinned_stash_modal",
        "UpdatePinnedStashModal",
    ),
    "UserQuestionModal": (".user_question_modal", "UserQuestionModal"),
    "UserQuestionResult": (".user_question_modal", "UserQuestionResult"),
    "WaitAgentCandidate": (".wait_modal", "WaitAgentCandidate"),
    "WaitModal": (".wait_modal", "WaitModal"),
    "WaitModalResult": (".wait_modal", "WaitModalResult"),
    "WorkflowHITLInput": (".workflow_hitl_modal", "WorkflowHITLInput"),
    "WorkflowHITLModal": (".workflow_hitl_modal", "WorkflowHITLModal"),
    "WorkflowSelectModal": (".workflow_select_modal", "WorkflowSelectModal"),
    "WorkspaceInputModal": (".workspace_input_modal", "WorkspaceInputModal"),
    "XPromptConfigEntry": (".xprompt_config_modal", "XPromptConfigEntry"),
    "XPromptConfigEntryModal": (".xprompt_config_modal", "XPromptConfigEntryModal"),
    "XPromptFilenameModal": (".xprompt_filename_modal", "XPromptFilenameModal"),
    "XPromptFocusChoice": (
        ".statistics_xprompt_picker_modal",
        "XPromptFocusChoice",
    ),
    "XPromptItemModal": (".xprompt_item_modal", "XPromptItemModal"),
    "XPromptLocation": (".xprompt_location_modal", "XPromptLocation"),
    "XPromptLocationModal": (".xprompt_location_modal", "XPromptLocationModal"),
    "XPromptSelectModal": (".xprompt_select_modal", "XPromptSelectModal"),
    "XPromptSelection": (".xprompt_select_modal", "XPromptSelection"),
    "XPromptWriteConflictModal": (
        ".xprompt_write_conflict_modal",
        "XPromptWriteConflictModal",
    ),
    "ZoomPanelModal": (".zoom_panel_modal", "ZoomPanelModal"),
    "ZoomPanelSeed": (".zoom_panel_modal", "ZoomPanelSeed"),
    "ZoomPanelTarget": (".zoom_panel_modal", "ZoomPanelTarget"),
    "axe_entry_schema": (".axe_entry_editor_modal", "axe_entry_schema"),
    "build_agent_workspace_tmux_choices": (
        ".agent_workspace_tmux_modal",
        "build_agent_workspace_tmux_choices",
    ),
    "build_mentor_review_data": (
        ".mentor_review_models",
        "build_mentor_review_data",
    ),
    "get_runner_count": (".runners_modal", "get_runner_count"),
    "render_transaction_preview": (
        ".config_transaction_preview",
        "render_transaction_preview",
    ),
    "stable_chop_name": (".axe_add_modals", "stable_chop_name"),
    "validate_axe_new_entry_identity": (
        ".axe_add_modals",
        "validate_axe_new_entry_identity",
    ),
}

__all__ = [
    "BeadCloseModal",
    "BeadCloseResult",
    "BeadCreateModal",
    "BeadCreateResult",
    "BeadEditorModal",
    "BeadEditorResult",
    "BeadNoteModal",
    "AddableProperty",
    "AddPropertyModal",
    "PropertyPickerItem",
    "PropertyPickerModal",
    "PropertyPickerRecord",
    "AxeEntryEditorModal",
    "AxeEntryEditorResult",
    "AxeEntryEditorSeed",
    "AxeEntryIdentity",
    "AxeEntryKind",
    "AxeEntryMutationRequest",
    "AxeWritableScope",
    "axe_entry_schema",
    "AxeAddChooserModal",
    "AxeAddKind",
    "AxeLumberjackPickerModal",
    "AxeNewEntryDraft",
    "AxeNewEntryIdentityModal",
    "AxeScriptChoice",
    "AxeScriptPickerModal",
    "stable_chop_name",
    "validate_axe_new_entry_identity",
    "ConfigTransactionApplyResult",
    "ConfigTransactionConflict",
    "ConfigTransactionMetadata",
    "ConfigTransactionPreview",
    "ConfigTransactionRequest",
    "TransactionDiagnostic",
    "TransactionEffectivePreview",
    "render_transaction_preview",
    "SchemaFieldDiagnostic",
    "SchemaFieldOperation",
    "SchemaFormModel",
    "SchemaObjectField",
    "SchemaObjectForm",
    "SchemaObjectFormModel",
    "InputItemModal",
    "IssueEditModal",
    "IssueEditResult",
    "JumpActionModal",
    "JumpChoice",
    "MemoryPanel",
    "MemoryPane",
    "MemoryPaneSession",
    "MiniXPromptNameModal",
    "MiniXPromptNameResult",
    "MentorApplyResult",
    "MentorInfo",
    "MentorKillResult",
    "MentorProfileSelectModal",
    "MentorReviewData",
    "MentorReviewModal",
    "MentorRunResult",
    "build_mentor_review_data",
    "AddXPromptModal",
    "ApproveOptionsEditPrompt",
    "ApproveOptionsModal",
    "ApproveOptionsResult",
    "AutoApproveChoice",
    "AutoApproveModal",
    "CustomApprovalEditPrompt",
    "CustomApprovalModal",
    "CustomApprovalResult",
    "AgentNameModal",
    "AgentNeighborChoice",
    "AgentNeighborModal",
    "AgentWorkspaceTmuxChoice",
    "AgentWorkspaceTmuxModal",
    "build_agent_workspace_tmux_choices",
    "ArtifactFileSelectionModal",
    "ArtifactFileSelectionResult",
    "AgentCleanupAction",
    "AgentCleanupClanKey",
    "AgentCleanupClanModal",
    "AgentCleanupClanResult",
    "AgentCleanupCustomModal",
    "AgentCleanupCustomResult",
    "AgentCleanupModal",
    "AgentCleanupPanelState",
    "AgentCleanupResult",
    "AgentCleanupTribeModal",
    "AgentCleanupTribeResult",
    "AgentRunLogModal",
    "AgentTribeModal",
    "AgentTribeModalResult",
    "CommandHistoryModal",
    "ConfirmActionModal",
    "CommandInputModal",
    "BeadEditModal",
    "BeadEditResult",
    "CommandPaletteModal",
    "CopyAsContext",
    "CopyAsModal",
    "CopyAsRow",
    "CommitViewModal",
    "CustomModelInputModal",
    "DisabledProviderLaunchDecision",
    "DisabledProviderLaunchModal",
    "ConfirmDeleteModal",
    "ConfirmDialog",
    "ConfirmDismissAllModal",
    "ConfirmKind",
    "ConfirmKillAllModal",
    "ConfirmKillModal",
    "ConfirmKillProcShellModal",
    "ConfirmRerunModal",
    "ConfirmRevertAgentModal",
    "ConfirmStopMonitorModal",
    "DismissedAgentSelectModal",
    "HelpModal",
    "StatisticsHelpModal",
    "StatisticsXPromptPickerModal",
    "XPromptFocusChoice",
    "HookHistoryAction",
    "HookHistoryModal",
    "HookHistoryResult",
    "JumpAllModal",
    "JumpAllResult",
    "LaunchApprovalModal",
    "LaunchApprovalResult",
    "GateDebugModal",
    "LocalXPromptNameModal",
    "MiniXPromptSaveConfirmModal",
    "MiniXPromptSaveConfirmState",
    "RecursiveFileFinderModal",
    "ModelPickerModal",
    "NotificationModal",
    "ReportModal",
    "ParentSelectModal",
    "PlanApprovalModal",
    "PlanApprovalResult",
    "PrOriginModal",
    "ProcessSelectModal",
    "ProcessSelection",
    "InventoryProjectChoice",
    "InventoryProjectPicker",
    "InventoryProjectPickerResult",
    "ProjectAliasEditorModal",
    "ProjectSelectModal",
    "ProjectSelectResult",
    "PromptHistoryAction",
    "PromptHistoryModal",
    "PromptHistoryResult",
    "PromptSubmitChoice",
    "PromptSubmitChoiceModal",
    "PostWriteActionsModal",
    "QueryEditModal",
    "SavedQueryPickerModal",
    "QuitOption",
    "QuitOptionsModal",
    "RenamePatchModal",
    "StashRestoreResult",
    "StashedPromptsModal",
    "SavedAgentGroupRevivalModal",
    "SavedAgentGroupRevivalResult",
    "SaveAgentGroupModal",
    "SaveAgentGroupResult",
    "BackgroundProcEntry",
    "RunnerJumpTarget",
    "RunnersModal",
    "SnoozeDurationModal",
    "SnippetNameModal",
    "SnippetNameResult",
    "SnippetSaveConfirmModal",
    "SnippetSaveConfirmState",
    "SnippetsPaneHost",
    "SnippetsPane",
    "SnippetsPaneSessionState",
    "SnippetsPanel",
    "get_runner_count",
    "SelectionItem",
    "StatusModal",
    "TabName",
    "TagInputModal",
    "TmuxAgentModal",
    "AliasEditPreviewModal",
    "LaunchPane",
    "LaunchPaneDisplayMode",
    "LaunchPaneHost",
    "LaunchPaneSessionState",
    "ModelsPanel",
    "ModelsPanelResult",
    "UpdatePanel",
    "UpdatePanelResult",
    "UpdatePinnedStashModal",
    "WaitModal",
    "WaitAgentCandidate",
    "WaitModalResult",
    "UserQuestionModal",
    "UserQuestionResult",
    "InputCollectionModal",
    "ConfigCenterModal",
    "ConfigHubEntry",
    "ConfigHubPane",
    "ConfigHubSessionState",
    "PluginActionConfirmModal",
    "PluginActionConfirmResult",
    "PluginActionVariant",
    "XPromptItemModal",
    "XPromptConfigEntry",
    "XPromptConfigEntryModal",
    "XPromptFilenameModal",
    "XPromptLocation",
    "XPromptLocationModal",
    "XPromptWriteConflictModal",
    "UnifiedSaveLocation",
    "UnifiedXPromptSaveModal",
    "UnifiedXPromptSaveResult",
    "XPromptSelection",
    "XPromptSelectModal",
    "WorkflowHITLInput",
    "WorkflowHITLModal",
    "CustomGateModal",
    "CustomGateModalData",
    "CustomGateModalResult",
    "GateActionControls",
    "GateActionOutputModal",
    "GateActionRunner",
    "GateActionsData",
    "GateBranchControls",
    "GateCommandOutcome",
    "GateEditOutcome",
    "GateInputPanel",
    "GateInputPanelResult",
    "GateInputRequest",
    "GateRetryModal",
    "GateBranchData",
    "WorkflowSelectModal",
    "WorkspaceInputModal",
    "ZoomPanelModal",
    "ZoomPanelSeed",
    "ZoomPanelTarget",
]


def __getattr__(name: str) -> Any:
    try:
        module_name, attr = _LAZY_EXPORTS[name]
    except KeyError as error:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        ) from error
    module = import_module(module_name, __name__)
    value = getattr(module, attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})


# PEP 562 entry points are called by Python, not by normal in-file code.
_PEP562_HOOKS = (__getattr__, __dir__)
