"""Modal dialogs for the ace TUI."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from ._export_table import _LAZY_EXPORTS

if TYPE_CHECKING:
    # These symbols have no static Python consumer outside their own defining
    # file; without an explicit re-export here, symvision can't see that they
    # are used (via the dynamic __getattr__ lazy export below) and flags them
    # as dead public code.
    from .add_xprompt_modal import AddXPromptModal as AddXPromptModal
    from .axe_add_modals import (
        validate_axe_new_entry_identity as validate_axe_new_entry_identity,
    )
    from .command_input_modal import CommandInputModal as CommandInputModal
    from .config_transaction import (
        ConfigTransactionConflict as ConfigTransactionConflict,
    )
    from .input_item_modal import InputItemModal as InputItemModal
    from .local_xprompt_name_modal import LocalXPromptNameModal as LocalXPromptNameModal
    from .memory_panel import MemoryPanel as MemoryPanel
    from .project_select_modal import ProjectSelectModal as ProjectSelectModal
    from .schema_object_form import SchemaFieldDiagnostic as SchemaFieldDiagnostic
    from .snippets_panel import SnippetsPanel as SnippetsPanel
    from .xprompt_item_modal import XPromptItemModal as XPromptItemModal

__all__ = [
    "BeadCloseModal",
    "BeadCloseResult",
    "BeadCreateModal",
    "BeadCreateResult",
    "BeadEditorModal",
    "BeadEditorResult",
    "BeadNoteModal",
    "AddableProperty",
    "AddPropertyModal",
    "PropertyPickerItem",
    "PropertyPickerModal",
    "PropertyPickerRecord",
    "AxeEntryEditorModal",
    "AxeEntryEditorResult",
    "AxeEntryEditorSeed",
    "AxeEntryIdentity",
    "AxeEntryKind",
    "AxeEntryMutationRequest",
    "AxeWritableScope",
    "axe_entry_schema",
    "AxeAddChooserModal",
    "AxeAddKind",
    "AxeLumberjackPickerModal",
    "AxeNewEntryDraft",
    "AxeNewEntryIdentityModal",
    "AxeScriptChoice",
    "AxeScriptPickerModal",
    "stable_chop_name",
    "validate_axe_new_entry_identity",
    "ConfigTransactionApplyResult",
    "ConfigTransactionConflict",
    "ConfigTransactionMetadata",
    "ConfigTransactionPreview",
    "ConfigTransactionRequest",
    "TransactionDiagnostic",
    "TransactionEffectivePreview",
    "render_transaction_preview",
    "SchemaFieldDiagnostic",
    "SchemaFieldOperation",
    "SchemaFormModel",
    "SchemaObjectField",
    "SchemaObjectForm",
    "SchemaObjectFormModel",
    "InputItemModal",
    "IssueEditModal",
    "IssueEditResult",
    "JumpActionModal",
    "JumpChoice",
    "MemoryPanel",
    "MemoryPane",
    "MemoryPaneSession",
    "MiniXPromptNameModal",
    "MiniXPromptNameResult",
    "MentorApplyResult",
    "MentorInfo",
    "MentorKillResult",
    "MentorProfileSelectModal",
    "MentorReviewData",
    "MentorReviewModal",
    "MentorRunResult",
    "build_mentor_review_data",
    "AddXPromptModal",
    "ApproveOptionsEditPrompt",
    "ApproveOptionsModal",
    "ApproveOptionsResult",
    "AutoApproveChoice",
    "AutoApproveModal",
    "CustomApprovalEditPrompt",
    "CustomApprovalModal",
    "CustomApprovalResult",
    "AgentNameModal",
    "AgentNeighborChoice",
    "AgentNeighborModal",
    "AgentWorkspaceTmuxChoice",
    "AgentWorkspaceTmuxModal",
    "build_agent_workspace_tmux_choices",
    "ArtifactFileSelectionModal",
    "ArtifactFileSelectionResult",
    "AgentCleanupAction",
    "AgentCleanupClanKey",
    "AgentCleanupClanModal",
    "AgentCleanupClanResult",
    "AgentCleanupCustomModal",
    "AgentCleanupCustomResult",
    "AgentCleanupModal",
    "AgentCleanupPanelState",
    "AgentCleanupResult",
    "AgentCleanupTribeModal",
    "AgentCleanupTribeResult",
    "AgentRunLogModal",
    "AgentTribeModal",
    "AgentTribeModalResult",
    "ArtifactLinkModal",
    "ArtifactLinkRelationChoice",
    "ArtifactLinkResult",
    "ArtifactLinksPanelModal",
    "ArtifactLinksPanelResult",
    "CommandHistoryModal",
    "ConfirmActionModal",
    "CommandInputModal",
    "BeadEditModal",
    "BeadEditResult",
    "CommandPaletteModal",
    "CopyAsContext",
    "CopyAsModal",
    "CopyAsRow",
    "CommitViewModal",
    "CustomModelInputModal",
    "DisabledProviderLaunchDecision",
    "DisabledProviderLaunchModal",
    "ConfirmDeleteModal",
    "ConfirmDialog",
    "ConfirmDismissAllModal",
    "ConfirmKind",
    "ConfirmKillAllModal",
    "ConfirmKillModal",
    "ConfirmKillProcShellModal",
    "ConfirmRerunModal",
    "ConfirmRevertAgentModal",
    "ConfirmStopMonitorModal",
    "DismissedAgentSelectModal",
    "HelpModal",
    "StatisticsHelpModal",
    "StatisticsXPromptPickerModal",
    "XPromptFocusChoice",
    "HookHistoryAction",
    "HookHistoryModal",
    "HookHistoryResult",
    "JumpAllModal",
    "JumpAllResult",
    "LaunchApprovalModal",
    "LaunchApprovalResult",
    "GateDebugModal",
    "LocalXPromptNameModal",
    "MiniXPromptSaveConfirmModal",
    "MiniXPromptSaveConfirmState",
    "RecursiveFileFinderModal",
    "ModelPickerModal",
    "NotificationModal",
    "ReportModal",
    "ParentSelectModal",
    "PlanApprovalModal",
    "PlanApprovalResult",
    "PrOriginModal",
    "ProcessSelectModal",
    "ProcessSelection",
    "InventoryProjectChoice",
    "InventoryProjectPicker",
    "InventoryProjectPickerResult",
    "ProjectAliasEditorModal",
    "ProjectSelectModal",
    "ProjectSelectResult",
    "PromptHistoryAction",
    "PromptHistoryModal",
    "PromptHistoryResult",
    "PromptSubmitChoice",
    "PromptSubmitChoiceModal",
    "PostWriteActionsModal",
    "QueryEditModal",
    "SavedQueryPickerModal",
    "QuitOption",
    "QuitOptionsModal",
    "RenamePatchModal",
    "StashRestoreResult",
    "StashedPromptsModal",
    "SavedAgentGroupRevivalModal",
    "SavedAgentGroupRevivalResult",
    "SaveAgentGroupModal",
    "SaveAgentGroupResult",
    "BackgroundProcEntry",
    "RunnerJumpTarget",
    "RunnersModal",
    "SnoozeDurationModal",
    "SnippetNameModal",
    "SnippetNameResult",
    "SnippetSaveConfirmModal",
    "SnippetSaveConfirmState",
    "SnippetsPaneHost",
    "SnippetsPane",
    "SnippetsPaneSessionState",
    "SnippetsPanel",
    "get_runner_count",
    "SelectionItem",
    "StatusModal",
    "TabName",
    "TagInputModal",
    "TmuxAgentModal",
    "AliasEditPreviewModal",
    "LaunchPane",
    "LaunchPaneDisplayMode",
    "LaunchPaneHost",
    "LaunchPaneSessionState",
    "ModelsPanel",
    "ModelsPanelResult",
    "UpdatePanel",
    "UpdatePanelResult",
    "UpdatePinnedStashModal",
    "WaitModal",
    "WaitAgentCandidate",
    "WaitModalResult",
    "UserQuestionModal",
    "UserQuestionResult",
    "InputCollectionModal",
    "ConfigCenterModal",
    "ConfigHubEntry",
    "ConfigHubPane",
    "ConfigHubSessionState",
    "PluginActionConfirmModal",
    "PluginActionConfirmResult",
    "PluginActionVariant",
    "XPromptItemModal",
    "XPromptConfigEntry",
    "XPromptConfigEntryModal",
    "XPromptFilenameModal",
    "XPromptLocation",
    "XPromptLocationModal",
    "XPromptWriteConflictModal",
    "UnifiedSaveLocation",
    "UnifiedXPromptSaveModal",
    "UnifiedXPromptSaveResult",
    "XPromptSelection",
    "XPromptSelectModal",
    "WorkflowHITLInput",
    "WorkflowHITLModal",
    "CustomGateModal",
    "CustomGateModalData",
    "CustomGateModalResult",
    "GateActionControls",
    "GateActionOutputModal",
    "GateActionRunner",
    "GateActionsData",
    "GateBranchControls",
    "GateCommandOutcome",
    "GateEditOutcome",
    "GateInputPanel",
    "GateInputPanelResult",
    "GateInputRequest",
    "GateRetryModal",
    "GateBranchData",
    "WorkflowSelectModal",
    "WorkspaceInputModal",
    "ZoomPanelModal",
    "ZoomPanelSeed",
    "ZoomPanelTarget",
]


def __getattr__(name: str) -> Any:
    try:
        module_name, attr = _LAZY_EXPORTS[name]
    except KeyError as error:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        ) from error
    module = import_module(module_name, __name__)
    value = getattr(module, attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})


# PEP 562 entry points are called by Python, not by normal in-file code.
_PEP562_HOOKS = (__getattr__, __dir__)
