"""Frozen reference composer for the virtual body line model.

Copied verbatim from the pre-virtualization ``compose_body`` /
``_paint_section_body`` / ``apply_gutter`` pipeline (with section-rule,
label-capsule and mark rendering) and frozen: every src helper a later
phase might delete or change is vendored here under test-only names, so
later refactors cannot silently move the oracle. Stable leaves (the
document model, link-kind tables, trail text) are still imported live.

Do not edit this file. If a parity test fails after a src change, the src
change moved rendering — that is the signal, not an excuse to update the
oracle.
"""

from __future__ import annotations

from collections.abc import Mapping
from collections.abc import Set as AbstractSet
from dataclasses import dataclass
from typing import Any

from rich.cells import cell_len
from rich.console import Console, Group, RenderableType
from rich.text import Text

from sase.ace.tui._artifact_tab_model import (
    ARTIFACTS_ACCENTS,
    ARTIFACTS_ICONS,
    EXTERNAL_ACCENT,
)
from sase.pager._labels import DanglingPredicate, PagerLabelLayer
from sase.pager._line_mark import LineMark
from sase.pager._trail_chrome_model import MUTED_STYLE
from sase.pager._trail_chrome_text import append_path_label
from sase.pager.document import PagerDocument, PagerSection
from sase.pager.link_scan import LinkSpanKind

_REF_DIVIDER_LINES = 1

_REF_SEPARATOR = "│ "
_REF_RAIL_SEPARATOR = "┃ "
_REF_SEPARATOR_STYLE = "dim"
_REF_NUMBER_STYLE = "dim"
_REF_MIN_NUMBER_WIDTH = 2

_REF_LABEL_STYLE = "bold black on #FFD75F"
_REF_LABEL_MATCH_STYLE = "bold black on #FFFFAF"
_REF_LABEL_DIM_STYLE = "dim"
_REF_LABEL_DANGLING_STYLE = "dim"
_REF_DANGLING_ICON = "⊘"
_REF_DANGLING_ACCENT = "#808080"
_REF_DANGLING_TEXT = "(missing)"
_REF_DEFAULT_LINK_ICON = "•"
_REF_DEFAULT_LINK_ACCENT = EXTERNAL_ACCENT
_REF_PLAN_REF_ICON = "✎"
_REF_URL_ICON = "↗"
_REF_NO_BREAK_SPACE = "\u00a0"

_REF_KIND_TABS: Mapping[str, str] = {
    "agent": "agents",
    "bead": "beads",
    "file": "files",
    "patch": "patches",
    "plan": "ref:plan",
    "stitch": "stitches",
}
_REF_DIRECT_KIND_TABS: Mapping[str, str] = {
    **_REF_KIND_TABS,
    "agents": "agents",
    "beads": "beads",
    "files": "files",
    "patches": "patches",
    "stitches": "stitches",
    LinkSpanKind.FILE_PATH.value: "files",
}
_REF_DIVIDER_CHAR = "━"
_REF_SECTION_KIND_TAB: Mapping[str, str] = {
    "bead": "beads",
    "file": "files",
    "agent": "agents",
}
_REF_DEFAULT_SECTION_ICON = "◆"
_REF_DEFAULT_SECTION_ACCENT = "#AFAFAF"


@dataclass(frozen=True, slots=True)
class _RefTargetMarker:
    icon: str
    accent: str


@dataclass(frozen=True, slots=True)
class ReferenceBody:
    """One document rendered at a fixed width, with expanded row texts."""

    renderable: RenderableType
    section_offsets: tuple[int, ...]
    total_height: int
    section_line_counts: tuple[int, ...] = ()
    section_line_rows: tuple[tuple[int, ...], ...] = ()
    rows: tuple[Text, ...] = ()


def _ref_number_width(max_line_count: int) -> int:
    return max(len(str(max(max_line_count, 0))), _REF_MIN_NUMBER_WIDTH)


def _ref_gutter_width(max_line_count: int) -> int:
    return _ref_number_width(max_line_count) + len(_REF_SEPARATOR)


def _ref_logical_line_count(text: str) -> int:
    if not text:
        return 0
    count = text.count("\n")
    if text.endswith("\n"):
        return count
    return count + 1


def _ref_logical_lines(text: Text) -> tuple[Text, ...]:
    if not text.plain:
        return ()
    return tuple(text.split("\n"))


@dataclass(frozen=True, slots=True)
class _RefGutterSection:
    text: Text
    row_count: int
    line_rows: tuple[int, ...]


def _ref_apply_gutter(
    text: Text,
    *,
    content_width: int,
    number_width: int,
    emphasis_range: tuple[int, int] | None = None,
    accent: str | None = None,
    change_marks: dict[int, str] | None = None,
    removal_anchors: set[int] | frozenset[int] | tuple[int, ...] | None = None,
    rail_style: str | None = None,
    history_styles: Any | None = None,
) -> _RefGutterSection:
    wrap_width = max(content_width, 1)
    console = Console(
        width=wrap_width,
        color_system=None,
        force_terminal=False,
        highlight=False,
        markup=False,
        emoji=False,
    )
    lo, hi = _ref_normalized_emphasis_range(emphasis_range)
    marks = change_marks or {}
    anchors = set(removal_anchors or ())
    mark_styles = _ref_mark_styles(history_styles)
    lines = _ref_logical_lines(text)
    visual_rows: list[Text] = []
    line_rows: list[int] = []
    if 0 in anchors:
        visual_rows.append(_ref_removal_anchor_row(number_width, mark_styles[2]))
    for line_number, logical in enumerate(lines, start=1):
        line_rows.append(len(visual_rows))
        in_range = lo is not None and hi is not None and lo <= line_number <= hi
        wrapped = _ref_wrap_logical_line(logical, wrap_width, console)
        for wrap_index, piece in enumerate(wrapped):
            number = line_number if wrap_index == 0 else None
            change_kind = marks.get(line_number) if wrap_index == 0 else None
            if in_range:
                visual_rows.append(
                    _ref_guttered_row(
                        piece,
                        number=number,
                        number_width=number_width,
                        emphasize=in_range and number is not None,
                        rail=in_range,
                        accent=accent,
                    )
                )
            elif change_kind in ("added", "changed"):
                visual_rows.append(
                    _ref_change_mark_row(
                        piece,
                        number=number,
                        number_width=number_width,
                        kind=change_kind,
                        mark_styles=mark_styles,
                    )
                )
            else:
                visual_rows.append(
                    _ref_guttered_row(
                        piece,
                        number=number,
                        number_width=number_width,
                        emphasize=False,
                        rail=False,
                        accent=None,
                        rail_style=rail_style,
                    )
                )
        if line_number in anchors:
            visual_rows.append(_ref_removal_anchor_row(number_width, mark_styles[2]))
    if not visual_rows:
        visual_rows.append(
            _ref_guttered_row(
                Text(),
                number=None,
                number_width=number_width,
                emphasize=False,
                rail=False,
                accent=None,
                rail_style=rail_style,
            )
        )
    joined = Text(no_wrap=True, overflow="crop")
    for index, row in enumerate(visual_rows):
        if index:
            joined.append("\n")
        joined.append_text(row)
    return _RefGutterSection(
        text=joined,
        row_count=len(visual_rows),
        line_rows=tuple(line_rows),
    )


def _ref_normalized_emphasis_range(
    emphasis_range: tuple[int, int] | None,
) -> tuple[int | None, int | None]:
    if emphasis_range is None:
        return None, None
    lo, hi = emphasis_range
    if lo > hi:
        lo, hi = hi, lo
    return lo, hi


def _ref_wrap_logical_line(
    text: Text, width: int, console: Console
) -> tuple[Text, ...]:
    if not text.plain:
        return (Text(),)
    copied = text.copy()
    copied.overflow = "fold"
    copied.no_wrap = False
    wrapped = tuple(copied.wrap(console, width, overflow="fold"))
    return wrapped if wrapped else (Text(),)


def _ref_mark_styles(history_styles: Any | None) -> tuple[str, str, str]:
    if history_styles is None:
        from sase.pager.history.styles import default_history_styles

        history_styles = default_history_styles()
    return (
        str(getattr(history_styles, "gutter_add", "green")),
        str(getattr(history_styles, "gutter_change", "blue")),
        str(getattr(history_styles, "gutter_remove", "red")),
    )


def _ref_guttered_row(
    piece: Text,
    *,
    number: int | None,
    number_width: int,
    emphasize: bool,
    rail: bool,
    accent: str | None,
    rail_style: str | None = None,
) -> Text:
    row = Text(no_wrap=True, overflow="crop")
    row.append_text(
        _ref_gutter_cells(
            number,
            number_width,
            emphasize=emphasize,
            rail=rail,
            accent=accent,
            rail_style=rail_style,
        )
    )
    row.append_text(piece)
    return row


def _ref_gutter_cells(
    number: int | None,
    number_width: int,
    *,
    emphasize: bool,
    rail: bool,
    accent: str | None,
    rail_style: str | None = None,
) -> Text:
    if number is None:
        label = f"{'':>{number_width}}"
        style = _REF_NUMBER_STYLE
    else:
        label = f"{number:>{number_width}}"
        if emphasize:
            style = f"bold {accent}" if accent else "bold"
        else:
            style = _REF_NUMBER_STYLE
    cells = Text()
    cells.append(label, style=style)
    if rail:
        separator_style = accent if accent else "bold"
        cells.append(_REF_RAIL_SEPARATOR, style=separator_style)
    elif rail_style is not None:
        cells.append(_REF_SEPARATOR, style=rail_style)
    else:
        cells.append(_REF_SEPARATOR, style=_REF_SEPARATOR_STYLE)
    return cells


def _ref_change_mark_row(
    piece: Text,
    *,
    number: int | None,
    number_width: int,
    kind: str,
    mark_styles: tuple[str, str, str] = ("green", "blue", "red"),
) -> Text:
    row = Text(no_wrap=True, overflow="crop")
    label = f"{'':>{number_width}}" if number is None else f"{number:>{number_width}}"
    row.append(label, style=_REF_NUMBER_STYLE)
    if kind == "added":
        row.append("▌ ", style=mark_styles[0])
    else:
        row.append("▌ ", style=mark_styles[1])
    row.append_text(piece)
    return row


def _ref_removal_anchor_row(number_width: int, style: str = "red") -> Text:
    row = Text(no_wrap=True, overflow="crop")
    row.append(f"{'':>{number_width}}", style=_REF_NUMBER_STYLE)
    row.append("╴ ", style=style)
    return row


def _ref_link_accent_style(accent: str, surface: str | None = None) -> str:
    if surface is None:
        return f"bold {accent}"
    try:
        from sase.pager.syntax_theme import (
            ensure_contrast_min,
            parse_color,
        )

        if parse_color(surface) is None or parse_color(accent) is None:
            return f"bold {accent}"
        corrected = ensure_contrast_min(accent, surface, accent, 4.5)
        return f"bold {corrected}"
    except Exception:
        return f"bold {accent}"


def _ref_render_section_with_labels(
    section: PagerSection,
    labels: Any,
    *,
    pending_prefix: str = "",
    source: Text | None = None,
    surface: str | None = None,
) -> Text:
    body = section.body_text if source is None else source
    if not labels:
        return body
    output = Text(
        style=body.style,
        justify=body.justify,
        overflow=body.overflow,
        no_wrap=body.no_wrap,
        tab_size=body.tab_size,
    )
    cursor = 0
    for label in sorted(labels, key=lambda item: item.target.start):
        start = label.target.start
        end = label.target.end
        output.append_text(body[cursor:start])
        output.append_text(_ref_label_prefix(label, pending_prefix=pending_prefix))
        target = body[start:end]
        marker = _ref_target_marker(label.target, dangling=label.dangling)
        style = (
            _REF_LABEL_DANGLING_STYLE
            if label.dangling
            else _ref_link_accent_style(marker.accent, surface)
        )
        target.stylize(style, 0, len(target.plain))
        output.append_text(target)
        if label.dangling:
            output.append(f" {_REF_DANGLING_TEXT}", style=_REF_LABEL_DANGLING_STYLE)
        cursor = end
    output.append_text(body[cursor:])
    return output


def _ref_label_prefix(label: Any, *, pending_prefix: str) -> Text:
    marker = _ref_target_marker(label.target, dangling=label.dangling)
    text = Text()
    text.append(
        f"[{label.hint}]",
        style=_ref_label_style(label, pending_prefix=pending_prefix),
    )
    icon_style = _ref_label_icon_style(label, marker, pending_prefix=pending_prefix)
    text.append(f"{marker.icon}{_REF_NO_BREAK_SPACE}", style=icon_style)
    return text


def _ref_label_icon_style(
    label: Any,
    marker: _RefTargetMarker,
    *,
    pending_prefix: str,
) -> str:
    if label.dangling:
        return _REF_LABEL_DANGLING_STYLE
    if pending_prefix and not label.hint.startswith(pending_prefix):
        return f"{_REF_LABEL_DIM_STYLE} bold {marker.accent}"
    return f"bold {marker.accent}"


def _ref_label_style(label: Any, *, pending_prefix: str) -> str:
    if label.dangling:
        return _REF_LABEL_DANGLING_STYLE
    if not pending_prefix:
        return _REF_LABEL_STYLE
    hint = label.hint
    return (
        _REF_LABEL_MATCH_STYLE
        if hint.startswith(pending_prefix)
        else _REF_LABEL_DIM_STYLE
    )


def _ref_target_marker(target: Any, *, dangling: bool) -> _RefTargetMarker:
    if dangling:
        return _RefTargetMarker(_REF_DANGLING_ICON, _REF_DANGLING_ACCENT)
    if target.kind == LinkSpanKind.URL.value:
        return _RefTargetMarker(_REF_URL_ICON, EXTERNAL_ACCENT)
    attachment_marker = _ref_attachment_target_marker(target)
    if attachment_marker is not None:
        return attachment_marker
    tab = _ref_target_artifact_tab(target)
    if tab is None:
        return _RefTargetMarker(_REF_DEFAULT_LINK_ICON, _REF_DEFAULT_LINK_ACCENT)
    if tab == "ref:plan":
        return _RefTargetMarker(_REF_PLAN_REF_ICON, ARTIFACTS_ACCENTS[tab])
    return _RefTargetMarker(
        ARTIFACTS_ICONS.get(tab, _REF_DEFAULT_LINK_ICON),
        ARTIFACTS_ACCENTS.get(tab, _REF_DEFAULT_LINK_ACCENT),
    )


_REF_ATTACHMENT_ICONS: dict[str, tuple[str, str]] = {
    "image": ("🖼", "#FFAF5F"),
    "video": ("🎞", "#FFAF5F"),
    "pdf": ("📕", "#FFAF5F"),
    "text": ("≡", "#FFAF5F"),
    "archive": ("▤", "#FFAF5F"),
    "audio": ("♫", "#FFAF5F"),
    "other": ("◇", "#FFAF5F"),
    "attachment": ("📎", "#FFAF5F"),
}

_REF_ATTACHMENT_SUFFIX_ICONS: tuple[tuple[tuple[str, ...], str, str], ...] = (
    (
        (".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tiff", ".tif"),
        "🖼",
        "#FFAF5F",
    ),
    ((".mp4", ".mov", ".mkv", ".webm", ".ogv"), "🎞", "#FFAF5F"),
    ((".mp3", ".wav", ".flac", ".ogg", ".opus"), "♫", "#FFAF5F"),
    ((".pdf",), "📕", "#FFAF5F"),
    (
        (
            ".md",
            ".txt",
            ".log",
            ".json",
            ".jsonl",
            ".yaml",
            ".yml",
            ".toml",
            ".csv",
            ".diff",
            ".patch",
            ".py",
            ".rs",
            ".ts",
            ".sh",
        ),
        "≡",
        "#FFAF5F",
    ),
    ((".zip", ".tar", ".gz", ".bz2", ".xz", ".zst", ".7z"), "▤", "#FFAF5F"),
)


def _ref_attachment_target_marker(target: Any) -> _RefTargetMarker | None:
    ref = target.target if isinstance(target.target, str) else target.text
    if not isinstance(ref, str) or not ref.lower().startswith("attachment:"):
        return None
    payload = ref.split(":", 1)[1] if ":" in ref else ""
    name = payload.rsplit("/", 1)[-1].lower() if payload else ""
    for suffixes, icon, accent in _REF_ATTACHMENT_SUFFIX_ICONS:
        if name.endswith(suffixes):
            return _RefTargetMarker(icon, accent)
    icon, accent = _REF_ATTACHMENT_ICONS["attachment"]
    return _RefTargetMarker(icon, accent)


def _ref_target_artifact_tab(target: Any) -> str | None:
    if target.kind == LinkSpanKind.ARTIFACT_REF.value:
        ref = target.target if isinstance(target.target, str) else target.text
        ref_kind = ref.split(":", 1)[0].lower()
        return _REF_KIND_TABS.get(ref_kind)
    if target.kind == LinkSpanKind.BARE_TOKEN.value:
        return "beads" if target.text.startswith("sase-") else "patches"
    return _REF_DIRECT_KIND_TABS.get(target.kind.lower())


def _ref_section_icon(kind: str) -> str:
    tab = _REF_SECTION_KIND_TAB.get(kind)
    if tab is None:
        return _REF_DEFAULT_SECTION_ICON
    return ARTIFACTS_ICONS.get(tab, _REF_DEFAULT_SECTION_ICON)


def _ref_section_accent(kind: str) -> str:
    tab = _REF_SECTION_KIND_TAB.get(kind)
    if tab is None:
        return _REF_DEFAULT_SECTION_ACCENT
    return ARTIFACTS_ACCENTS.get(tab, _REF_DEFAULT_SECTION_ACCENT)


def _ref_section_rule(
    section: PagerSection,
    *,
    index: int,
    total: int,
    width: int,
) -> Text:
    glyph = _ref_section_icon(section.kind)
    accent = _ref_section_accent(section.kind)
    marker = f"{index}/{total}"
    line = Text()
    line.append(f"{_REF_DIVIDER_CHAR}{_REF_DIVIDER_CHAR} ", style="dim")
    line.append(marker, style=f"bold {accent}")
    line.append(f" {_REF_DIVIDER_CHAR} ", style="dim")
    line.append(f"{glyph} ", style=accent)
    append_path_label(line, section.title, style=accent, root_style=MUTED_STYLE)
    prefix_width = cell_len(line.plain) + 1
    fill = _REF_DIVIDER_CHAR * max(width - prefix_width, 0)
    line.append(f" {fill}", style="dim")
    return line


def _ref_section_row_offsets(heights: tuple[int, ...]) -> tuple[int, ...]:
    if not heights:
        return (0,)
    offsets = [0]
    row = heights[0]
    for height in heights[1:]:
        offsets.append(row)
        row += _REF_DIVIDER_LINES + height
    return tuple(offsets)


def _ref_absolute_line_rows(
    section_offset: int,
    section_index: int,
    relative: tuple[int, ...],
) -> tuple[int, ...]:
    body_start = section_offset + (0 if section_index == 0 else _REF_DIVIDER_LINES)
    return tuple(body_start + row for row in relative)


def reference_compose_body(
    document: PagerDocument,
    width: int,
    *,
    label_layer: PagerLabelLayer | None = None,
    pending_prefix: str = "",
    prepared_sections: Mapping[int, Text] | None = None,
    line_mark: LineMark | None = None,
    goto_accent: str | None = None,
    change_marks: Mapping[int, Mapping[int, str]] | None = None,
    removal_anchors: Mapping[int, set[int]] | None = None,
    rail_styles: Mapping[int, str] | None = None,
    history_styles: Any | None = None,
    surface: str | None = None,
) -> ReferenceBody:
    """Frozen copy of the pre-virtualization ``compose_body``."""
    sections = document.sections
    if not sections:
        return ReferenceBody(
            renderable=Group(), section_offsets=(0,), total_height=0, rows=()
        )
    paint_width = max(width, 1)
    max_count = max(
        (_ref_logical_line_count(section.plain_text) for section in sections),
        default=0,
    )
    digits = _ref_number_width(max_count)
    content_width = max(paint_width - _ref_gutter_width(max_count), 1)
    total = len(sections)
    parts: list[RenderableType] = []
    heights: list[int] = []
    relative_line_rows: list[tuple[int, ...]] = []
    for index, section in enumerate(sections):
        if index > 0:
            parts.append(
                _ref_section_rule(
                    section, index=index + 1, total=total, width=paint_width
                )
            )
        resolved_surface = surface
        if resolved_surface is None and history_styles is not None:
            try:
                candidate = getattr(history_styles, "background", None)
                if isinstance(candidate, str) and candidate:
                    resolved_surface = candidate
            except Exception:
                resolved_surface = None
        renderable = _ref_section_renderable(
            section,
            section_index=index,
            label_layer=label_layer,
            pending_prefix=pending_prefix,
            prepared_text=None
            if prepared_sections is None
            else prepared_sections.get(index),
            surface=resolved_surface,
        )
        emphasis_range = (
            line_mark.emphasis_range
            if line_mark is not None and line_mark.section_index == index
            else None
        )
        section_marks = None if change_marks is None else change_marks.get(index)
        section_anchors = (
            None if removal_anchors is None else removal_anchors.get(index)
        )
        section_rail = None if rail_styles is None else rail_styles.get(index)
        painted, height, line_rows = _ref_paint_section_body(
            renderable,
            section,
            paint_width=paint_width,
            content_width=content_width,
            digits=digits,
            emphasis_range=emphasis_range,
            accent=goto_accent if emphasis_range is not None else None,
            change_marks=dict(section_marks) if section_marks is not None else None,
            removal_anchors=set(section_anchors)
            if section_anchors is not None
            else None,
            rail_style=section_rail,
            history_styles=history_styles,
        )
        parts.append(painted)
        heights.append(height)
        relative_line_rows.append(line_rows)
    height_tuple = tuple(heights)
    offsets = _ref_section_row_offsets(height_tuple)
    absolute_line_rows = tuple(
        _ref_absolute_line_rows(offsets[index], index, rows)
        for index, rows in enumerate(relative_line_rows)
    )
    divider_rows = _REF_DIVIDER_LINES * max(len(sections) - 1, 0)
    return ReferenceBody(
        renderable=Group(*parts),
        section_offsets=offsets,
        total_height=sum(heights) + divider_rows,
        section_line_counts=tuple(len(rows) for rows in relative_line_rows),
        section_line_rows=absolute_line_rows,
        rows=_expand_reference_rows(parts, paint_width),
    )


def _expand_reference_rows(
    parts: list[RenderableType], paint_width: int
) -> tuple[Text, ...]:
    rows: list[Text] = []
    for part in parts:
        if isinstance(part, Text):
            rows.extend(part.split("\n"))
            continue
        console = Console(width=max(paint_width, 1), color_system=None, highlight=False)
        part_rows = console.render_lines(part, pad=False)
        if not part_rows:
            rows.append(Text())
            continue
        for segments in part_rows:
            row = Text()
            for segment in segments:
                row.append(segment.text, style=segment.style)
            rows.append(row)
    return tuple(rows)


def _ref_paint_section_body(
    renderable: RenderableType,
    section: PagerSection,
    *,
    paint_width: int,
    content_width: int,
    digits: int,
    emphasis_range: tuple[int, int] | None,
    accent: str | None,
    change_marks: dict[int, str] | None = None,
    removal_anchors: set[int] | None = None,
    rail_style: str | None = None,
    history_styles: Any | None = None,
) -> tuple[RenderableType, int, tuple[int, ...]]:
    if isinstance(renderable, Text):
        guttered = _ref_apply_gutter(
            renderable,
            content_width=content_width,
            number_width=digits,
            emphasis_range=emphasis_range,
            accent=accent,
            change_marks=change_marks,
            removal_anchors=removal_anchors,
            rail_style=rail_style,
            history_styles=history_styles,
        )
        return guttered.text, guttered.row_count, guttered.line_rows
    console = Console(width=max(paint_width, 1), color_system=None, highlight=False)
    height = max(len(console.render_lines(renderable, pad=False)), 1)
    return renderable, height, _ref_estimated_line_rows(section, paint_width)


def _ref_estimated_line_rows(section: PagerSection, width: int) -> tuple[int, ...]:
    from sase.pager.document import section_line_prefix

    count = _ref_logical_line_count(section.plain_text)
    if count == 0:
        return ()
    _starts, start_rows = section_line_prefix(section, width)
    return start_rows[:count]


def _ref_section_renderable(
    section: PagerSection,
    *,
    section_index: int,
    label_layer: PagerLabelLayer | None,
    pending_prefix: str,
    prepared_text: Text | None = None,
    surface: str | None = None,
) -> RenderableType:
    if label_layer is None:
        if prepared_text is not None:
            return prepared_text.copy()
        return section.body_renderable
    labels = label_layer.labels_by_section[section_index]
    if not labels:
        if prepared_text is not None:
            return prepared_text.copy()
        return section.body_renderable
    return _ref_render_section_with_labels(
        section,
        labels,
        pending_prefix=pending_prefix,
        source=prepared_text,
        surface=surface,
    )


def expand_group_rows(renderable: Group, paint_width: int) -> tuple[Text, ...]:
    """Expand a live ``compose_body`` group into row texts for comparison."""
    return _expand_reference_rows(list(renderable.renderables), paint_width)
