"""Frozen reference composer for the virtual body line model.

Part of the frozen oracle split from ``tests/pager/_reference_compose.py``:
copied verbatim from the pre-virtualization ``compose_body`` /
``_paint_section_body`` pipeline (with section-rule rendering) and frozen.
Do not edit this file. If a parity test fails after a src change, the src
change moved rendering — that is the signal, not an excuse to update the
oracle.

Gutter and label rendering live in ``tests.pager._reference_gutter`` and
``tests.pager._reference_labels``; this module imports only their public
(``ref_*``) entry points.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from rich.cells import cell_len
from rich.console import Console, Group, RenderableType
from rich.text import Text

from sase.ace.tui._artifact_tab_model import (
    ARTIFACTS_ACCENTS,
    ARTIFACTS_ICONS,
)
from sase.pager._labels import PagerLabelLayer
from sase.pager._line_mark import LineMark
from sase.pager._trail_chrome_model import MUTED_STYLE
from sase.pager._trail_chrome_text import append_path_label
from sase.pager.document import PagerDocument, PagerSection
from tests.pager._reference_gutter import (
    ref_apply_gutter,
    ref_gutter_width,
    ref_number_width,
)
from tests.pager._reference_labels import ref_render_section_with_labels

_REF_DIVIDER_LINES = 1
_REF_DIVIDER_CHAR = "━"
_REF_SECTION_KIND_TAB: Mapping[str, str] = {
    "bead": "beads",
    "file": "files",
    "agent": "agents",
}
_REF_DEFAULT_SECTION_ICON = "◆"
_REF_DEFAULT_SECTION_ACCENT = "#AFAFAF"


@dataclass(frozen=True, slots=True)
class ReferenceBody:
    """One document rendered at a fixed width, with expanded row texts."""

    renderable: RenderableType
    section_offsets: tuple[int, ...]
    total_height: int
    section_line_counts: tuple[int, ...] = ()
    section_line_rows: tuple[tuple[int, ...], ...] = ()
    rows: tuple[Text, ...] = ()


def _ref_logical_line_count(text: str) -> int:
    if not text:
        return 0
    count = text.count("\n")
    if text.endswith("\n"):
        return count
    return count + 1


def _ref_section_icon(kind: str) -> str:
    tab = _REF_SECTION_KIND_TAB.get(kind)
    if tab is None:
        return _REF_DEFAULT_SECTION_ICON
    return ARTIFACTS_ICONS.get(tab, _REF_DEFAULT_SECTION_ICON)


def _ref_section_accent(kind: str) -> str:
    tab = _REF_SECTION_KIND_TAB.get(kind)
    if tab is None:
        return _REF_DEFAULT_SECTION_ACCENT
    return ARTIFACTS_ACCENTS.get(tab, _REF_DEFAULT_SECTION_ACCENT)


def _ref_section_rule(
    section: PagerSection,
    *,
    index: int,
    total: int,
    width: int,
) -> Text:
    glyph = _ref_section_icon(section.kind)
    accent = _ref_section_accent(section.kind)
    marker = f"{index}/{total}"
    line = Text()
    line.append(f"{_REF_DIVIDER_CHAR}{_REF_DIVIDER_CHAR} ", style="dim")
    line.append(marker, style=f"bold {accent}")
    line.append(f" {_REF_DIVIDER_CHAR} ", style="dim")
    line.append(f"{glyph} ", style=accent)
    append_path_label(line, section.title, style=accent, root_style=MUTED_STYLE)
    prefix_width = cell_len(line.plain) + 1
    fill = _REF_DIVIDER_CHAR * max(width - prefix_width, 0)
    line.append(f" {fill}", style="dim")
    return line


def _ref_section_row_offsets(heights: tuple[int, ...]) -> tuple[int, ...]:
    if not heights:
        return (0,)
    offsets = [0]
    row = heights[0]
    for height in heights[1:]:
        offsets.append(row)
        row += _REF_DIVIDER_LINES + height
    return tuple(offsets)


def _ref_absolute_line_rows(
    section_offset: int,
    section_index: int,
    relative: tuple[int, ...],
) -> tuple[int, ...]:
    body_start = section_offset + (0 if section_index == 0 else _REF_DIVIDER_LINES)
    return tuple(body_start + row for row in relative)


def reference_compose_body(
    document: PagerDocument,
    width: int,
    *,
    label_layer: PagerLabelLayer | None = None,
    pending_prefix: str = "",
    prepared_sections: Mapping[int, Text] | None = None,
    line_mark: LineMark | None = None,
    goto_accent: str | None = None,
    change_marks: Mapping[int, Mapping[int, str]] | None = None,
    removal_anchors: Mapping[int, set[int]] | None = None,
    rail_styles: Mapping[int, str] | None = None,
    history_styles: Any | None = None,
    surface: str | None = None,
) -> ReferenceBody:
    """Frozen copy of the pre-virtualization ``compose_body``."""
    sections = document.sections
    if not sections:
        return ReferenceBody(
            renderable=Group(), section_offsets=(0,), total_height=0, rows=()
        )
    paint_width = max(width, 1)
    max_count = max(
        (_ref_logical_line_count(section.plain_text) for section in sections),
        default=0,
    )
    digits = ref_number_width(max_count)
    content_width = max(paint_width - ref_gutter_width(max_count), 1)
    total = len(sections)
    parts: list[RenderableType] = []
    heights: list[int] = []
    relative_line_rows: list[tuple[int, ...]] = []
    for index, section in enumerate(sections):
        if index > 0:
            parts.append(
                _ref_section_rule(
                    section, index=index + 1, total=total, width=paint_width
                )
            )
        resolved_surface = surface
        if resolved_surface is None and history_styles is not None:
            try:
                candidate = getattr(history_styles, "background", None)
                if isinstance(candidate, str) and candidate:
                    resolved_surface = candidate
            except Exception:
                resolved_surface = None
        renderable = _ref_section_renderable(
            section,
            section_index=index,
            label_layer=label_layer,
            pending_prefix=pending_prefix,
            prepared_text=None
            if prepared_sections is None
            else prepared_sections.get(index),
            surface=resolved_surface,
        )
        emphasis_range = (
            line_mark.emphasis_range
            if line_mark is not None and line_mark.section_index == index
            else None
        )
        section_marks = None if change_marks is None else change_marks.get(index)
        section_anchors = (
            None if removal_anchors is None else removal_anchors.get(index)
        )
        section_rail = None if rail_styles is None else rail_styles.get(index)
        painted, height, line_rows = _ref_paint_section_body(
            renderable,
            section,
            paint_width=paint_width,
            content_width=content_width,
            digits=digits,
            emphasis_range=emphasis_range,
            accent=goto_accent if emphasis_range is not None else None,
            change_marks=dict(section_marks) if section_marks is not None else None,
            removal_anchors=set(section_anchors)
            if section_anchors is not None
            else None,
            rail_style=section_rail,
            history_styles=history_styles,
        )
        parts.append(painted)
        heights.append(height)
        relative_line_rows.append(line_rows)
    height_tuple = tuple(heights)
    offsets = _ref_section_row_offsets(height_tuple)
    absolute_line_rows = tuple(
        _ref_absolute_line_rows(offsets[index], index, rows)
        for index, rows in enumerate(relative_line_rows)
    )
    divider_rows = _REF_DIVIDER_LINES * max(len(sections) - 1, 0)
    return ReferenceBody(
        renderable=Group(*parts),
        section_offsets=offsets,
        total_height=sum(heights) + divider_rows,
        section_line_counts=tuple(len(rows) for rows in relative_line_rows),
        section_line_rows=absolute_line_rows,
        rows=_expand_reference_rows(parts, paint_width),
    )


def _expand_reference_rows(
    parts: list[RenderableType], paint_width: int
) -> tuple[Text, ...]:
    rows: list[Text] = []
    for part in parts:
        if isinstance(part, Text):
            rows.extend(part.split("\n"))
            continue
        console = Console(width=max(paint_width, 1), color_system=None, highlight=False)
        part_rows = console.render_lines(part, pad=False)
        if not part_rows:
            rows.append(Text())
            continue
        for segments in part_rows:
            row = Text()
            for segment in segments:
                row.append(segment.text, style=segment.style)
            rows.append(row)
    return tuple(rows)


def _ref_paint_section_body(
    renderable: RenderableType,
    section: PagerSection,
    *,
    paint_width: int,
    content_width: int,
    digits: int,
    emphasis_range: tuple[int, int] | None,
    accent: str | None,
    change_marks: dict[int, str] | None = None,
    removal_anchors: set[int] | None = None,
    rail_style: str | None = None,
    history_styles: Any | None = None,
) -> tuple[RenderableType, int, tuple[int, ...]]:
    if isinstance(renderable, Text):
        guttered = ref_apply_gutter(
            renderable,
            content_width=content_width,
            number_width=digits,
            emphasis_range=emphasis_range,
            accent=accent,
            change_marks=change_marks,
            removal_anchors=removal_anchors,
            rail_style=rail_style,
            history_styles=history_styles,
        )
        return guttered.text, guttered.row_count, guttered.line_rows
    console = Console(width=max(paint_width, 1), color_system=None, highlight=False)
    height = max(len(console.render_lines(renderable, pad=False)), 1)
    return renderable, height, _ref_estimated_line_rows(section, paint_width)


def _ref_estimated_line_rows(section: PagerSection, width: int) -> tuple[int, ...]:
    from sase.pager.document import section_line_prefix

    count = _ref_logical_line_count(section.plain_text)
    if count == 0:
        return ()
    _starts, start_rows = section_line_prefix(section, width)
    return start_rows[:count]


def _ref_section_renderable(
    section: PagerSection,
    *,
    section_index: int,
    label_layer: PagerLabelLayer | None,
    pending_prefix: str,
    prepared_text: Text | None = None,
    surface: str | None = None,
) -> RenderableType:
    if label_layer is None:
        if prepared_text is not None:
            return prepared_text.copy()
        return section.body_renderable
    labels = label_layer.labels_by_section[section_index]
    if not labels:
        if prepared_text is not None:
            return prepared_text.copy()
        return section.body_renderable
    return ref_render_section_with_labels(
        section,
        labels,
        pending_prefix=pending_prefix,
        source=prepared_text,
        surface=surface,
    )


def expand_group_rows(renderable: Group, paint_width: int) -> tuple[Text, ...]:
    """Expand a live ``compose_body`` group into row texts for comparison."""
    return _expand_reference_rows(list(renderable.renderables), paint_width)
