"""Frozen reference gutter for the virtual body line model.

Part of the frozen oracle split from ``tests/pager/_reference_compose.py``:
copied verbatim from the pre-virtualization ``apply_gutter`` pipeline and
frozen. Do not edit this file. If a parity test fails after a src change,
the src change moved rendering — that is the signal, not an excuse to
update the oracle.

The gutter entry points needed by ``tests.pager._reference_body`` use
public names (``ref_*``); every other helper stays private to this file.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from rich.console import Console
from rich.text import Text

_REF_SEPARATOR = "│ "
_REF_RAIL_SEPARATOR = "┃ "
_REF_SEPARATOR_STYLE = "dim"
_REF_NUMBER_STYLE = "dim"
_REF_MIN_NUMBER_WIDTH = 2


@dataclass(frozen=True, slots=True)
class _RefGutterSection:
    text: Text
    row_count: int
    line_rows: tuple[int, ...]


def ref_number_width(max_line_count: int) -> int:
    return max(len(str(max(max_line_count, 0))), _REF_MIN_NUMBER_WIDTH)


def ref_gutter_width(max_line_count: int) -> int:
    return ref_number_width(max_line_count) + len(_REF_SEPARATOR)


def ref_apply_gutter(
    text: Text,
    *,
    content_width: int,
    number_width: int,
    emphasis_range: tuple[int, int] | None = None,
    accent: str | None = None,
    change_marks: dict[int, str] | None = None,
    removal_anchors: set[int] | frozenset[int] | tuple[int, ...] | None = None,
    rail_style: str | None = None,
    history_styles: Any | None = None,
) -> _RefGutterSection:
    wrap_width = max(content_width, 1)
    console = Console(
        width=wrap_width,
        color_system=None,
        force_terminal=False,
        highlight=False,
        markup=False,
        emoji=False,
    )
    lo, hi = _ref_normalized_emphasis_range(emphasis_range)
    marks = change_marks or {}
    anchors = set(removal_anchors or ())
    mark_styles = _ref_mark_styles(history_styles)
    lines = _ref_logical_lines(text)
    visual_rows: list[Text] = []
    line_rows: list[int] = []
    if 0 in anchors:
        visual_rows.append(_ref_removal_anchor_row(number_width, mark_styles[2]))
    for line_number, logical in enumerate(lines, start=1):
        line_rows.append(len(visual_rows))
        in_range = lo is not None and hi is not None and lo <= line_number <= hi
        wrapped = _ref_wrap_logical_line(logical, wrap_width, console)
        for wrap_index, piece in enumerate(wrapped):
            number = line_number if wrap_index == 0 else None
            change_kind = marks.get(line_number) if wrap_index == 0 else None
            if in_range:
                visual_rows.append(
                    _ref_guttered_row(
                        piece,
                        number=number,
                        number_width=number_width,
                        emphasize=in_range and number is not None,
                        rail=in_range,
                        accent=accent,
                    )
                )
            elif change_kind in ("added", "changed"):
                visual_rows.append(
                    _ref_change_mark_row(
                        piece,
                        number=number,
                        number_width=number_width,
                        kind=change_kind,
                        mark_styles=mark_styles,
                    )
                )
            else:
                visual_rows.append(
                    _ref_guttered_row(
                        piece,
                        number=number,
                        number_width=number_width,
                        emphasize=False,
                        rail=False,
                        accent=None,
                        rail_style=rail_style,
                    )
                )
        if line_number in anchors:
            visual_rows.append(_ref_removal_anchor_row(number_width, mark_styles[2]))
    if not visual_rows:
        visual_rows.append(
            _ref_guttered_row(
                Text(),
                number=None,
                number_width=number_width,
                emphasize=False,
                rail=False,
                accent=None,
                rail_style=rail_style,
            )
        )
    joined = Text(no_wrap=True, overflow="crop")
    for index, row in enumerate(visual_rows):
        if index:
            joined.append("\n")
        joined.append_text(row)
    return _RefGutterSection(
        text=joined,
        row_count=len(visual_rows),
        line_rows=tuple(line_rows),
    )


def _ref_logical_lines(text: Text) -> tuple[Text, ...]:
    if not text.plain:
        return ()
    return tuple(text.split("\n"))


def _ref_normalized_emphasis_range(
    emphasis_range: tuple[int, int] | None,
) -> tuple[int | None, int | None]:
    if emphasis_range is None:
        return None, None
    lo, hi = emphasis_range
    if lo > hi:
        lo, hi = hi, lo
    return lo, hi


def _ref_wrap_logical_line(
    text: Text, width: int, console: Console
) -> tuple[Text, ...]:
    if not text.plain:
        return (Text(),)
    copied = text.copy()
    copied.overflow = "fold"
    copied.no_wrap = False
    wrapped = tuple(copied.wrap(console, width, overflow="fold"))
    return wrapped if wrapped else (Text(),)


def _ref_mark_styles(history_styles: Any | None) -> tuple[str, str, str]:
    if history_styles is None:
        from sase.pager.history.styles import default_history_styles

        history_styles = default_history_styles()
    return (
        str(getattr(history_styles, "gutter_add", "green")),
        str(getattr(history_styles, "gutter_change", "blue")),
        str(getattr(history_styles, "gutter_remove", "red")),
    )


def _ref_guttered_row(
    piece: Text,
    *,
    number: int | None,
    number_width: int,
    emphasize: bool,
    rail: bool,
    accent: str | None,
    rail_style: str | None = None,
) -> Text:
    row = Text(no_wrap=True, overflow="crop")
    row.append_text(
        _ref_gutter_cells(
            number,
            number_width,
            emphasize=emphasize,
            rail=rail,
            accent=accent,
            rail_style=rail_style,
        )
    )
    row.append_text(piece)
    return row


def _ref_gutter_cells(
    number: int | None,
    number_width: int,
    *,
    emphasize: bool,
    rail: bool,
    accent: str | None,
    rail_style: str | None = None,
) -> Text:
    if number is None:
        label = f"{'':>{number_width}}"
        style = _REF_NUMBER_STYLE
    else:
        label = f"{number:>{number_width}}"
        if emphasize:
            style = f"bold {accent}" if accent else "bold"
        else:
            style = _REF_NUMBER_STYLE
    cells = Text()
    cells.append(label, style=style)
    if rail:
        separator_style = accent if accent else "bold"
        cells.append(_REF_RAIL_SEPARATOR, style=separator_style)
    elif rail_style is not None:
        cells.append(_REF_SEPARATOR, style=rail_style)
    else:
        cells.append(_REF_SEPARATOR, style=_REF_SEPARATOR_STYLE)
    return cells


def _ref_change_mark_row(
    piece: Text,
    *,
    number: int | None,
    number_width: int,
    kind: str,
    mark_styles: tuple[str, str, str] = ("green", "blue", "red"),
) -> Text:
    row = Text(no_wrap=True, overflow="crop")
    label = f"{'':>{number_width}}" if number is None else f"{number:>{number_width}}"
    row.append(label, style=_REF_NUMBER_STYLE)
    if kind == "added":
        row.append("▌ ", style=mark_styles[0])
    else:
        row.append("▌ ", style=mark_styles[1])
    row.append_text(piece)
    return row


def _ref_removal_anchor_row(number_width: int, style: str = "red") -> Text:
    row = Text(no_wrap=True, overflow="crop")
    row.append(f"{'':>{number_width}}", style=_REF_NUMBER_STYLE)
    row.append("╴ ", style=style)
    return row
