"""Frozen reference label renderer for the virtual body line model.

Part of the frozen oracle split from ``tests/pager/_reference_compose.py``:
copied verbatim from the pre-virtualization label-capsule and mark
rendering pipeline and frozen. Do not edit this file. If a parity test
fails after a src change, the src change moved rendering — that is the
signal, not an excuse to update the oracle.

The section renderer needed by ``tests.pager._reference_body`` uses a
public name (``ref_render_section_with_labels``); every other helper stays
private to this file.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from rich.text import Text

from sase.ace.tui._artifact_tab_model import (
    ARTIFACTS_ACCENTS,
    ARTIFACTS_ICONS,
    EXTERNAL_ACCENT,
)
from sase.pager.document import PagerSection
from sase.pager.link_scan import LinkSpanKind

_REF_LABEL_STYLE = "bold black on #FFD75F"
_REF_LABEL_MATCH_STYLE = "bold black on #FFFFAF"
_REF_LABEL_DIM_STYLE = "dim"
_REF_LABEL_DANGLING_STYLE = "dim"
_REF_DANGLING_ICON = "⊘"
_REF_DANGLING_ACCENT = "#808080"
_REF_DANGLING_TEXT = "(missing)"
_REF_DEFAULT_LINK_ICON = "•"
_REF_DEFAULT_LINK_ACCENT = EXTERNAL_ACCENT
_REF_PLAN_REF_ICON = "✎"
_REF_URL_ICON = "↗"
_REF_NO_BREAK_SPACE = "\u00a0"

_REF_KIND_TABS: Mapping[str, str] = {
    "agent": "agents",
    "bead": "beads",
    "file": "files",
    "patch": "patches",
    "plan": "ref:plan",
    "stitch": "stitches",
}
_REF_DIRECT_KIND_TABS: Mapping[str, str] = {
    **_REF_KIND_TABS,
    "agents": "agents",
    "beads": "beads",
    "files": "files",
    "patches": "patches",
    "stitches": "stitches",
    LinkSpanKind.FILE_PATH.value: "files",
}


@dataclass(frozen=True, slots=True)
class _RefTargetMarker:
    icon: str
    accent: str


def ref_render_section_with_labels(
    section: PagerSection,
    labels: Any,
    *,
    pending_prefix: str = "",
    source: Text | None = None,
    surface: str | None = None,
) -> Text:
    body = section.body_text if source is None else source
    if not labels:
        return body
    output = Text(
        style=body.style,
        justify=body.justify,
        overflow=body.overflow,
        no_wrap=body.no_wrap,
        tab_size=body.tab_size,
    )
    cursor = 0
    for label in sorted(labels, key=lambda item: item.target.start):
        start = label.target.start
        end = label.target.end
        output.append_text(body[cursor:start])
        output.append_text(_ref_label_prefix(label, pending_prefix=pending_prefix))
        target = body[start:end]
        marker = _ref_target_marker(label.target, dangling=label.dangling)
        style = (
            _REF_LABEL_DANGLING_STYLE
            if label.dangling
            else _ref_link_accent_style(marker.accent, surface)
        )
        target.stylize(style, 0, len(target.plain))
        output.append_text(target)
        if label.dangling:
            output.append(f" {_REF_DANGLING_TEXT}", style=_REF_LABEL_DANGLING_STYLE)
        cursor = end
    output.append_text(body[cursor:])
    return output


def _ref_link_accent_style(accent: str, surface: str | None = None) -> str:
    if surface is None:
        return f"bold {accent}"
    try:
        from sase.pager.syntax_theme import (
            ensure_contrast_min,
            parse_color,
        )

        if parse_color(surface) is None or parse_color(accent) is None:
            return f"bold {accent}"
        corrected = ensure_contrast_min(accent, surface, accent, 4.5)
        return f"bold {corrected}"
    except Exception:
        return f"bold {accent}"


def _ref_label_prefix(label: Any, *, pending_prefix: str) -> Text:
    marker = _ref_target_marker(label.target, dangling=label.dangling)
    text = Text()
    text.append(
        f"[{label.hint}]",
        style=_ref_label_style(label, pending_prefix=pending_prefix),
    )
    icon_style = _ref_label_icon_style(label, marker, pending_prefix=pending_prefix)
    text.append(f"{marker.icon}{_REF_NO_BREAK_SPACE}", style=icon_style)
    return text


def _ref_label_icon_style(
    label: Any,
    marker: _RefTargetMarker,
    *,
    pending_prefix: str,
) -> str:
    if label.dangling:
        return _REF_LABEL_DANGLING_STYLE
    if pending_prefix and not label.hint.startswith(pending_prefix):
        return f"{_REF_LABEL_DIM_STYLE} bold {marker.accent}"
    return f"bold {marker.accent}"


def _ref_label_style(label: Any, *, pending_prefix: str) -> str:
    if label.dangling:
        return _REF_LABEL_DANGLING_STYLE
    if not pending_prefix:
        return _REF_LABEL_STYLE
    hint = label.hint
    return (
        _REF_LABEL_MATCH_STYLE
        if hint.startswith(pending_prefix)
        else _REF_LABEL_DIM_STYLE
    )


def _ref_target_marker(target: Any, *, dangling: bool) -> _RefTargetMarker:
    if dangling:
        return _RefTargetMarker(_REF_DANGLING_ICON, _REF_DANGLING_ACCENT)
    if target.kind == LinkSpanKind.URL.value:
        return _RefTargetMarker(_REF_URL_ICON, EXTERNAL_ACCENT)
    attachment_marker = _ref_attachment_target_marker(target)
    if attachment_marker is not None:
        return attachment_marker
    tab = _ref_target_artifact_tab(target)
    if tab is None:
        return _RefTargetMarker(_REF_DEFAULT_LINK_ICON, _REF_DEFAULT_LINK_ACCENT)
    if tab == "ref:plan":
        return _RefTargetMarker(_REF_PLAN_REF_ICON, ARTIFACTS_ACCENTS[tab])
    return _RefTargetMarker(
        ARTIFACTS_ICONS.get(tab, _REF_DEFAULT_LINK_ICON),
        ARTIFACTS_ACCENTS.get(tab, _REF_DEFAULT_LINK_ACCENT),
    )


_REF_ATTACHMENT_ICONS: dict[str, tuple[str, str]] = {
    "image": ("🖼", "#FFAF5F"),
    "video": ("🎞", "#FFAF5F"),
    "pdf": ("📕", "#FFAF5F"),
    "text": ("≡", "#FFAF5F"),
    "archive": ("▤", "#FFAF5F"),
    "audio": ("♫", "#FFAF5F"),
    "other": ("◇", "#FFAF5F"),
    "attachment": ("📎", "#FFAF5F"),
}

_REF_ATTACHMENT_SUFFIX_ICONS: tuple[tuple[tuple[str, ...], str, str], ...] = (
    (
        (".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tiff", ".tif"),
        "🖼",
        "#FFAF5F",
    ),
    ((".mp4", ".mov", ".mkv", ".webm", ".ogv"), "🎞", "#FFAF5F"),
    ((".mp3", ".wav", ".flac", ".ogg", ".opus"), "♫", "#FFAF5F"),
    ((".pdf",), "📕", "#FFAF5F"),
    (
        (
            ".md",
            ".txt",
            ".log",
            ".json",
            ".jsonl",
            ".yaml",
            ".yml",
            ".toml",
            ".csv",
            ".diff",
            ".patch",
            ".py",
            ".rs",
            ".ts",
            ".sh",
        ),
        "≡",
        "#FFAF5F",
    ),
    ((".zip", ".tar", ".gz", ".bz2", ".xz", ".zst", ".7z"), "▤", "#FFAF5F"),
)


def _ref_attachment_target_marker(target: Any) -> _RefTargetMarker | None:
    ref = target.target if isinstance(target.target, str) else target.text
    if not isinstance(ref, str) or not ref.lower().startswith("attachment:"):
        return None
    payload = ref.split(":", 1)[1] if ":" in ref else ""
    name = payload.rsplit("/", 1)[-1].lower() if payload else ""
    for suffixes, icon, accent in _REF_ATTACHMENT_SUFFIX_ICONS:
        if name.endswith(suffixes):
            return _RefTargetMarker(icon, accent)
    icon, accent = _REF_ATTACHMENT_ICONS["attachment"]
    return _RefTargetMarker(icon, accent)


def _ref_target_artifact_tab(target: Any) -> str | None:
    if target.kind == LinkSpanKind.ARTIFACT_REF.value:
        ref = target.target if isinstance(target.target, str) else target.text
        ref_kind = ref.split(":", 1)[0].lower()
        return _REF_KIND_TABS.get(ref_kind)
    if target.kind == LinkSpanKind.BARE_TOKEN.value:
        return "beads" if target.text.startswith("sase-") else "patches"
    return _REF_DIRECT_KIND_TABS.get(target.kind.lower())
